# Initially generated by GitHub Copilot.
"""Compare vendored file copies to their MAM-basics sources.

Outputs SHA256 identity check + last-git-commit date for each copy.
Results written to out/vendoring_compare_out.txt.
"""

import hashlib
import subprocess
import sys
from pathlib import Path

from py_vendoring.discover import iter_compare_copies, source_pkg_dirs

_MAM = Path(__file__).resolve().parents[2]
_REPOS = _MAM.parent


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _git_log_date(repo_path: Path, rel_file: str) -> str:
    """Return ISO date of last commit touching rel_file in repo_path, or '?'."""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%ci", "--", rel_file],
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
        line = result.stdout.strip()
        if line:
            return line[:10]  # YYYY-MM-DD
        return "no-commits"
    except Exception as e:
        return f"err:{e}"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    source_pkg_dir_map = source_pkg_dirs()

    rows = []
    for filename, src_pkg, dest_repo, dest_rel, notes in iter_compare_copies():
        src_path = _MAM / source_pkg_dir_map[src_pkg] / filename
        dest_path = _REPOS / dest_repo / dest_rel

        src_hash = _sha256(src_path) if src_path.exists() else "MISSING-SRC"
        dest_hash = _sha256(dest_path) if dest_path.exists() else "MISSING-DEST"

        identity_str = (
            "identical"
            if src_hash == dest_hash
            else ("DIFFERS" if dest_hash != "MISSING-DEST" else "MISSING-DEST")
        )
        last_synced = _git_log_date(_REPOS / dest_repo, dest_rel)

        rows.append(
            {
                "file": filename,
                "src_pkg": src_pkg,
                "dest_repo": dest_repo,
                "dest_path": dest_rel,
                "identity": identity_str,
                "last_synced": last_synced,
                "hint_notes": notes,
            }
        )

    out = _MAM / "out" / "vendoring_compare_out.txt"
    with out.open("w", encoding="utf-8") as f:
        f.write(
            f"{'FILE':<42} {'DEST_REPO':<26} {'DEST_PATH':<55} {'IDENTITY':<14} {'LAST_SYNCED':<12} HINT_NOTES\n"
        )
        f.write("-" * 180 + "\n")
        for r in rows:
            f.write(
                f"{r['file']:<42} {r['dest_repo']:<26} {r['dest_path']:<55} {r['identity']:<14} {r['last_synced']:<12} {r['hint_notes']}\n"
            )

    print(f"Wrote {len(rows)} rows to {out}")
