# Initially generated by GitHub Copilot.
"""Shared MAM-parsed authored-doc build traversal with explicit claims."""

from pathlib import Path

from author_util.claim import ClaimCollection
from mb_misc import styles_mam_parsed


def build_docs_with_explicit_claims(
    out_dir: str | Path,
    *,
    css_href: str = "style.css",
) -> ClaimCollection:
    """Generate all MAM-parsed authored docs and return explicit claims."""
    claims = ClaimCollection()
    out_dir_path = Path(out_dir)
    from author import mp_cmn
    from author import mpplain
    from author import mpplus
    from author import mpplus_aot
    from author import mpplus_kq_special
    from author import mpplus_haarah_2
    from author import mpplus_kaful
    from author import mpplus_good_ending

    mp_cmn.populate_claims(claims=claims)
    styles_mam_parsed.make_css_file_for_mam_parsed(str(out_dir_path / css_href))
    tdm_ch = str(out_dir_path), css_href
    mpplain.gen_html_file(tdm_ch, claims=claims)
    mpplus.gen_html_file(tdm_ch, claims=claims)
    mpplus_aot.gen_html_file(tdm_ch, claims=claims)
    mpplus_kq_special.gen_html_file(tdm_ch, claims=claims)
    mpplus_haarah_2.gen_html_file(tdm_ch, claims=claims)
    mpplus_kaful.gen_html_file(tdm_ch, claims=claims)
    mpplus_good_ending.gen_html_file(tdm_ch, claims=claims)

    return claims
