# Initially generated by GitHub Copilot.
"""Other row families and selectors extracted from mp_cmn."""

from author import mp_cmn_claims_core as _claims_core
from author_util import author

_claim_def = _claims_core.claim_def

_GOOD_ENDING_TMPL_DOC = "mpplus_good_ending_tmpl.html"
_DOCNOTE_DOC = "mpplus_docnote.html"


def _docnote_row(docnote_doc):
    return [
        author.hbo("נוסח"),
        [
            "Documentation template. See ",
            author.anchor_h(
                "its dedicated page",
                docnote_doc,
            ),
            ".",
        ],
    ]


def _good_ending_row(good_ending_doc):
    return [
        author.hbo("מ:סיום בטוב"),
        [
            "Good ending. See ",
            author.anchor_h(
                "its dedicated page",
                good_ending_doc,
            ),
            ".",
        ],
    ]


OTHER_ROWS = [
    [
        [author.hbo("פפ"), " / ", author.hbo("סס")],
        "$Parashah $petuxah / $setumah (primarily in D column)",
    ],
    [
        author.hbo("מ:אות מנוקדת"),
        "Dotted letter/word. Marks words with masoretic dots above/below.",
    ],
    _good_ending_row(_GOOD_ENDING_TMPL_DOC),
    [
        author.hbo("מ:טעם ומתג באות אחת"),
        "Normalization-robust meteg for 10 cases where a below-accent and meteg share one letter.",
    ],
    [
        author.hbo("מ:גרש ותלישא גדולה"),
        "Combined $geresh + $telisha gedolah (2 words, 3 uses). No parameters.",
    ],
    [
        author.hbo("מ:גרשיים ותלישא גדולה"),
        "Combined gershayim + $telisha gedolah (3 words, 4 uses). No parameters.",
    ],
    [
        author.hbo("ססס"),
        "Closed $parashah ($setumah) variant appearing mid-line after a blank space, rather than at the start of the next line.",
    ],
    [
        author.hbo("פפפ"),
        "Open $parashah ($petuxah) variant starting at the very top of the next line, without an intervening blank line.",
    ],
    [
        author.hbo("רווח בסוף שורה"),
        "Large end-of-line spacers supporting פפפ; fills remaining line space so the next $parashah can start at the top of the following line.",
    ],
    [
        author.hbo("מ:ששש"),
        "$Setumah-like section divider for the 8 shirah (song) sections in the 21 prose books; analogous to ססס.",
    ],
    [
        author.hbo("מ:כל קמץ קטן מרכא"),
        "Font-rendering workaround for the word כל with $qamats qatan and $merkha in Taamey Frank CLM (2 occurrences: Ps 35:10, Prov 19:7).",
    ],
    _docnote_row(_DOCNOTE_DOC),
    [
        author.hbo("מודגש"),
        "Bold styling within the notes argument (param 2) of נוסח.",
    ],
    [
        author.hbo("ש"),
        "Paragraph separator within the notes argument (param 2) of נוסח.",
    ],
]

MODAG_ONLY_IN_DOCNOTE_PARAM2 = (
    "Template מודגש appears only within the notes argument (param 2) of נוסח."
)

SH_ONLY_IN_DOCNOTE_PARAM2 = (
    "Template ש appears only within the notes argument (param 2) of נוסח."
)

PABP_ARG_VALUE_STRUCT = (
    "Argument value passed as the first positional parameter to"
    " סס, ססס, פפ, or פפפ"
    " when the parashah division appears within a verse rather than between verses."
    " This is a parameter value, not a template name."
    " Verified by corpus assertions in survey_plain.py and survey_plus.py."
)

CLAIM_DEFS = (
    _claim_def(
        "mp.both.templates.other.set",
        OTHER_ROWS,
        kind="enum",
        subject="mp:both",
        data={
            # מ:אות מנוקדת, מ:טעם ומתג באות אחת, מ:גרש ותלישא גדולה,
            # מ:גרשיים ותלישא גדולה, רווח בסוף שורה, מ:כל קמץ קטן מרכא, and מ:סיום בטוב
            # appear only in the plain survey. Verified in PLAIN_ONLY.
            "templates": [
                "פפ",
                "סס",
                "ססס",
                "פפפ",
                "מ:ששש",
                "נוסח",
                "מודגש",
                "ש",
            ]
        },
    ),
    _claim_def(
        "mp.both.templates.sampe.pabp-arg-value",
        PABP_ARG_VALUE_STRUCT,
        kind="struct",
        subject="mp:both",
        data={
            "arg_value": "פסקא באמצע פסוק",
            "templates": ["סס", "ססס", "פפ", "פפפ"],
        },
    ),
    _claim_def(
        "mp.both.templates.modag.only-in-docnote-param2",
        MODAG_ONLY_IN_DOCNOTE_PARAM2,
        kind="struct",
        subject="mp:both",
        data={
            "template": "מודגש",
            "parent_template": "נוסח",
            "parent_param": "2",
        },
    ),
    _claim_def(
        "mp.both.templates.sh.only-in-docnote-param2",
        SH_ONLY_IN_DOCNOTE_PARAM2,
        kind="struct",
        subject="mp:both",
        data={
            "template": "ש",
            "parent_template": "נוסח",
            "parent_param": "2",
        },
    ),
)

OTHER_ROW_TEMPLATE_NAMES = (
    "פפ/סס",
    "מ:אות מנוקדת",
    "מ:סיום בטוב",
    "מ:טעם ומתג באות אחת",
    "מ:גרש ותלישא גדולה",
    "מ:גרשיים ותלישא גדולה",
    "ססס",
    "פפפ",
    "רווח בסוף שורה",
    "מ:ששש",
    "מ:כל קמץ קטן מרכא",
    "נוסח",
    "מודגש",
    "ש",
)

assert len(OTHER_ROW_TEMPLATE_NAMES) == len(OTHER_ROWS)

OTHER_ROW_BY_TEMPLATE = dict(zip(OTHER_ROW_TEMPLATE_NAMES, OTHER_ROWS))


def other_rows_for_templates(template_names):
    missing = [n for n in template_names if n not in OTHER_ROW_BY_TEMPLATE]
    assert not missing, f"unknown other template(s): {sorted(missing)}"
    return [OTHER_ROW_BY_TEMPLATE[n] for n in template_names]


def whitespace_rows_shared():
    return [
        [
            [
                author.hbo("פפ"),
                " / ",
                author.hbo("פפפ"),
                " / ",
                author.hbo("סס"),
                " / ",
                author.hbo("ססס"),
            ],
            [
                "$Parashah $petuxah / $setumah variants."
                " When any of these appears within a verse (rather than between verses),",
                [" it takes the argument ", author.hbo("פסקא באמצע פסוק"), "."],
            ],
        ],
        OTHER_ROW_BY_TEMPLATE["מ:ששש"],
    ]


def other_rows_shared_core(*, docnote_doc=_DOCNOTE_DOC):
    return [
        _docnote_row(docnote_doc),
        OTHER_ROW_BY_TEMPLATE["מודגש"],
        OTHER_ROW_BY_TEMPLATE["ש"],
    ]


def good_ending_row(*, good_ending_doc=_GOOD_ENDING_TMPL_DOC):
    return _good_ending_row(good_ending_doc)


def other_rows_plain_extras(*, good_ending_doc=_GOOD_ENDING_TMPL_DOC):
    return [
        OTHER_ROW_BY_TEMPLATE["מ:אות מנוקדת"],
        _good_ending_row(good_ending_doc),
        OTHER_ROW_BY_TEMPLATE["מ:טעם ומתג באות אחת"],
        OTHER_ROW_BY_TEMPLATE["מ:גרש ותלישא גדולה"],
        OTHER_ROW_BY_TEMPLATE["מ:גרשיים ותלישא גדולה"],
        OTHER_ROW_BY_TEMPLATE["רווח בסוף שורה"],
        OTHER_ROW_BY_TEMPLATE["מ:כל קמץ קטן מרכא"],
    ]

