# Initially generated by GitHub Copilot.
"""Helpers to wire dedicated-page links in common template rows."""

from author_util import author

_KQ_SPECIAL_NAME = author.hbo("מ:כו״ק מיוחד")
_KAFUL_NAME = author.hbo("מ:כפול")


def with_kq_special_dedicated_page_link(kq_rows, *, doc_name: str):
    """Return k/q rows with מ:כו״ק מיוחד pointing to the caller-provided page."""
    out_rows = []
    for tmpl_cell, purpose in kq_rows:
        if tmpl_cell != _KQ_SPECIAL_NAME:
            out_rows.append([tmpl_cell, purpose])
            continue

        out_rows.append(
            [
                tmpl_cell,
                [
                    "Special $ketiv_qere. See ",
                    author.anchor_h("its dedicated page", doc_name),
                    ".",
                ],
            ]
        )

    return out_rows


def with_kaful_dedicated_page_link(accent_rows, *, doc_name: str):
    """Return accent rows with מ:כפול pointing to the caller-provided page."""
    out_rows = []
    for tmpl_cell, purpose in accent_rows:
        if tmpl_cell != _KAFUL_NAME:
            out_rows.append([tmpl_cell, purpose])
            continue

        out_rows.append(
            [
                tmpl_cell,
                [
                    "Dual-trope span. See ",
                    author.anchor_h("its dedicated page", doc_name),
                    ".",
                ],
            ]
        )

    return out_rows
