# Initially generated by GitHub Copilot.
"""Core row families and selectors extracted from mp_cmn."""

from mb_cmn import template_names as tmpln
from author import mp_cmn_claims_core as _claims_core
from author_util import author

_claim_def = _claims_core.claim_def

_KQ_SPECIAL_DOC = "mpplus_kq_special.html"
_KAFUL_DOC = "mpplus_kaful.html"
_TWO_ACCENTS_OF_QUPO_ABBREV = "שני טעמים ..."

KQ_ROWS = [
    [
        author.hbo("כו״ק"),
        [
            "Standard $ketiv_qere. Param 1 = unpointed $ketiv,"
            " param 2 = pointed $qere.",
        ],
    ],
    [
        author.hbo("קו״כ"),
        [
            "Post-$maqaf $ketiv_qere. Same params as ",
            author.hbo("כו״ק"),
            " but used when the pair follows a $maqaf.",
        ],
    ],
    [
        author.hbo("מ:קו״כ-אם-2"),
        [
            "Trivial $ketiv_qere. Param 1 = pointed $ketiv, param 2 = unpointed $ketiv,"
            " param 3 = pointed $qere.",
        ],
    ],
    [
        author.hbo("כתיב ולא קרי"),
        [
            "$Ketiv without $qere. Param 1 = the $ketiv.",
        ],
    ],
    [
        author.hbo("קרי ולא כתיב"),
        [
            "$Qere without $ketiv. Param 1 = the $qere.",
        ],
    ],
    [
        author.hbo("מ:כו״ק מיוחד"),
        [
            "Special $ketiv_qere. See ",
            author.anchor_h(
                "its dedicated page",
                _KQ_SPECIAL_DOC,
            ),
            ".",
        ],
    ],
]

KQ_AM2_SUG_LIST = [
    author.hbo('אל"ף נחה באמצע תיבה ולא נקראת'),
    author.hbo('כתיב ה"א בסיומת של חולם'),
    author.hbo("כתיב הוא קרי היא"),
    author.hbo('כתיב חסר יו"ד בסיומת של קמץ ואחריו וי"ו'),
    author.hbo("כתיב נער קרי נערה"),
]

SPECIAL_LETTER_ROWS = [
    [
        author.hbo("מ:אות-ג"),
        "Large letter. Parameter is the letter along with any diacritical marks.",
    ],
    [
        author.hbo("מ:אות-ק"),
        "Small letter. Parameter is the letter along with any diacritical marks.",
    ],
    [
        author.hbo("מ:אות תלויה"),
        "Suspended (hung) letter. Parameter is the letter along with any diacritical marks.",
    ],
    [
        author.hbo("מ:נו״ן הפוכה"),
        "Reversed (inverted) $nun.",
    ],
]

ACCENT_ROWS = [
    [
        author.hbo("מ:לגרמיה-2"),
        "$Legarmeh. The vertical line ׀ as $legarmeh (part of the word\u2019s cantillation). Shares Unicode with $paseq but differs in function.",
    ],
    [
        author.hbo("מ:פסק"),
        "$Paseq. The vertical line ׀ as $paseq in the narrow sense, i.e. $paseq as distinct from $legarmeh.",
    ],
    [
        author.hbo("מ:מקף אפור"),
        "Gray $maqaf. A $maqaf that is only implicit in the manuscript. Appears only in poetic verses.",
    ],
    [
        author.hbo("מ:דחי"),
        "Deḥi variation. Presents both stress-helped and non-stress-helped versions of a word.",
    ],
    [
        author.hbo("מ:צינור"),
        "Tsinnor variation. Presents both stress-helped and non-stress-helped versions of a word.",
    ],
    [
        author.hbo("גלגל-2"),
        "Galgal. Distinguishes poetic from prose uses of Unicode $YBY.",
    ],
    [
        author.hbo("ירח בן יומו-2"),
        "Yeraḥ ben yomo. Distinguishes prose from poetic uses of Unicode $YBY.",
    ],
    [
        author.hbo("אתנח הפוך"),
        "Atnaḥ hafukh. Helps distinguish this accent from galgal/yeraḥ ben yomo.",
    ],
    [
        author.hbo("מ:קמץ"),
        [
            "Qamats variation. Named params: ",
            author.hbo("ד="),
            " (grammatical) and ",
            author.hbo("ס="),
            " (Sephardic tradition).",
        ],
    ],
    [
        author.hbo("מ:טעם"),
        "Accent extractor. Drops the first code point of its argument, allowing an accent to be specified on a dummy letter for readability.",
    ],
    [
        author.hbo("מ:כפול"),
        [
            "Dual-trope span. See ",
            author.anchor_h(
                "its dedicated page",
                _KAFUL_DOC,
            ),
            ".",
        ],
    ],
    [
        author.hbo(
            _TWO_ACCENTS_OF_QUPO_ABBREV,
            {"title": tmpln.TWO_ACCENTS_OF_QUPO},
        ),
        "Formats the two extra marks (above-accent + patah) on the QUPO Decalogue words (פני and מתחת). Parameter is the above-accent (may use מ:טעם).",
    ],
]

ACCENT_ROW_TEMPLATE_NAMES = (
    "מ:לגרמיה-2",
    "מ:פסק",
    "מ:מקף אפור",
    "מ:דחי",
    "מ:צינור",
    "גלגל-2",
    "ירח בן יומו-2",
    "אתנח הפוך",
    "מ:קמץ",
    "מ:טעם",
    "מ:כפול",
    tmpln.TWO_ACCENTS_OF_QUPO,
)

assert len(ACCENT_ROW_TEMPLATE_NAMES) == len(ACCENT_ROWS)

ACCENT_ROW_BY_TEMPLATE = dict(zip(ACCENT_ROW_TEMPLATE_NAMES, ACCENT_ROWS))


def accent_rows_for_templates(template_names):
    missing = [n for n in template_names if n not in ACCENT_ROW_BY_TEMPLATE]
    assert not missing, f"unknown accent template(s): {sorted(missing)}"
    return [ACCENT_ROW_BY_TEMPLATE[n] for n in template_names]


JER_ROWS = [
    [
        author.hbo("מ:ירושלם"),
        "Handles the masoretic spelling of Jerusalem without $yod. Two params (vowel and accent of $lamed).",
    ],
    [
        author.hbo("מ:ירושלמה"),
        "Like מ:ירושלם but for the directional form \u201cto Jerusalem\u201d (4 cases).",
    ],
]

POETIC_ROWS = [
    [
        author.hbo("ר1"),
        "Following stich on its own line, one indent. In 2 cases (Ps 70, 108) represents a closed $parashah.",
    ],
    [author.hbo("ר2"), "Following stich on its own line, two indents."],
    [author.hbo("ר3"), "Following stich at line start, no indent."],
    [author.hbo("ר4"), "New verse at line start, no indent."],
    [
        author.hbo("ר0"),
        "Extra division point when a verse has an odd number of stiches, for even-column display.",
    ],
    [
        author.hbo("פרשה-מרכז"),
        "Centered title. For \u201ctitles\u201d in Job and Proverbs. Parameter is the title text.",
    ],
]

CLAIM_DEFS = (
    _claim_def(
        "mp.both.templates.kq.set",
        KQ_ROWS,
        kind="enum",
        subject="mp:both",
        data={
            "templates": [
                "כו״ק",
                "קו״כ",
                "מ:קו״כ-אם-2",
                "כתיב ולא קרי",
                "קרי ולא כתיב",
                "מ:כו״ק מיוחד",
            ]
        },
    ),
    _claim_def(
        "mp.both.templates.kq-am2.sug-values",
        KQ_AM2_SUG_LIST,
        kind="enum",
        subject="mp:both",
        data={
            "template": "מ:קו״כ-אם-2",
            "param": "סוג",
            "values": [
                'אל"ף נחה באמצע תיבה ולא נקראת',
                'כתיב ה"א בסיומת של חולם',
                "כתיב הוא קרי היא",
                'כתיב חסר יו"ד בסיומת של קמץ ואחריו וי"ו',
                "כתיב נער קרי נערה",
            ],
        },
    ),
    _claim_def(
        "mp.both.templates.special-letters.set",
        SPECIAL_LETTER_ROWS,
        kind="enum",
        subject="mp:both",
        data={
            "templates": [
                "מ:אות-ג",
                "מ:אות-ק",
                "מ:אות תלויה",
                "מ:נו״ן הפוכה",
            ]
        },
    ),
    _claim_def(
        "mp.both.templates.accents.set",
        ACCENT_ROWS,
        kind="enum",
        subject="mp:both",
        data={
            "templates": [
                "מ:לגרמיה-2",
                "מ:פסק",
                "מ:מקף אפור",
                "מ:דחי",
                "מ:צינור",
                # גלגל-2, ירח בן יומו-2, מ:טעם, and שני טעמים באות אחת קמץ-תחתון-פתח-עליון
                # are boring templates (expanded by mpplus_boring_tmpls.py in plus);
                # they appear only in the plain survey. Verified in PLAIN_ONLY.
                # אתנח הפוך is documented above but absent from the parsed corpus
                # (doc-only per novc_tmpl_survey). Excluded from machine verification.
                "מ:קמץ",
                "מ:כפול",
            ]
        },
    ),
    _claim_def(
        "mp.plain.templates.jerusalem.set",
        JER_ROWS,
        kind="enum",
        subject="mp:plain",
        data={"templates": ["מ:ירושלם", "מ:ירושלמה"]},
    ),
    _claim_def(
        "mp.both.templates.poetic.set",
        POETIC_ROWS,
        kind="enum",
        subject="mp:both",
        data={
            # פרשה-מרכז is a boring template (expanded by mpplus_boring_tmpls.py);
            # it appears only in the plain survey. Verified in PLAIN_ONLY.
            "templates": ["ר1", "ר2", "ר3", "ר4", "ר0"],
        },
    ),
)
