# Initially generated by GitHub Copilot.
"""Shared table data for mpplain and mpplus docs."""

from mb_cmn import template_names as tmpln
from author import mp_cmn_claims_core as _claims_core
from author import mp_cmn_examples_and_file_naming as _examples_and_file_naming
from author import mp_cmn_groups_misc as _groups_misc
from author import mp_cmn_kq_special as _kq_special
from author import mp_cmn_plain_only as _plain_only
from author_util import author
from author_util.claim import ClaimCollection

# ---------------------------------------------------------------------------
# JSON snippets shared by plain and plus common-templates sections
# ---------------------------------------------------------------------------

JSON_KQ = _examples_and_file_naming.JSON_KQ
JSON_KQ_PLUS = _examples_and_file_naming.JSON_KQ_PLUS
JSON_NUSACH = _examples_and_file_naming.JSON_NUSACH
JSON_NUSACH_PLUS = _examples_and_file_naming.JSON_NUSACH_PLUS

# ---------------------------------------------------------------------------
# Table row data
# ---------------------------------------------------------------------------

from author import mp_cmn_rows_core as _rows_core  # noqa: E402

KQ_ROWS = _rows_core.KQ_ROWS
KQ_AM2_SUG_LIST = _rows_core.KQ_AM2_SUG_LIST
SPECIAL_LETTER_ROWS = _rows_core.SPECIAL_LETTER_ROWS
ACCENT_ROWS = _rows_core.ACCENT_ROWS
ACCENT_ROW_TEMPLATE_NAMES = _rows_core.ACCENT_ROW_TEMPLATE_NAMES
ACCENT_ROW_BY_TEMPLATE = _rows_core.ACCENT_ROW_BY_TEMPLATE
accent_rows_for_templates = _rows_core.accent_rows_for_templates
JER_ROWS = _rows_core.JER_ROWS
POETIC_ROWS = _rows_core.POETIC_ROWS
STRUCTURAL_ROWS = _groups_misc.STRUCTURAL_ROWS
NOTE_ROW = _groups_misc.NOTE_ROW
NOTE_ROW_PLAIN = _groups_misc.NOTE_ROW_PLAIN
NOTE_LINKS_ROW = _groups_misc.NOTE_LINKS_ROW
NAVIGATION_ROWS = _groups_misc.NAVIGATION_ROWS

from author import mp_cmn_rows_other as _rows_other  # noqa: E402

OTHER_ROWS = _rows_other.OTHER_ROWS
MODAG_ONLY_IN_NUSACH_PARAM2 = _rows_other.MODAG_ONLY_IN_NUSACH_PARAM2
SH_ONLY_IN_NUSACH_PARAM2 = _rows_other.SH_ONLY_IN_NUSACH_PARAM2
OTHER_ROW_TEMPLATE_NAMES = _rows_other.OTHER_ROW_TEMPLATE_NAMES
OTHER_ROW_BY_TEMPLATE = _rows_other.OTHER_ROW_BY_TEMPLATE
other_rows_for_templates = _rows_other.other_rows_for_templates
other_rows_shared_core = _rows_other.other_rows_shared_core
other_rows_plain_extras = _rows_other.other_rows_plain_extras

_kq_simple_foi_link = _kq_special._kq_simple_foi_link
_kq_simple_foi_link_for_sug = _kq_special._kq_simple_foi_link_for_sug
KQ_SPECIAL_ROWS = _kq_special.KQ_SPECIAL_ROWS
KQ_SPECIAL_SUBTYPE_COUNTS = _kq_special.KQ_SPECIAL_SUBTYPE_COUNTS

ALL_GROUPS_COVER_ALL_OBSERVED = _groups_misc.ALL_GROUPS_COVER_ALL_OBSERVED

PLAIN_ONLY_TAGGING_ONLY_TEMPLATES = _plain_only.PLAIN_ONLY_TAGGING_ONLY_TEMPLATES
PLAIN_ONLY_PRE_EVALUATED_TEMPLATES = _plain_only.PLAIN_ONLY_PRE_EVALUATED_TEMPLATES
PLAIN_ONLY_PRE_EVALUATED_HANDLER_BEHAVIOR = (
    _plain_only.PLAIN_ONLY_PRE_EVALUATED_HANDLER_BEHAVIOR
)
PLAIN_ONLY_MISC_NOT_APPLICABLE_TO_PLUS_TEMPLATES = (
    _plain_only.PLAIN_ONLY_MISC_NOT_APPLICABLE_TO_PLUS_TEMPLATES
)
PLAIN_ONLY_CATEGORY_DEFS = _plain_only.PLAIN_ONLY_CATEGORY_DEFS
PLAIN_ONLY_TEMPLATE_SET = _plain_only.PLAIN_ONLY_TEMPLATE_SET
PLAIN_ONLY_CATEGORY_UNION = _plain_only.PLAIN_ONLY_CATEGORY_UNION
PLAIN_ONLY = _plain_only.PLAIN_ONLY
PLUS_ONLY = _plain_only.PLUS_ONLY

# ---------------------------------------------------------------------------
# Google Sheet URLs, JSON snippets, and file-naming section
# (shared by plain and plus docs)
# ---------------------------------------------------------------------------

SHEETS_TMPL = _examples_and_file_naming.SHEETS_TMPL
SHEETS_DATA = _examples_and_file_naming.SHEETS_DATA
JSON_TOP_LEVEL = _examples_and_file_naming.JSON_TOP_LEVEL
JSON_COMPOSITE = _examples_and_file_naming.JSON_COMPOSITE
JSON_BOOK39 = _examples_and_file_naming.JSON_BOOK39
_FILE_NAMING_ROWS = _examples_and_file_naming._FILE_NAMING_ROWS
s_file_naming = _examples_and_file_naming.s_file_naming


def emit_claims(*, claims: ClaimCollection):
    """Emit mp_cmn claims into an explicit claims collection."""
    _claims_core.emit_claim_defs(
        claims=claims,
        claim_defs=_examples_and_file_naming.CLAIM_DEFS,
    )
    _claims_core.emit_claim_defs(claims=claims, claim_defs=_groups_misc.CLAIM_DEFS)
    _claims_core.emit_claim_defs(claims=claims, claim_defs=_kq_special.CLAIM_DEFS)
    _claims_core.emit_claim_defs(claims=claims, claim_defs=_plain_only.CLAIM_DEFS)
    _claims_core.emit_claim_defs(claims=claims, claim_defs=_rows_core.CLAIM_DEFS)
    _claims_core.emit_claim_defs(claims=claims, claim_defs=_rows_other.CLAIM_DEFS)
