# Initially generated by GitHub Copilot.
"""Shared body builder for poetic spacing templates (ר0–ר4) pages."""

from author_util import author
from author_util.claim import ClaimCollection
from author import mp_cmn as cmn
from author import mp_table_helpers as tblh

_POETIC_TEMPLATE_NAMES = (
    "ר1",
    "ר2",
    "ר3",
    "ר4",
    "ר0",
)


def build_body(*, claims: ClaimCollection, back_doc: str, back_label: str):
    cmn.emit_claim_by_id(claims=claims, claim_id="mp.both.templates.poetic.set")
    poetic_rows = cmn.poetic_rows_for_templates(_POETIC_TEMPLATE_NAMES)
    back_link = author.anchor_h(back_label, back_doc)
    return [
        author.heading_level_1(["Poetic spacing templates — ", author.hbo("ר0–ר4")]),
        author.para(["← Back to ", back_link]),
        author.para(
            "These templates control line placement and indentation in poetic verses."
        ),
        tblh.tmpl_purp_table(poetic_rows),
        author.para(
            "Many editions will choose to skip poetic formatting by treating"
            " ר0–ר4 as simple word spaces."
        ),
    ]