# Initially generated by GitHub Copilot.
"""Shared std_table wrappers for MAM-parsed authored docs."""

from author_util import author

_WIDE_LAST_COL_ATTRS = (None, None, {"class": "wide-col"})
_TMPL_PURPOSE_COL_ATTRS = (
    {"class": "template-col"},
    {"class": "wide-col"},
)


def key_type_desc_table(table_data):
    return author.std_table(
        table_data,
        arg_to_troh=["Key", "Type", "Description"],
        tdattrs=_WIDE_LAST_COL_ATTRS,
        thattrs=_WIDE_LAST_COL_ATTRS,
    )


def key_category_purpose_table(table_data):
    return author.std_table(
        table_data,
        arg_to_troh=["Key", "Category", "Purpose"],
        tdattrs=_WIDE_LAST_COL_ATTRS,
        thattrs=_WIDE_LAST_COL_ATTRS,
    )


def tmpl_purp_table(table_data):
    return author.std_table(
        table_data,
        arg_to_troh=["Template", "Purpose"],
        tdattrs=_TMPL_PURPOSE_COL_ATTRS,
        thattrs=_TMPL_PURPOSE_COL_ATTRS,
    )
