# Initially generated by GitHub Copilot.
"""
HTML document: Word with special letter(s) — מ:אות-מיוחדת-במילה.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplus_aot.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util import json_block
from author_util.claim import ClaimCollection

_FNAME = "mpplus_aot.html"
_TITLE = "Word with special letter(s)"

_PLUS_DOC = "mpplus.html"

_JSON_SPECIAL_LETTER = """\
{
  "tmpl_name": "מ:אות-מיוחדת-במילה",
  "tmpl_params": {
    "1": ["שִׁבְ", {"tmpl_name": "מ:אות-ג", "tmpl_params": {"1": "ט֑"}}, "וֹ"],
    "2": "שִׁבְט֑וֹ",
    "3": "..ט.",
    "4": "ג",
    "5": "ט/ג"
  }
}"""

_AOT_INTRO_CLAIM_ID = "mp.plus.templates.aot.arg5-derivable"
_AOT_INTRO_CLAIM_DATA = {"template": "מ:אות-מיוחדת-במילה"}

_AOT_INTRO_PAYLOAD = [
    "Marks a whole word containing a special (large, small, or suspended) letter."
    " The template encodes the word in two forms:"
    " interrupted (arg 1 — array decomposed around the special letter)"
    " and uninterrupted (args 2–4 — plain word string, dot-mask, and type code)."
    " Args 2–4 together are sufficient to recover all special-letter information"
    " without arg 1 (arg 5 is a redundant letter/type summary, derivable from args 3 and 4):",
]


def _emit_claim_payload(
    claims: ClaimCollection,
    claim_id: str,
    payload,
    *,
    kind: str,
    subject: str,
    data=None,
):
    return claims.claim(claim_id, payload, kind=kind, subject=subject, data=data)


def _aot_intro(*, claims: ClaimCollection):
    return _emit_claim_payload(
        claims,
        _AOT_INTRO_CLAIM_ID,
        _AOT_INTRO_PAYLOAD,
        kind="struct",
        subject="mp:plus",
        data=_AOT_INTRO_CLAIM_DATA,
    )


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplus_aot.html in the given output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def build_body(*, claims: ClaimCollection):
    back_link = author.anchor_h("Reading $MAM-parsed-plus", _PLUS_DOC)
    return [
        author.heading_level_1(
            ["Word with special letter(s) — ", author.hbo("מ:אות-מיוחדת-במילה")]
        ),
        author.para(["← Back to ", back_link]),
        author.para(_aot_intro(claims=claims)),
        json_block.json_block_raw_html(_JSON_SPECIAL_LETTER),
        author.para("Arguments:"),
        author.ordered_list(
            [
                "Array showing the word decomposed around the special letter",
                "The word as a plain string (uninterrupted)",
                "A dot-mask showing the position of the special letter(s)",
                [
                    "The size/type code (",
                    author.hbo("ג"),
                    " = large, ",
                    author.hbo("ק"),
                    " = small, ",
                    author.hbo("ע"),
                    " = hung (suspended))",
                ],
                "Letter/type summary",
            ]
        ),
        author.para(
            [
                "When the word is followed by a $legarmeh, the ",
                author.hbo("מ:לגרמיה-2"),
                " template is included at the end of argument 1,"
                " and the $paseq/$legarmeh character is appended to argument 2.",
            ]
        ),
    ]


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
