# Initially generated by GitHub Copilot.
"""
HTML document: plain-only templates removed from MAM-parsed-plus.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplus_plain_only_templates.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util.claim import ClaimCollection
from author import mp_cmn as cmn

PLAIN_ONLY_TEMPLATES_DOC = "mpplus_plain_only_templates.html"

_PLUS_DOC = "mpplus.html"
_DIFF_FROM_PLAIN_DOC = "mpplus_diff_from_plain.html"
_TITLE = "Plain-only Templates"


def _emit_claim_payload(
    claims: ClaimCollection,
    claim_id: str,
    payload,
    *,
    kind: str,
    subject: str,
    data=None,
):
    return claims.claim(claim_id, payload, kind=kind, subject=subject, data=data)


def _category_table_rows(template_names):
    return [[author.hbo(template_name)] for template_name in template_names]


def _category_table(title: str, template_names):
    return [
        author.heading_level_2([title, f" ({len(template_names)})"]),
        author.std_table(
            _category_table_rows(template_names), arg_to_troh=["Template"]
        ),
    ]


def _pre_evaluated_handler_rows():
    return [
        [author.hbo(template_name), mb_html.code(handler_behavior)]
        for template_name, handler_behavior in cmn.PLAIN_ONLY_PRE_EVALUATED_HANDLER_BEHAVIOR.items()
    ]


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplus_plain_only_templates.html in the given output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(
        __file__,
        tdm_ch,
        PLAIN_ONLY_TEMPLATES_DOC,
        _TITLE,
        cbody,
    )


def build_body(*, claims: ClaimCollection):
    cmn.emit_claim_by_id(claims=claims, claim_id="mp.plain.templates.plain-only.set")
    cmn.emit_claim_by_id(claims=claims, claim_id="mp.plus.templates.plus-only.set")

    _emit_claim_payload(
        claims,
        "mp.plain.docs.plain-only-templates.categories",
        "Every plain-only template appears in exactly one dedicated category.",
        kind="enum",
        subject="mp:plain",
        data={
            "categories": [
                {
                    "name": category_name,
                    "templates": list(templates),
                }
                for category_name, templates in cmn.PLAIN_ONLY_CATEGORY_DEFS
            ]
        },
    )
    _emit_claim_payload(
        claims,
        "mp.plain.docs.plain-only-templates.pre-evaluated.handlers",
        "Pre-evaluated plain-only templates are cross-referenced to mpplus_boring_tmpls.py handler behavior.",
        kind="struct",
        subject="mp:plain",
        data={
            "handler_behavior": dict(cmn.PLAIN_ONLY_PRE_EVALUATED_HANDLER_BEHAVIOR),
            "source_module": "mpplus_boring_tmpls.py",
        },
    )

    back_link = author.anchor_h("Reading $MAM-parsed-plus", _PLUS_DOC)
    diff_link = author.anchor_h("Differences from plain format", _DIFF_FROM_PLAIN_DOC)
    return [
        author.heading_level_1(_TITLE),
        author.para(["← Back to ", back_link]),
        author.para(["← Back to ", diff_link]),
        author.para(
            [
                "This page is exhaustive by reference: each plain-only template appears",
                " exactly once in one of the three categories below.",
                " The category constants in ",
                mb_html.code("author/mp_cmn.py"),
                " are the source of truth.",
            ]
        ),
        *_category_table(
            "Tagging-only templates removed",
            cmn.PLAIN_ONLY_TAGGING_ONLY_TEMPLATES,
        ),
        *_category_table(
            "Pre-evaluated templates removed",
            cmn.PLAIN_ONLY_PRE_EVALUATED_TEMPLATES,
        ),
        author.heading_level_3(
            "Pre-evaluated handler behavior (from mpplus_boring_tmpls.py)"
        ),
        author.std_table(
            _pre_evaluated_handler_rows(),
            arg_to_troh=["Template", "Handler behavior"],
        ),
        *_category_table(
            "Misc. not applicable to plus templates removed",
            cmn.PLAIN_ONLY_MISC_NOT_APPLICABLE_TO_PLUS_TEMPLATES,
        ),
    ]


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
