# Initially generated by GitHub Copilot.
"""HTML document: mpplus-template-call-graphs.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/plus/html/mpplus-template-call-graphs.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util.claim import ClaimCollection
from tmpl_survey import nesting_normal_form

_FNAME = "mpplus-template-call-graphs.html"
_TITLE = "Plus template nesting"  # title is slightly out of sync with the .py/.html filename, but that's fine since the title is more user-facing
_PLUS_DOC = "mpplus.html"
_SVG_FULL = "../svg/plus-call-graph.svg"
_SVG_DUALCANT = "../svg/plus-dualcant-call-graph.svg"
_SVG_DOCNOTE = "../svg/plus-docnote-call-graph.svg"

_PLUS_E_RANK_CATEGORY_SYMBOLS = (
    "choice",
    "doc-note",
    "scrdff-note",
    "$ketiv_qere",
    "choice",
    "choice",
    "word-with-special-letter",
    "misc. terminal",
)


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplus-template-call-graphs.html in the output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def build_body(*, claims: ClaimCollection):
    del claims
    return [
        mb_html.heading_level_1(_TITLE),
        mb_html.heading_level_2("Normal order"),
        *_normal_order(),
        mb_html.heading_level_2("Call graphs"),
        author.para(
            "These call graphs show which plus templates can appear inside other templates."
        ),
        author.para(
            "Each directed edge A → B means template B appears in an argument to template A."
        ),
        author.para(
            "The full graph omits some templates to keep it more readable."
            " The templates omitted include נוסח and מ:כפול."
            " A full list of templates omitted appears on the diagram itself."
        ),
        mb_html.heading_level_2("Full call graph"),
        _svg_object(_SVG_FULL, "Full call graph (SVG not supported)"),
        mb_html.heading_level_2("Focused call graph: dualcant"),
        _svg_object(_SVG_DUALCANT, "Dualcant call graph (SVG not supported)"),
        mb_html.heading_level_2("Focused call graph: docnote"),
        _svg_object(_SVG_DOCNOTE, "Docnote call graph (SVG not supported)"),
    ]


def _normal_order():
    return [
        mb_html.para(
            "MAM-parsed-plus imposes a somewhat arbitrary order on the nesting of templates."
        ),
        author.para(
            "Although the order is somewhat arbitrary, it is important that there be"
            " such an order, to make the data easier to use."
            " As with many standards, the existence of the standard is more important"
            " than the details of the standard."
        ),
        author.para(
            "The order is a partial order on templates."
            " In other words, templates are ordered by equivalence classes."
        ),
        author.para(
            "These equivalence classes can also be thought of as ranks."
            " Templates within an equivalence class are exclusive of each other,"
            " i.e. can never be nested within each other, so there is no need to"
            " define an ordering amongst them."
        ),
        author.para(
            [
                "Here are the ranks for column E,",
                " with symbolic categories that align with sections in the ",
                author.anchor_h("main mpplus document", _PLUS_DOC),
                ".",
            ]
        ),
        author.std_table(
            _plus_e_rank_table_rows(),
            coldirs=["rtl", "ltr"],
            arg_to_troh=["Template(s)", "Category"],
        ),
    ]


_MISC_TERMINAL_LINES = [
    ["מ:אות-ק", "מ:אות-ג", "מ:אות תלויה", "מ:נו״ן הפוכה"],
    #
    ["מ:לגרמיה-2", "מ:פסק", "מ:מקף אפור"],
    #
    ["מ:קישור בהערה", "מ:קישור פנימי בהערה", "מודגש", "ש"],
    #
    ["סס", "ססס", "פפ", "פפפ"],
    #
    ["ר0", "ר1", "ר2", "ר3", "ר4"],
]
_MISC_TERMINAL_ABBR = {
    "מ:קישור בהערה": "...",
    "מ:קישור פנימי בהערה": "...",
}


def _plus_e_rank_table_rows():
    rank_groups = nesting_normal_form.RANK_GROUPS_FOR_PLUS_E
    if len(rank_groups) != len(_PLUS_E_RANK_CATEGORY_SYMBOLS):
        raise ValueError(
            "Expected one symbolic category per plus-E rank group: "
            f"{len(rank_groups)} groups vs "
            f"{len(_PLUS_E_RANK_CATEGORY_SYMBOLS)} symbols"
        )

    out: list[list[object]] = []
    last_rank_index = len(rank_groups) - 1
    for idx, (symbol, templates) in enumerate(
        zip(_PLUS_E_RANK_CATEGORY_SYMBOLS, rank_groups)
    ):
        if idx == last_rank_index:
            out.append([_misc_terminal_templates_cell(templates), symbol])
            continue
        tmpl_comma_sep = ", ".join(sorted(templates))
        out.append([tmpl_comma_sep, symbol])
    return out


def _misc_terminal_templates_cell(last_rank_group: frozenset[str]):
    flattened = [tmpl for line in _MISC_TERMINAL_LINES for tmpl in line]
    if sorted(flattened) != sorted(last_rank_group):
        raise AssertionError(
            "_MISC_TERMINAL_LINES must match sorted last element of "
            "nesting_normal_form.RANK_GROUPS_FOR_PLUS_E"
        )

    lines = []
    for line in _MISC_TERMINAL_LINES:
        abbr_line = [_MISC_TERMINAL_ABBR.get(tmpl, tmpl) for tmpl in line]
        lines.append(", ".join(abbr_line))

    with_breaks: list[object] = []
    for idx, line in enumerate(lines):
        if idx > 0:
            with_breaks.append(mb_html.line_break())
        with_breaks.append(line)

    return with_breaks


def _svg_object(svg_href: str, fallback: str):
    return mb_html.raw_html(
        (f'<object type="image/svg+xml" data="{svg_href}">' f"{fallback}" "</object>")
    )


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
