# Initially generated by GitHub Copilot.
"""HTML document: mpplus-template-call-graphs.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplus-template-call-graphs.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util.claim import ClaimCollection

_FNAME = "mpplus-template-call-graphs.html"
_TITLE = "Plus template call graphs"
_SVG_FULL = "../svg/plus-call-graph.svg"
_SVG_KAFUL = "../svg/plus-kaful-call-graph.svg"
_SVG_NUSACH = "../svg/plus-nusach-call-graph.svg"


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplus-template-call-graphs.html in the output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def build_body(*, claims: ClaimCollection):
    del claims
    return [
        mb_html.heading_level_1(_TITLE),
        author.para(
            "These call graphs show which plus templates can appear inside other templates."
        ),
        author.para(
            "Each directed edge A -> B means template A contains template B as a parameter value."
        ),
        author.blockquote(
            author.para(
                "The full graph omits kaful, nusach, and sh to keep the core shape readable."
            )
        ),
        mb_html.heading_level_2("Full call graph"),
        _svg_object(_SVG_FULL, "Full call graph (SVG not supported)"),
        mb_html.heading_level_2("Focused call graph: kaful"),
        _svg_object(_SVG_KAFUL, "Kaful call graph (SVG not supported)"),
        mb_html.heading_level_2("Focused call graph: nusach"),
        _svg_object(_SVG_NUSACH, "Nusach call graph (SVG not supported)"),
    ]


def _svg_object(svg_href: str, fallback: str):
    return mb_html.raw_html(
        (f'<object type="image/svg+xml" data="{svg_href}">' f"{fallback}" "</object>")
    )


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
