# Initially generated by GitHub Copilot.
"""HTML document: mpplus-template-call-graphs.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/plus/html/mpplus-template-call-graphs.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util.claim import ClaimCollection
from author import mpplus_nesting_normal_order as normal_order

_FNAME = "mpplus-template-call-graphs.html"
_TITLE = "Plus template nesting"  # title is slightly out of sync with the .py/.html filename, but that's fine since the title is more user-facing
_SVG_FULL = "../svg/plus-call-graph.svg"
_SVG_DUALCANT = "../svg/plus-dualcant-call-graph.svg"
_SVG_DOCNOTE = "../svg/plus-docnote-call-graph.svg"


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplus-template-call-graphs.html in the output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def build_body(*, claims: ClaimCollection):
    del claims
    return [
        mb_html.heading_level_1(_TITLE),
        mb_html.heading_level_2("Normal order"),
        *normal_order.build_normal_order(),
        mb_html.heading_level_2("Call graphs"),
        author.para(
            "These call graphs show which plus templates can appear inside other templates."
        ),
        author.para(
            "Each directed edge A → B means template B appears in an argument to template A."
        ),
        author.para(
            "The full graph omits some templates to keep it more readable."
            " The templates omitted include נוסח and מ:כפול."
            " A full list of templates omitted appears on the diagram itself."
        ),
        mb_html.heading_level_2("Full call graph"),
        _svg_object(_SVG_FULL, "Full call graph (SVG not supported)"),
        mb_html.heading_level_2("Focused call graph: dualcant"),
        _svg_object(_SVG_DUALCANT, "Dualcant call graph (SVG not supported)"),
        mb_html.heading_level_2("Focused call graph: docnote"),
        _svg_object(_SVG_DOCNOTE, "Docnote call graph (SVG not supported)"),
    ]


def _svg_object(svg_href: str, fallback: str):
    return mb_html.raw_html(
        (f'<object type="image/svg+xml" data="{svg_href}">' f"{fallback}" "</object>")
    )


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
