# Initially generated by GitHub Copilot.
"""Normal-order section content for mpplus-template-call-graphs.html."""

from mb_cmn import my_utils
from mb_misc import mb_html
from author_util import author
from tmpl_survey import nesting_normal_form

_PLUS_DOC = "mpplus.html"

_PLUS_E_RANK_CATEGORY_SYMBOLS = (
    "choice of cantillation",
    "documentation note",
    "scroll difference note",
    "$ketiv_qere",
    ["choice of $qamats ", author.dquote("size")],
    "choice of stress helper",
    "word with special letter",
    "misc. terminal",
)

_MISC_TERMINAL_LINES = [
    ["מ:אות-ק", "מ:אות-ג", "מ:אות תלויה", "מ:נו״ן הפוכה"],
    #
    ["מ:לגרמיה-2", "מ:פסק", "מ:מקף אפור"],
    #
    ["ש", "מודגש", "מ:קישור בהערה", "מ:קישור פנימי בהערה"],
    #
    ["סס", "ססס", "פפ", "פפפ"],
    #
    ["ר0", "ר1", "ר2", "ר3", "ר4"],
]
_MISC_TERMINAL_ABBR = {
    "מ:אות תלויה": "...",
    "מ:נו״ן הפוכה": "...",
    "מ:קישור בהערה": "...",
    "מ:קישור פנימי בהערה": "...",
}
_KETIV_QERE_LINES = [
    ["כו״ק", "כתיב ולא קרי", "מ:כו״ק מיוחד", "מ:קו״כ-אם-2", "קו״כ", "קרי ולא כתיב"],
]
_KETIV_QERE_ABBR = {
    "מ:כו״ק מיוחד": "...",
    "מ:קו״כ-אם-2": "...",
    "קו״כ": "...",
    "קרי ולא כתיב": "...",
}


def build_normal_order():
    return _normal_order()


def _normal_order():
    return [
        mb_html.para(
            "MAM-parsed-plus imposes a somewhat arbitrary order on the nesting of templates."
        ),
        author.para(
            "Although the order is somewhat arbitrary, it is important that there be"
            " such an order, to make the data easier to use."
            " As with many standards, the existence of the standard is more important"
            " than the details of the standard."
        ),
        author.para(
            "The order is a partial order on templates."
            " In other words, templates are ordered by equivalence classes."
        ),
        author.para(
            "These equivalence classes can also be thought of as ranks."
            " Templates within an equivalence class are exclusive of each other,"
            " i.e. can never be nested within each other, so there is no need to"
            " define an ordering amongst them."
        ),
        author.para(
            [
                "Here are the ranks for column E,",
                " with symbolic categories that align with sections in the ",
                author.anchor_h("main mpplus document", _PLUS_DOC),
                ".",
            ]
        ),
        author.std_table(
            _plus_e_rank_table_rows(),
            coldirs=["rtl", "ltr"],
            arg_to_troh=["Template(s)", "Category"],
        ),
    ]


def _plus_e_rank_table_rows():
    rank_groups = nesting_normal_form.RANK_GROUPS_FOR_PLUS_E
    if len(rank_groups) != len(_PLUS_E_RANK_CATEGORY_SYMBOLS):
        raise ValueError(
            "Expected one symbolic category per plus-E rank group: "
            f"{len(rank_groups)} groups vs "
            f"{len(_PLUS_E_RANK_CATEGORY_SYMBOLS)} symbols"
        )

    out: list[list[object]] = []
    for idx, (symbol, templates) in enumerate(
        zip(_PLUS_E_RANK_CATEGORY_SYMBOLS, rank_groups)
    ):
        rank_handler = _CUSTOM_RANK_HANDLERS.get(idx) or _default_rank_handler
        tmpl_comma_sep = rank_handler(templates)
        out.append([tmpl_comma_sep, symbol])
    return out


def _default_rank_handler(templates: frozenset[str]):
    return ", ".join(sorted(templates))


def _misc_terminal_templates_cell(rank_group: frozenset[str]):
    return _custom_handler(_MISC_TERMINAL_LINES, _MISC_TERMINAL_ABBR, rank_group)


def _ketiv_qere_templates_cell(rank_group: frozenset[str]):
    return _custom_handler(_KETIV_QERE_LINES, _KETIV_QERE_ABBR, rank_group)


def _custom_handler(lines, abbr, rank_group: frozenset[str]):
    flattened = [tmpl for line in lines for tmpl in line]
    assert sorted(flattened) == sorted(rank_group)
    out_lines = []
    for line in lines:
        abbr_line = [abbr.get(tmpl, tmpl) for tmpl in line]
        out_lines.append(", ".join(abbr_line))
    return my_utils.intersperse(mb_html.line_break(), out_lines)


_CUSTOM_RANK_HANDLERS = {
    3: _ketiv_qere_templates_cell,
    7: _misc_terminal_templates_cell,
}
