# Initially generated by GitHub Copilot.
"""
HTML document: good_ending_plus — מ:סיום בטוב.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplus_good_ending.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util import json_block

_FNAME = "mpplus_good_ending.html"
_TITLE = "good_ending_plus"

_PLUS_DOC = "mpplus.html"

_JSON_GOOD_ENDING = """\
{
  "last_chapnver": ["סו", "כד"],
  "wikitext_element": {
    "tmpl_name": "נוסח",
    "tmpl_params": {
      "1": {
        "tmpl_name": "מ:סיום בטוב",
        "tmpl_params": {
          "1": "והיה מדי ... אמר יהוה"
        }
      },
      "2": "=מנהג יפה ... בכתי\\"ל)."
    }
  }
}"""


def gen_html_file(tdm_ch):
    """Generate reading_mam_parsed_plus_good_ending.html in the given output directory."""
    cbody = _build_body()
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def _build_body():
    back_link = mb_html.anchor_h("Reading MAM-parsed-plus", _PLUS_DOC)
    return [
        author.heading_level_1(mb_html.code("good_ending_plus")),
        author.para(["\u2190 Back to ", back_link]),
        author.para(
            [
                "Four books of the Bible end with a verse of rather negative tone."
                " There is a tradition that prevents these verses from being the last"
                " verses recited. The tradition is to recite the next-to-last verse"
                " after reciting the last verse. To facilitate this tradition, some"
                " publications repeat the next-to-last verse, in unpointed form,"
                " after the officially-last verse. The ",
                mb_html.code("good_ending_plus"),
                " key captures this: it is ",
                mb_html.code("null"),
                " for most books (including Job)."
                " For the 4 books/book-parts that have it"
                " (Isaiah, Malachi, Lamentations, Ecclesiastes),"
                " it is an object (see example below).",
            ]
        ),
        author.heading_level_2(["Example \u2014 ", author.hbo("מ:סיום בטוב")]),
        author.para(
            [
                "The ",
                mb_html.code("good_ending_plus"),
                " object's ",
                mb_html.code("wikitext_element"),
                " is a ",
                author.hbo("נוסח"),
                " template wrapping ",
                author.hbo("מ:סיום בטוב"),
                ". Example from Isaiah:",
            ]
        ),
        json_block.json_block_with_notes_raw_html(
            _JSON_GOOD_ENDING,
            {
                9: "Unpointed text of Isa 66:23 (the next-to-last verse of Isaiah)",
                12: 'Documentation note on the good-ending tradition ("2=" param of the enclosing נוסח template)',
            },
        ),
    ]
