# Initially generated by GitHub Copilot.
"""Body content for mpplain.html."""

from mb_misc import mb_html
from author_util import author
from author_util import json_block
from author_util.claim import ClaimCollection
from author import mp_cmn as cmn
from author import mp_cmn_json_snippets as jsnip
from author import mp_cmn_dedicated_rows as dedicated_rows
from author import mp_cmn_top_header_book39 as thb
from author import mp_body_shared as body_shared
from author import mp_table_helpers as tblh

_KQ_AM2_DOC = "mpplain_kq_am2.html"
_KQ_SPECIAL_DOC = "mpplain_kq_special.html"
_KAFUL_DOC = "mpplain_kaful.html"
_MULTIMARK_DOC = "mpplain_multimark.html"
_GOOD_ENDING_TMPL_DOC = "mpplain_good_ending_tmpl.html"
_NUSACH_DOC = "mpplain_nusach.html"
_POETIC_SPACING_DOC = "mpplus_poetic_spacing.html"

_JSON_INDEX_0 = jsnip.read_text("mpplain", "index_0.json")
_JSON_EP_EXAMPLE = jsnip.read_text("mpplain", "ep_example.json")
_JSON_STMPL = jsnip.read_text("mpplain", "stmpl.json")
_JSON_TMPL = jsnip.read_text("mpplain", "tmpl_tree.json")
_JSON_TMPL_NESTED = jsnip.read_text("mpplain", "tmpl_tree_nested.json")
_JSON_CUSTOM_TAG = jsnip.read_text("mpplain", "custom_tag_pair.json")

_CLAIM_ID_BOOK39_SKEL_COMMON = "mp.plain.docs.book39-skeleton.common"
_CLAIM_ID_EXAMPLE_INDEX_0 = "mp.plain.example.verse-label-template-object"
_CLAIM_ID_EXAMPLE_STMPL = "mp.plain.example.stmpl-format"
_CLAIM_ID_EXAMPLE_TMPL_TREE = "mp.plain.example.tmpl-tree"
_CLAIM_ID_EXAMPLE_TMPL_TREE_NESTED = "mp.plain.example.tmpl-tree-nested"
_CLAIM_ID_TMPL_TREE_SHAPE = "mp.plain.template-node.recursive-shape"
_CLAIM_ID_CUSTOM_TAG_KEYS_VALUES = "mp.plain.docs.custom-tag.keys-and-values"

_PLAIN_COMMON_TEMPLATES = [
    "מ:עלייה",
    "כו״ק",
    "קו״כ",
    "מ:קו״כ-אם-2",
    "כתיב ולא קרי",
    "קרי ולא כתיב",
    "מ:כו״ק מיוחד",
    "מ:אות-ג",
    "מ:אות-ק",
    "מ:אות תלויה",
    "מ:נו״ן הפוכה",
    "מ:לגרמיה-2",
    "מ:פסק",
    "מ:מקף אפור",
    "מ:דחי",
    "מ:צינור",
    "גלגל-2",
    "ירח בן יומו-2",
    "מ:קמץ",
    "מ:טעם",
    "מ:כפול",
    "שני טעמים באות אחת קמץ-תחתון-פתח-עליון",
    "מ:ירושלם",
    "מ:ירושלמה",
    "ר1",
    "ר2",
    "ר3",
    "ר4",
    "ר0",
    "מ:ספר חדש",
    "מ:רווח בתרי עשר",
    "מ:רווח בתרי עשר בפסוק הראשון",
    "מ:רווח לספר בתהלים",
    "מ:רווח לספר בתהלים בפסוק הראשון",
    "מ:אין פרשה בתחילת פרק",
    "מ:אין פרשה בתחילת פרק בספרי אמ״ת",
    "מ:אין רווח של פרשה בתחילת פרשת השבוע",
    "פרשה-מרכז",
    "מ:הערה",
    "מ:קישור בהערה",
    "מ:קישור פנימי בהערה",
    "פפ",
    "סס",
    "מ:אות מנוקדת",
    "מ:סיום בטוב",
    "מ:טעם ומתג באות אחת",
    "מ:גרש ותלישא גדולה",
    "מ:גרשיים ותלישא גדולה",
    "ססס",
    "פפפ",
    "רווח בסוף שורה",
    "מ:ששש",
    "מ:כל קמץ קטן מרכא",
    "נוסח",
    "מודגש",
    "ש",
]

_PLAIN_ACCENT_TEMPLATES = [
    "מ:לגרמיה-2",
    "מ:פסק",
    "מ:מקף אפור",
]

_CHOICE_TEMPLATES = [
    "מ:דחי",
    "מ:צינור",
    "מ:קמץ",
    "מ:כפול",
]

_find_template_row = body_shared.find_template_row
_emit_claim_payload = body_shared.emit_claim_payload


def _json_top_level_skel(*, claims: ClaimCollection):
    return _emit_claim_payload(
        claims,
        "mp.plain.example.top-level-skel",
        thb.JSON_TOP_LEVEL_SKEL,
        kind="struct",
        subject="mp:plain",
        data={"top_level_keys": ["header", "book39s"]},
    )


def _json_header(*, claims: ClaimCollection):
    return _emit_claim_payload(
        claims,
        "mp.plain.example.header-job",
        thb.JSON_HEADER,
        kind="example",
        subject="mp:plain",
        data={
            "book24_name": "ספר איוב",
            "sub_book_names": [],
            "chapter_counts": [{"sub_book_name": None, "chapter_count": 42}],
        },
    )


def _json_header_composite(*, claims: ClaimCollection):
    return _emit_claim_payload(
        claims,
        "mp.plain.example.header-samuel",
        thb.JSON_HEADER_COMPOSITE,
        kind="example",
        subject="mp:plain",
    )


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


def s_intro():
    return [
        author.para(
            "The $MAM-parsed-plain JSON files are formed by parsing the Wikitext"
            " in the $MAM Google Sheet with minimal post-processing."
            #
            # Normally we avoid mentioning "plus" in "plain" and vice versa,
            # but this is an intentional exception to the rule.
            " Use plain when you want a format that stays close to the"
            " $MAM Google Sheet."
            " Use plus when you want conveniences"
            " intended to simplify most application code."
            #
            " This document covers:"
        ),
        author.unordered_list(
            [
                "File naming",
                "Structure of the top level and its header",
                "Structure of a book39, chapter, and verse",
                "Template and custom-tag objects",
                "Selected templates",
                "Pseudo-verses",
            ]
        ),
    ]


def s_top_level(*, claims: ClaimCollection):
    return body_shared.build_top_level_section(
        claims=claims,
        subject="mp:plain",
        header_claim_id="mp.plain.header.fields",
        top_level_skel_fn=_json_top_level_skel,
        header_fn=_json_header,
        header_composite_fn=_json_header_composite,
    )


def s_book39(*, claims: ClaimCollection):
    _book39_rows = _emit_claim_payload(
        claims,
        "mp.plain.book39.fields",
        thb.book39_rows_common(),
        kind="struct",
        subject="mp:plain",
        data={"book39_keys": thb.BOOK39_KEYS_COMMON},
    )
    return [
        author.heading_level_2("Book39 structure"),
        json_block.json_block_raw_html(
            _emit_claim_payload(
                claims,
                _CLAIM_ID_BOOK39_SKEL_COMMON,
                thb.JSON_BOOK39_SKEL_COMMON,
                kind="struct",
                subject="mp:plain",
                data={"book39_keys": thb.BOOK39_KEYS_COMMON},
            )
        ),
        tblh.key_type_desc_table(_book39_rows),
    ]


def s_chapter(*, claims: ClaimCollection):
    _chapter_rows = _emit_claim_payload(
        claims,
        "mp.plain.chapter.pseudo-verse-keys",
        [
            [
                mb_html.code('"0"'),
                "Pre-chapter",
                "Wiki navigation templates, page setup",
            ],
            ["Hebrew numerals", "Normal verses", "Actual verse data"],
            [
                author.hbo('"תתת"'),
                "Post-chapter",
                "Wiki footer templates, end-of-chapter markup",
            ],
        ],
        kind="struct",
        subject="mp:plain",
        data={"pseudo_verse_keys": ["0", "תתת"]},
    )
    return [
        author.heading_level_2("Chapter structure"),
        author.para(
            [
                "The ",
                mb_html.code("chapters"),
                " dict is keyed as follows:",
            ]
        ),
        tblh.key_category_purpose_table(_chapter_rows),
        author.para(
            [
                "The keys for normal verses are Hebrew numerals conforming to the system"
                " that uses טו and טז for 15 and 16,"
                " avoiding the divine-name letter-pairs."
            ]
        ),
    ]


def s_verse(*, claims: ClaimCollection):
    return [
        *body_shared.verse_structure_prelude(
            claims=claims,
            claim_id="mp.plain.verse.is-3-tuple",
            subject="mp:plain",
            d_col_item="D — Verse label: usually just book, chapter, and verse",
            preface_text="(This section documents both normal verses and pseudo-verses.)",
        ),
        *body_shared.verse_c_column_block(
            claims=claims,
            claim_id="mp.plain.verse.c-col.top5-items",
            subject="mp:plain",
            top_items_data_key="top5",
            top_items=["__", "//", "ר4", "פפ", "סס"],
            include_double_slash=True,
        ),
        *body_shared.verse_d_column_block(
            claims=claims,
            claim_id="mp.plain.verse.d-col.semantics",
            subject="mp:plain",
            semantics_payload=[
                "Column D is an empty array for pseudo-verses."
                " For normal verses, it is an array with exactly"
                " one element: either a ",
                author.hbo("מ:פסוק"),
                " template or ",
                author.hbo("מ:פסוק"),
                " wrapped in a ",
                author.hbo("נוסח"),
                " template." " For example, here is the D column value for Job 1:2:",
            ],
            semantics_data={
                "label_template": "מ:פסוק",
                "nusach_wrapper": "נוסח",
                "always_present": True,
                "allowed_named_params": ["סדר", "עלייה"],
            },
            example_json=_emit_claim_payload(
                claims,
                _CLAIM_ID_EXAMPLE_INDEX_0,
                _JSON_INDEX_0,
                kind="example",
                subject="mp:plain",
            ),
        ),
        author.heading_level_3("E column (index 2): Verse proper"),
        author.para(
            _emit_claim_payload(
                claims,
                "mp.plain.verse.e-col.semantics",
                "Column E is an array mixing strings and templates."
                " Example (Job 1:1):",
                kind="struct",
                subject="mp:plain",
                data={"element_types": ["string", "stmpl", "tmpl", "custom_tag"]},
            )
        ),
        json_block.json_block_raw_html(_JSON_EP_EXAMPLE),
    ]


def s_template_format(*, claims: ClaimCollection):
    return [
        author.heading_level_2("Template format"),
        author.para("Three kinds of template objects are used:"),
        author.heading_level_3("1. Stringified template (stmpl)"),
        author.para(
            [
                "Many templates are simple enough to appear as a pipe-delimited string:",
            ]
        ),
        json_block.json_block_raw_html(
            _emit_claim_payload(
                claims,
                _CLAIM_ID_EXAMPLE_STMPL,
                _JSON_STMPL,
                kind="example",
                subject="mp:plain",
            )
        ),
        author.para(
            [
                "This represents the Wikitext ",
                mb_html.code("{{מ:פסוק|איוב|א|ב}}"),
                "." " The first segment (before ",
                mb_html.code("|"),
                ") is the template name; remaining segments are positional arguments.",
            ]
        ),
        author.heading_level_3("2. Parsed template tree (tmpl)"),
        author.para(
            _emit_claim_payload(
                claims,
                _CLAIM_ID_TMPL_TREE_SHAPE,
                "A parsed template tree’s segments contain strings and nested templates.",
                kind="struct",
                subject="mp:plain",
                data={
                    "key": "tmpl",
                    "allowed_node_types": ["string", "stmpl", "tmpl"],
                },
            )
        ),
        author.para(
            "A parsed template tree is used in cases where a stringified template would be inappropriate,"
            " such as when the template is long and/or contains nested templates."
        ),
        author.para("Example — a long template with string parameters only:"),
        json_block.json_block_raw_html(
            _emit_claim_payload(
                claims,
                _CLAIM_ID_EXAMPLE_TMPL_TREE,
                _JSON_TMPL,
                kind="example",
                subject="mp:plain",
            )
        ),
        author.para("Example — a template nested inside another template:"),
        json_block.json_block_raw_html(
            _emit_claim_payload(
                claims,
                _CLAIM_ID_EXAMPLE_TMPL_TREE_NESTED,
                _JSON_TMPL_NESTED,
                kind="example",
                subject="mp:plain",
            )
        ),
        author.heading_level_3("3. Custom XML tag (custom_tag)"),
        author.para(
            _emit_claim_payload(
                claims,
                _CLAIM_ID_CUSTOM_TAG_KEYS_VALUES,
                "Custom-tag objects use the custom_tag key and only the documented tag values.",
                kind="format",
                subject="mp:plain",
                data={
                    "key": "custom_tag",
                    "allowed_values": ["noinclude", "/noinclude", "references/"],
                    "allowed_prefixes": ["קטע התחלה=", "קטע סוף="],
                },
            )
        ),
        json_block.json_block_raw_html(_JSON_CUSTOM_TAG),
    ]


def s_common_templates(*, claims: ClaimCollection):
    structural_rows, _ = body_shared.emit_common_templates_claim_prelude(claims=claims)
    kq_rows = body_shared.build_kq_rows(
        claims=claims,
        kq_am2_doc=_KQ_AM2_DOC,
        kq_special_doc=_KQ_SPECIAL_DOC,
    )
    json_kq = cmn.emit_claim_by_id(claims=claims, claim_id="mp.plain.example.kq")
    special_letter_rows = cmn.emit_claim_by_id(
        claims=claims,
        claim_id="mp.both.templates.special-letters.set",
    )
    cmn.emit_claim_by_id(
        claims=claims,
        claim_id="mp.both.templates.accents.set",
    )
    cmn.emit_claim_by_id(
        claims=claims,
        claim_id="mp.both.templates.poetic.set",
    )

    plain_accent_rows = cmn.accent_rows_for_templates(_PLAIN_ACCENT_TEMPLATES)
    plain_choice_rows = dedicated_rows.with_kaful_dedicated_page_link(
        cmn.accent_rows_for_templates(_CHOICE_TEMPLATES),
        doc_name=_KAFUL_DOC,
    )
    poetic_spacing_row = body_shared.poetic_spacing_row(doc_name=_POETIC_SPACING_DOC)
    whitespace_extra_rows = cmn.other_rows_for_templates(["רווח בסוף שורה"])
    whitespace_parashah_rows = [
        _find_template_row(structural_rows, "מ:ספר חדש"),
        _find_template_row(structural_rows, "מ:רווח בתרי עשר"),
        _find_template_row(structural_rows, "מ:רווח בתרי עשר בפסוק הראשון"),
        _find_template_row(structural_rows, "מ:רווח לספר בתהלים"),
        _find_template_row(structural_rows, "מ:רווח לספר בתהלים בפסוק הראשון"),
        [author.hbo("סס2"), "Narrow closed $parashah"],
        [author.hbo("פסקא באמצע פסוק"), "$parashah division within a verse"],
    ]
    lack_of_whitespace_rows = [
        _find_template_row(structural_rows, "מ:אין פרשה בתחילת פרק"),
        _find_template_row(structural_rows, "מ:אין פרשה בתחילת פרק בספרי אמ״ת"),
        _find_template_row(structural_rows, "מ:אין רווח של פרשה בתחילת פרשת השבוע"),
    ]
    plain_note_links_rows = [
        [
            author.hbo("מ:קישור בהערה"),
            "Hyperlink inside note content (within arg 2 of מ:הערה).",
        ],
        [
            author.hbo("מ:קישור פנימי בהערה"),
            "Same-page link inside note content (within arg 2 of מ:הערה).",
        ],
    ]
    other_templates_rows = (
        [cmn.good_ending_row(good_ending_doc=_GOOD_ENDING_TMPL_DOC)]
        + cmn.poetic_rows_for_templates(["פרשה-מרכז"])
        + plain_note_links_rows
        + [
            *cmn.accent_rows_for_templates(["גלגל-2", "ירח בן יומו-2"]),
            *cmn.other_rows_for_templates(["מ:אות מנוקדת"]),
        ]
    )

    _emit_claim_payload(
        claims,
        "mp.plain.docs.common-templates.templates-in-plain-survey",
        None,
        kind="enum",
        subject="mp:plain",
        data={"templates": _PLAIN_COMMON_TEMPLATES},
    )
    return [
        *body_shared.selected_templates_intro_block(),
        *body_shared.verse_label_templates_block(),
        *body_shared.ketiv_qere_block(kq_rows=kq_rows, json_kq=json_kq),
        author.heading_level_3("Special letter templates"),
        tblh.tmpl_purp_table(special_letter_rows),
        author.heading_level_3("Punctuation templates"),
        tblh.tmpl_purp_table(plain_accent_rows),
        author.heading_level_3("Multimark templates"),
        author.para(
            [
                "See ",
                author.anchor_h("their dedicated page", _MULTIMARK_DOC),
                ".",
            ]
        ),
        author.heading_level_3("Choice templates"),
        body_shared.choice_templates_intro_para(),
        tblh.tmpl_purp_table(plain_choice_rows),
        author.heading_level_3("Whitespace templates"),
        tblh.tmpl_purp_table(
            cmn.whitespace_rows_shared()
            + [poetic_spacing_row]
            + whitespace_extra_rows
            + whitespace_parashah_rows
        ),
        author.para(
            "Many editions will choose to skip poetic formatting by treating"
            " ר0–ר4 as simple word spaces."
        ),
        author.heading_level_3("Lack-of-whitespace templates"),
        tblh.tmpl_purp_table(lack_of_whitespace_rows),
        author.heading_level_3("Note template"),
        tblh.tmpl_purp_table([cmn.NOTE_ROW_PLAIN]),
        author.heading_level_3("Documentation templates"),
        tblh.tmpl_purp_table(cmn.other_rows_shared_core(nusach_doc=_NUSACH_DOC)),
        author.heading_level_3("Other templates"),
        tblh.tmpl_purp_table(other_templates_rows),
    ]


def s_pseudo_verses():
    return [
        author.heading_level_2("Pseudo-verses (0 and תתת)"),
        author.para(
            [
                "The ",
                mb_html.code('"0"'),
                " and ",
                author.hbo('"תתת"'),
                " keys are pseudo-verses that contain"
                " Wiki-specific navigation and formatting markup, not biblical content."
                " They can generally be skipped when extracting verse content.",
            ]
        ),
        author.unordered_list(
            [
                [
                    mb_html.code('"0"'),
                    ": Contains ",
                    mb_html.code("noinclude"),
                    " tags, navigation templates, margin settings.",
                ],
                [
                    author.hbo('"תתת"'),
                    ": Contains end-of-chapter markers, unnumbered-verse section.",
                ],
            ]
        ),
    ]
