# Initially generated by GitHub Copilot.
"""
HTML document: Special ketiv/qere — מ:כו״ק מיוחד.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplus_kq_special.html.
"""

from mb_misc import mb_html
from author_util import author
from author_util import json_block
from author import mp_cmn as cmn

_FNAME = "mpplus_kq_special.html"
_TITLE = "Special ketiv/qere"

_PLUS_DOC = "mpplus.html"

_JSON_KQ_SPECIAL = """\
{
  "tmpl_name": "מ:כו״ק מיוחד",
  "tmpl_params": {
    "1": "מנהסערה",
    "2": ["מִ֥ן", {"tmpl_name": "מ:פסק"}, "הַסְּעָרָ֗ה"],
    "סוג": "כו״ק כתיב מילה חדה וקרי תרתין מילין"
  }
}"""


def gen_html_file(tdm_ch):
    """Generate reading_mam_parsed_plus_kq_special.html in the given output directory."""
    cbody = _build_body()
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def _build_body():
    back_link = author.anchor_h("Reading $MAM-parsed-plus", _PLUS_DOC)
    return [
        author.heading_level_1(
            ["Special $ketiv_qere template — ", author.hbo("מ:כו״ק מיוחד")]
        ),
        author.para(["← Back to ", back_link]),
        author.para(
            [
                "Nine special $ketiv_qere types are encoded in the required named parameter ",
                author.hbo("סוג="),
                ".",
            ]
        ),
        author.para(
            [
                "The sub-typing serves two purposes: it pre-categorizes these rare k/q pairs so"
                " that consuming applications do not need to re-derive the classification from"
                " the template parameters alone, and it exposes enough granularity for"
                " applications that wish to present different subtypes differently."
                " For example, the Wikisource edition of $MAM groups the nine subtypes into four"
                " display families based on whether the pair is flanked by $maqaf marks, and"
                " (for pairs not so flanked) whether the $qere precedes or follows the $ketiv"
                " in the text.",
            ]
        ),
        author.para(
            [
                "The following ",
                author.hbo("סוג="),
                " values are used with the ",
                author.hbo("מ:כו״ק מיוחד"),
                " template:",
            ]
        ),
        author.std_table(cmn.KQ_SPECIAL_ROWS, arg_to_troh=["Type", "Meaning"]),
        author.para("Example (Job 38:1):"),
        json_block.json_block_raw_html(_JSON_KQ_SPECIAL),
    ]
