# Initially generated by GitHub Copilot.
"""Body content for mpplus.html — plus-only sections."""

from mb_misc import mb_html
from author_util import author
from author_util import json_block
from author_util.claim import claim
from author import mp_cmn as cmn

_PLUS_DOC = "mpplus.html"
_CALL_GRAPHS = "https://bdenckla.github.io/MAM-parsed/plus-template-call-graphs.html"

_AOT_DOC = "mpplus_aot.html"
_KQ_SPECIAL_DOC = "mpplus_kq_special.html"
_HAARAH_2_DOC = "mpplus_haarah_2.html"
_KAFUL_DOC = "mpplus_kaful.html"
_GOOD_ENDING_DOC = "mpplus_good_ending.html"

_PLUS_COMMON_TEMPLATES = [
    "כו״ק",
    "קו״כ",
    "מ:קו״כ-אם-2",
    "כתיב ולא קרי",
    "קרי ולא כתיב",
    "מ:כו״ק מיוחד",
    "מ:אות-ג",
    "מ:אות-ק",
    "מ:אות תלויה",
    "מ:נו״ן הפוכה",
    "מ:אות-מיוחדת-במילה",
    "מ:לגרמיה-2",
    "מ:פסק",
    "מ:מקף אפור",
    "מ:דחי",
    "מ:צינור",
    "מ:קמץ",
    "מ:כפול",
    "ר1",
    "ר2",
    "ר3",
    "ר4",
    "ר0",
    "מ:הערה",
    "מ:הערה-2",
    "פפ",
    "פפפ",
    "סס",
    "ססס",
    "מ:ששש",
    "נוסח",
    "מודגש",
    "ש",
]


# ---------------------------------------------------------------------------
# JSON snippets
# ---------------------------------------------------------------------------

_JSON_TOP_LEVEL_SKEL = claim(
    "mp.plus.example.top-level-skel",
    """\
{
  "header": {},
  "book39s": []
}""",
    kind="struct",
    subject="mp:plus",
    data={"top_level_keys": ["header", "book39s"]},
)

_JSON_HEADER = claim(
    "mp.plus.example.header-job",
    """\
"header": {
  "book24_name": "ספר איוב",
  "sub_book_names": [],
  "chapter_counts": [
    {"sub_book_name": null, "chapter_count": 42}
  ]
}""",
    kind="example",
    subject="mp:plus",
    data={
        "book24_name": "ספר איוב",
        "sub_book_names": [],
        "chapter_counts": [{"sub_book_name": None, "chapter_count": 42}],
    },
)

_JSON_HEADER_COMPOSITE = claim(
    "mp.plus.example.header-samuel",
    """\
"header": {
  "book24_name": "ספר שמואל",
  "sub_book_names": ["שמ\\\"א", "שמ\\\"ב"],
  "chapter_counts": [
      {"sub_book_name": "שמ\\\"א", "chapter_count": 31},
      {"sub_book_name": "שמ\\\"ב", "chapter_count": 24}
  ]
}""",
    kind="example",
    subject="mp:plus",
)

_JSON_BOOK39_SKEL = claim(
    "mp.plus.example.book39-skel",
    """\
{
  "book24_name": "ספר ישעיהו",
  "sub_book_name": null,
  "chapters": {},
  "good_ending_plus": null
}""",
    kind="struct",
    subject="mp:plus",
    data={
        "book39_keys": [
            "book24_name",
            "sub_book_name",
            "chapters",
            "good_ending_plus",
        ]
    },
)

_JSON_D_COL_FIRST = claim(
    "mp.plus.example.d-col-first",
    """\
[
    ...,
    [
      {"tmpl_name": "מ:פסוק",
       "tmpl_params": {"1": "איוב", "2": "א", "3": "א", "סדר": "א"}}
    ],
    ...
]""",
    kind="example",
    subject="mp:plus",
)

_JSON_D_COL_SUBSEQ = claim(
    "mp.plus.example.d-col-empty",
    """\
[
    ...,
    [],
    ...
]""",
    kind="example",
    subject="mp:plus",
)

_JSON_TMPL_FORMAT = claim(
    "mp.plus.template.format-example",
    """\
{
  "tmpl_name": "קו״כ",
  "tmpl_params": {"1": "את", "2": "אַ֠תָּ֠ה"}
}""",
    kind="format",
    subject="mp:plus",
    data={
        "object_keys": ["tmpl_name", "tmpl_params"],
        "tmpl_name": "קו״כ",
        "tmpl_params": {"1": "את", "2": "אַ֠תָּ֠ה"},
    },
)

_JSON_TMPL_PLAIN_COMPARE = claim(
    "mp.plain.template.stmpl-format-example",
    """\
{"stmpl": "קו״כ|את|אַ֠תָּ֠ה"}""",
    kind="format",
    subject="mp:plain",
    data={"stmpl": "קו״כ|את|אַ֠תָּ֠ה"},
)

_JSON_NESTED = claim(
    "mp.plus.example.nested-tmpl",
    """\
{
  "tmpl_name": "נוסח",
  "tmpl_params": {
    "1": {
      "tmpl_name": "כו״ק",
      "tmpl_params": {
        "1": {
          "tmpl_name": "מ:אות-מיוחדת-במילה",
          "tmpl_params": {...},
        },
        "2": "וְג֣וּשׁ"
      }
    },
    "2": "..."
  }
}""",
    kind="example",
    subject="mp:plus",
)


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


_DIFF_ROWS = claim(
    "mp.plus.diff-from-plain",
    [
        [
            "Pseudo-verses “0” and “תתת”",
            "Present",
            "Removed",
        ],
        [
            "Custom XML tags (נוינקלוד etc.)",
            "Present",
            "Removed",
        ],
        ["Wikitext line breaks (“//”)", "Present in C column", "Removed"],
        ["Named params", "not parsed", "parsed and unified with positional"],
        [
            "D column (verse label)",
            ["Every verse has ", author.hbo("מ:פסוק")],
            [
                "Only when ",
                author.hbo("מ:פסוק"),
                " has interesting parameters or is wrapped in ",
                author.hbo("נוסח"),
            ],
        ],
        [mb_html.code("good_ending_plus"), "Not present", "Added (at book39 level)"],
        [
            "Words with special letters",
            "word split/interrupted by inline letter templates",
            [
                "whole word wrapped by ",
                author.hbo("מ:אות-מיוחדת-במילה"),
                "; uninterrupted encoding in args 2–4",
            ],
        ],
        [
            [mb_html.code('{"tmpl": [...]}'), " — parsed template trees"],
            "Present",
            [
                "Removed (replaced by ",
                mb_html.code("tmpl_name"),
                "/",
                mb_html.code("tmpl_params"),
                ")",
            ],
        ],
        [
            [mb_html.code('{"stmpl": "..."}'), " — stringified templates"],
            "Present",
            [
                "Removed (replaced by ",
                mb_html.code("tmpl_name"),
                "/",
                mb_html.code("tmpl_params"),
                ")",
            ],
        ],
        [
            [author.hbo("גלגל-2"), " — galgal accent annotation"],
            "Present",
            "Removed (handled differently in plus)",
        ],
    ],
    kind="enum",
    subject="mp:plus",
)


def s_intro():
    return [
        author.para(
            "The $MAM-parsed-plus JSON files are formed by:"
            " (a) parsing the Wikitext in the $MAM Google Sheet"
            " (b) adding some conveniences and"
            " (c) removing some inconveniences."
            " Of course, what is considered an inconvenience and what is considered a convenience"
            " can only be determined relative to a particular application."
            " Nonetheless, we believe that for most applications,"
            " the plus format is more convenient to work with than the plain format."
            " This document covers:"
        ),
        author.unordered_list(
            [
                "File naming",
                "Structure of the top-level and its header",
                "Structure of a book39, chapter, and verse",
                "Template format",
                "Selected templates presented in detail",
                "Common templates",
                "Differences from plain format",
            ]
        ),
    ]


def s_plain_differences():
    return [
        author.heading_level_2("Differences from plain format"),
        author.std_table(_DIFF_ROWS, arg_to_troh=["Feature", "Plain", "Plus"]),
        author.para(
            [
                "Template names use Hebrew gershayim ",
                mb_html.code("״"),
                " (for example ",
                author.hbo("כו״ק"),
                "), not ASCII double quote ",
                mb_html.code('"'),
                ".",
            ]
        ),
        author.para(
            [
                "Example of the stringified template format ",
                mb_html.code('{"stmpl": "..."}'),
                " (present in plain, replaced in plus):",
            ]
        ),
        json_block.json_block_raw_html(_JSON_TMPL_PLAIN_COMPARE),
    ]


def s_top_level():
    _header_rows = claim(
        "mp.plus.header.fields",
        [
            [
                mb_html.code("book24_name"),
                "string",
                "The name of this file’s book24.",
            ],
            [
                mb_html.code("sub_book_names"),
                "array",
                [
                    "Array of sub-book names for this book24."
                    " (Empty if this book24 has no sub-books.)",
                ],
            ],
            [
                mb_html.code("chapter_counts"),
                "array",
                [
                    "One object per book39, each with ",
                    mb_html.code("sub_book_name"),
                    " and ",
                    mb_html.code("chapter_count"),
                    ".",
                    " (The ",
                    mb_html.code("sub_book_name"),
                    " will be null for a book39 that is not a sub-book, i.e. a book39 that is also a book24.)",
                ],
            ],
        ],
        kind="struct",
        subject="mp:plus",
        data={"header_keys": ["book24_name", "sub_book_names", "chapter_counts"]},
    )
    return [
        author.heading_level_2("Top-level structure"),
        json_block.json_block_raw_html(_JSON_TOP_LEVEL_SKEL),
        author.heading_level_2("Header"),
        author.std_table(_header_rows, arg_to_troh=["Key", "Type", "Description"]),
        author.para("Here’s the header for Job, a book24 has no sub-books:"),
        json_block.json_block_raw_html(_JSON_HEADER),
        author.para("Here’s the header for Samuel, a book24 that has sub-books:"),
        json_block.json_block_raw_html(_JSON_HEADER_COMPOSITE),
    ]


def s_book39():
    _book39_rows = claim(
        "mp.plus.book39.fields",
        [
            [
                mb_html.code("book24_name"),
                "string",
                [
                    "For a book39 that is not a sub-book, this is its name.",
                    " For a book39 that is a sub-book, this is the name of the book24 to which this sub-book belongs.",
                ],
            ],
            [
                mb_html.code("sub_book_name"),
                "string | null",
                [
                    "For a book39 that is not a sub-book, this is null.",
                    " For a book39 that is a sub-book, this is its name.",
                ],
            ],
            [
                mb_html.code("chapters"),
                "object",
                "Object keyed by chapter numbers; values are chapter objects.",
            ],
            [
                mb_html.code("good_ending_plus"),
                "object | null",
                [
                    'Non-null only for the 4 book39s with "good endings." See ',
                    author.anchor_h(
                        "its dedicated page",
                        _GOOD_ENDING_DOC,
                    ),
                    ".",
                ],
            ],
        ],
        kind="struct",
        subject="mp:plus",
        data={
            "book39_keys": [
                "book24_name",
                "sub_book_name",
                "chapters",
                "good_ending_plus",
            ],
            "good_ending_plus_nonnull_count": 4,
        },
    )
    return [
        author.heading_level_2("Book39 structure"),
        json_block.json_block_raw_html(_JSON_BOOK39_SKEL),
        author.std_table(_book39_rows, arg_to_troh=["Key", "Type", "Description"]),
    ]


def s_chapter_verse():
    tmpl_rows = claim(
        "mp.plus.template.object-fields",
        [
            [mb_html.code("tmpl_name"), "string", "Template name"],
            [
                mb_html.code("tmpl_params"),
                "object",
                ["Parameters — present only if needed"],
            ],
        ],
        kind="struct",
        subject="mp:plus",
        data={"required_keys": ["tmpl_name"], "optional_keys": ["tmpl_params"]},
    )
    return [
        author.heading_level_2("Chapter structure"),
        author.para(
            claim(
                "mp.plus.chapter.keyed-by-verse-num",
                [
                    "An object keyed by verse numbers."
                    " For example, a chapter with 22 verses has exactly 22 keys, ",
                    mb_html.code('"1"'),
                    " through ",
                    mb_html.code('"22"'),
                    ".",
                ],
                kind="struct",
                subject="mp:plus",
                data={"key_format": "decimal-string-1-indexed-contiguous"},
            )
        ),
        author.heading_level_2("Verse structure"),
        author.para(
            claim(
                "mp.plus.verse.is-3-tuple",
                [
                    "A 3-element array [C, D, E], with column details described below.",
                ],
                kind="struct",
                subject="mp:plus",
                data={"shape": ["sep", "label", "text"], "length": 3},
            )
        ),
        author.heading_level_3("C column (index 0): Verse separator"),
        author.para(
            claim(
                "mp.plus.verse.c-col.semantics",
                [
                    "The C column usually contains what separates this verse "
                    "from the previous verse. This is usually a space, "
                    "represented as ",
                    mb_html.code('["__"]'),
                    ", but is sometimes something else, such as a פפ $parashah-break "
                    "template.",
                ],
                kind="struct",
                subject="mp:plus",
                data={"common_value": ["__"]},
            )
        ),
        author.heading_level_3("D column (index 1): Verse label"),
        author.para(
            claim(
                "mp.plus.verse.d-col.semantics",
                [
                    "This is an array that contains a ",
                    author.hbo("מ:פסוק"),
                    " template call when it has something interesting to say—typically when it carries ",
                    "extra metadata such as the ",
                    mb_html.code("סדר"),
                    " or ",
                    mb_html.code("עלייה"),
                    " parameter. Otherwise, the array is empty.",
                ],
                kind="struct",
                subject="mp:plus",
                data={
                    "label_template": "מ:פסוק",
                    "empty_when": "no interesting metadata",
                },
            )
        ),
        author.para(
            [
                "The ",
                mb_html.code("עלייה"),
                " value itself is a ",
                author.hbo("מ:עלייה"),
                " template; see ",
                author.anchor_h(
                    "notes on $aliyot",
                    "https://bdenckla.github.io/MAM-with-doc/misc/notes_on_aliyot.html",
                ),
                ".",
            ]
        ),
        author.para(["Job 1:1:"]),
        json_block.json_block_raw_html(_JSON_D_COL_FIRST),
        author.heading_level_3("E column (index 2): Verse text"),
        author.para(
            claim(
                "mp.plus.verse.e-col.semantics",
                [
                    "An array containing a mix of strings and template objects.",
                ],
                kind="struct",
                subject="mp:plus",
                data={"element_types": ["string", "template_object"]},
            )
        ),
        author.heading_level_2("Template format"),
        author.para("Templates are represented like this:"),
        json_block.json_block_raw_html(_JSON_TMPL_FORMAT),
        author.std_table(tmpl_rows, arg_to_troh=["Key", "Type", "Description"]),
        author.heading_level_3([mb_html.code("tmpl_params"), " keys"]),
        author.para(
            claim(
                "mp.plus.template.tmpl-params-keys",
                [
                    "Numeric string keys ",
                    mb_html.code('"1"'),
                    ", ",
                    mb_html.code('"2"'),
                    ", … correspond to positional arguments,"
                    " Non-numeric keys (e.g. ",
                    mb_html.code('"ד"'),
                    ", ",
                    mb_html.code('"ס"'),
                    ", ",
                    mb_html.code('"סדר"'),
                    ") represent named parameters like ",
                    mb_html.code("ד=..."),
                    " in the Wikitext.",
                ],
                kind="format",
                subject="mp:plus",
                data={
                    "numeric_keys": "positional args",
                    "non_numeric_keys": "named params",
                },
            )
        ),
        author.para(
            claim(
                "mp.plus.template.tmpl-params-omitted-when-empty",
                [
                    "The ",
                    mb_html.code("tmpl_params"),
                    " object is absent when the template has no parameters (e.g. ",
                    author.hbo("פפ"),
                    ", ",
                    author.hbo("סס"),
                    ", ",
                    author.hbo("מ:פסק"),
                    ").",
                ],
                kind="format",
                subject="mp:plus",
                data={"examples_no_params": ["פפ", "סס", "מ:פסק"]},
            )
        ),
        author.heading_level_3("Template parameter values can be complex"),
        author.para(
            [
                "Parameter values can themselves be strings, nested template objects,"
                " or arrays of mixed strings and template objects."
                " For a visual overview of which templates nest inside which, see the ",
                author.anchor_h("plus template call graphs", _CALL_GRAPHS),
                ".",
            ]
        ),
        author.para(
            "Example — a word with a special letter inside a $ketiv_qere inside a נוסח:"
        ),
        json_block.json_block_raw_html(_JSON_NESTED),
    ]


def s_plus_only_templates():
    return [
        author.heading_level_2("Selected templates"),
        author.para("Each of the following templates has its own dedicated page:"),
        author.unordered_list(
            [
                author.anchor_h(
                    [
                        "Special letter marking — ",
                        author.hbo("מ:אות-מיוחדת-במילה"),
                    ],
                    _AOT_DOC,
                ),
                author.anchor_h(
                    [
                        "Special $ketiv_qere template — ",
                        author.hbo("מ:כו״ק מיוחד"),
                    ],
                    _KQ_SPECIAL_DOC,
                ),
                author.anchor_h(
                    [
                        "Targeted scroll-difference note — ",
                        author.hbo("מ:הערה-2"),
                    ],
                    _HAARAH_2_DOC,
                ),
                author.anchor_h(
                    [
                        "Dual-trope text — ",
                        author.hbo("מ:כפול"),
                    ],
                    _KAFUL_DOC,
                ),
            ]
        ),
    ]


def s_common_templates():
    claim(
        "mp.plus.docs.common-templates.templates-in-plus-survey",
        "Templates listed in mpplus common-template tables are present in plus survey.",
        kind="enum",
        subject="mp:plus",
        data={"templates": _PLUS_COMMON_TEMPLATES},
    )
    sheets_link = author.anchor_h("Templates tab", cmn.SHEETS_TMPL)
    sheets_data_link = author.anchor_h("$MAM Google Sheet", cmn.SHEETS_DATA)
    return [
        author.heading_level_2("Common templates in the E (verse text) column"),
        author.para(
            [
                "For English and Hebrew descriptions of most templates, see the ",
                sheets_link,
                " of the ",
                sheets_data_link,
                ".",
            ]
        ),
        author.heading_level_3("Documentation template (נוסח)"),
        author.para(
            [
                "The first parameter is the “target” — what is being documented."
                " The second parameter contains the documentation"
                " (anomalous forms, variant readings, uncertain readings, etc.):",
            ]
        ),
        json_block.json_block_raw_html(cmn.JSON_NUSACH_PLUS),
        author.heading_level_3("$Ketiv_qere templates"),
        author.std_table(cmn.KQ_ROWS, arg_to_troh=["Template", "Purpose"]),
        author.para(
            [
                "Current values observed for optional ",
                author.hbo("סוג="),
                " in ",
                author.hbo("מ:קו״כ-אם-2"),
                ":",
            ]
        ),
        author.unordered_list(cmn.KQ_AM2_SUG_LIST),
        author.para("Example of standard $ketiv_qere:"),
        json_block.json_block_raw_html(cmn.JSON_KQ_PLUS),
        author.heading_level_3("Special letter templates"),
        author.std_table(
            cmn.SPECIAL_LETTER_ROWS
            + [
                [
                    author.hbo("מ:אות-מיוחדת-במילה"),
                    [
                        "Marks a whole word containing a special letter."
                        " (By “special” we mean large, small, or suspended.)"
                        " See ",
                        author.anchor_h(
                            "its dedicated page",
                            _AOT_DOC,
                        ),
                        ".",
                    ],
                ]
            ],
            arg_to_troh=["Template", "Purpose"],
        ),
        author.heading_level_3("Accent and cantillation templates"),
        author.std_table(
            [cmn.ACCENT_ROWS[i] for i in (0, 1, 2, 3, 4, 8, 10)],
            arg_to_troh=["Template", "Purpose"],
        ),
        author.heading_level_3("Poetic form templates (ספרי אמת)"),
        author.std_table(
            [row for row in cmn.POETIC_ROWS if row[0] != author.hbo("פרשה-מרכז")],
            arg_to_troh=["Template", "Purpose"],
        ),
        author.para(
            "Many editions will choose to skip poetic formatting by treating"
            " ר0–ר4 as simple word spaces."
        ),
        author.heading_level_3("Note template"),
        author.std_table(
            [cmn.NOTE_ROW],
            arg_to_troh=["Template", "Purpose"],
        ),
        author.heading_level_3("Other templates"),
        author.std_table(
            [
                [
                    [
                        author.hbo("פפ"),
                        " / ",
                        author.hbo("פפפ"),
                        " / ",
                        author.hbo("סס"),
                        " / ",
                        author.hbo("ססס"),
                    ],
                    "Parashah petuḥah / setumah variants.",
                ],
                [
                    author.hbo("מ:ששש"),
                    [
                        "Shirah space. Like ",
                        author.hbo("ססס"),
                        ", but for the 8 shirah (song) sections; not an official setumah break.",
                    ],
                ],
                cmn.OTHER_ROWS[11],
                cmn.OTHER_ROWS[12],
                cmn.OTHER_ROWS[13],
            ],
            arg_to_troh=["Template", "Purpose"],
        ),
    ]
