# Initially generated by GitHub Copilot.
"""
HTML document: reading MAM-parsed plus JSON format.

To regenerate the output HTML, run from the repo root::

    .venv\\Scripts\\python.exe py\\main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/reading_mam_parsed_plus.html.
Body content lives in reading_mam_parsed_plus_body.py.
"""

from mb_misc import mb_html
from author_util import author
from author import reading_mam_parsed_cmn as cmn
from author import reading_mam_parsed_plus_body as body

_FNAME = "reading_mam_parsed_plus.html"
_TITLE = "Reading MAM-parsed plus JSON"


def gen_html_file(tdm_ch):
    """Generate reading_mam_parsed_plus.html in the given output directory."""
    cbody = _build_body()
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def _build_body():
    return [
        mb_html.heading_level_1(_TITLE),
        *cmn.s_file_naming(),
        *body.s_intro(),
        *body.s_top_level(),
        *body.s_book39(),
        *body.s_chapter_verse(),
        *body.s_plus_only_templates(),
        *body.s_common_templates(),
        *body.s_not_in_plus(),
    ]
