# Initially generated by GitHub Copilot.
"""HTML document: reading MAM-parsed plain JSON format."""

from mb_misc import mb_html
from author_util import author
from author_util import json_block

_FNAME = "reading_mam_parsed_plain.html"
_TITLE = "Reading MAM-parsed plain JSON"

_SHEETS_TMPL = "https://docs.google.com/spreadsheets/d/1mkQyj6by1AtBUabpbaxaZq9Z2X3pX8ZpwG91ZCSOEYs/edit?gid=1670945398#gid=1670945398"
_SHEETS_DATA = "https://docs.google.com/spreadsheets/d/1mkQyj6by1AtBUabpbaxaZq9Z2X3pX8ZpwG91ZCSOEYs/edit#gid=920165745"
_PLUS_DOC = "reading_mam_parsed_plus.html"

_JSON_TOP_LEVEL = """\
{
  "header": {
    "book24_names": ["ספר איוב"],
    "sub_book_names": {},
    "chapter_counts": [
      {
        "book24_name": "ספר איוב",
        "sub_book_name": null,
        "chapter_count": 42
      }
    ]
  },
  "book39s": []
}"""

_JSON_COMPOSITE = """\
{
  "header": {
    "book24_names": ["ספר שמואל"],
    "sub_book_names": {"ספר שמואל": ["שמ\\"א", "שמ\\"ב"]},
    "chapter_counts": [
      {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"א", "chapter_count": 31},
      {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"ב", "chapter_count": 24}
    ]
  },
  "book39s": [
    {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"א", "chapters": {}},
    {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"ב", "chapters": {}}
  ]
}"""

_JSON_BOOK39 = """\
{
  "book24_name": "ספר איוב",
  "sub_book_name": null,
  "chapters": {}
}"""

_JSON_INDEX_0 = """\
[{"stmpl": "מ:פסוק|איוב|א|ב"}]"""

_JSON_EP_EXAMPLE = """\
[
  "אִ֛ישׁ הָיָ֥ה בְאֶֽרֶץ־ע֖וּץ אִיּ֣וֹב שְׁמ֑וֹ וְהָיָ֣ה",
  {"stmpl": "מ:לגרמיה-2"},
  " הָאִ֣ישׁ הַה֗וּא תָּ֧ם וְיָשָׁ֛ר וִירֵ֥א אֱלֹהִ֖ים וְסָ֥ר מֵרָֽע׃"
]"""

_JSON_STMPL = """\
{"stmpl": "מ:פסוק|איוב|א|ב"}"""

_JSON_TMPL = """\
{
  "tmpl": [
    ["#בלי קטע:", {"stmpl": "שם הדף המלא"}],
    ["סימן"]
  ]
}"""

_JSON_CUSTOM_TAG = """\
{"custom_tag": "noinclude"}
{"custom_tag": "/noinclude"}"""

_JSON_KQ = """\
{"stmpl": "קו\\"כ|את|אַ֠תָּ֠ה"}"""

_JSON_NUSACH = """\
{"stmpl": "נוסח|וּבֵרְﬞכ֥וּ|2=א=וּבֵרֲכ֥וּ (חטף)"}"""


def gen_html_file(tdm_ch):
    """Generate reading_mam_parsed_plain.html in the given output directory."""
    cbody = _build_body()
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


# ---------------------------------------------------------------------------
# Body builder
# ---------------------------------------------------------------------------


def _build_body():
    return [
        mb_html.heading_level_1(_TITLE),
        _s_intro(),
        *_s_file_naming(),
        *_s_top_level(),
        *_s_book39(),
        *_s_chapter(),
        *_s_verse(),
        *_s_template_objects(),
        *_s_common_templates(),
        *_s_pseudo_verses(),
    ]


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


def _s_intro():
    return author.para(
        [
            "\u26a0\ufe0f Note: This documentation was AI-generated and is known"
            " to contain inaccuracies, but it is a lot better than no documentation.",
        ]
    )


def _s_file_naming():
    rows = [
        ["A1\u2013A5", "Torah", "Genesis, Exodus, Leviticus, Numbers, Deuteronomy"],
        ["B1, B2, BA, BC", "Former Prophets", "Joshua, Judges, Samuel, Kings"],
        [
            "C1\u2013C3, CA",
            "Latter Prophets",
            "Isaiah, Jeremiah, Ezekiel, The 12 Minor Prophets",
        ],
        ["D1\u2013D3", "Wisdom", "Psalms, Proverbs, Job"],
        [
            "E1\u2013E5",
            "Five Scrolls",
            "Song of Songs, Ruth, Lamentations, Ecclesiastes, Esther",
        ],
        ["F1, FA, FC", "Late Books", "Daniel, Ezra-Nehemiah, Chronicles"],
    ]
    return [
        author.heading_level_2("File naming"),
        author.para(
            [
                "File names start with two characters that identify the book"
                " (in the \u201c24 books\u201d sense) and provide a standard ordering."
                " The first character (",
                mb_html.code("sec_char"),
                ") comes from the set ABCDEF and indicates the section of Tanakh."
                " The second character (",
                mb_html.code("book24_char"),
                ") comes from the set 12345AC and indicates the book within that section.",
            ]
        ),
        author.para(
            [
                "Files are named ",
                mb_html.code("{sec_char}{book24_char}-{EnglishName}.json"),
                ":",
            ]
        ),
        author.std_table(rows, arg_to_troh=["Prefix", "Section", "Books"]),
        author.para(
            [
                "When ",
                mb_html.code("book24_char"),
                " is A or C,"
                " the file is a composite book containing multiple sub-books"
                " (e.g. BA-Samuel contains both 1 Samuel and 2 Samuel)."
                " The letter B is not used in order to keep compatibility"
                " with a set of codes used for the 39-book system.",
            ]
        ),
    ]


def _s_top_level():
    rows = [
        [
            mb_html.code("header"),
            "object",
            "Metadata: book names, sub-book names, chapter counts.",
        ],
        [mb_html.code("book39s"), "array", "One element per book39 (sub-book)."],
    ]
    return [
        author.heading_level_2("Top-level structure"),
        json_block.json_block_raw_html(_JSON_TOP_LEVEL),
        author.std_table(rows, arg_to_troh=["Key", "Type", "Description"]),
        author.heading_level_3("Composite books"),
        author.para(
            [
                "For composite books like Samuel, ",
                mb_html.code("book39s"),
                " has multiple entries:",
            ]
        ),
        json_block.json_block_raw_html(_JSON_COMPOSITE),
    ]


def _s_book39():
    return [
        author.heading_level_2("Book39 entry"),
        json_block.json_block_raw_html(_JSON_BOOK39),
    ]


def _s_chapter():
    rows = [
        [mb_html.code('"0"'), "Pre-chapter", "Wiki navigation templates, page setup"],
        ["Hebrew numerals", "Normal verses", "Actual verse data"],
        [
            author.hbo('"תתת"'),
            "Post-chapter",
            "Wiki footer templates, end-of-chapter markup",
        ],
    ]
    return [
        author.heading_level_2("Chapter structure"),
        author.para(
            [
                "The ",
                mb_html.code("chapters"),
                " dict is keyed as follows:",
            ]
        ),
        author.std_table(rows, arg_to_troh=["Key", "Category", "Purpose"]),
        author.para(
            [
                "The keys for normal verses are Hebrew numerals conforming to the system"
                " that uses \u05d8\u05d5 and \u05d8\u05d6 for 15 and 16,"
                " avoiding the divine-name letter-pairs."
            ]
        ),
    ]


def _s_verse():
    col_rows = [
        [
            "D",
            [
                "Verse label (",
                mb_html.code("מ:פסוק"),
                " template): book name, chapter, verse, etc.",
            ],
        ],
        [
            "C",
            [
                "Verse separator: $parashah break or ",
                mb_html.code('"__"'),
                " for a plain space",
            ],
        ],
        ["E", "Verse text with inline templates"],
    ]

    sep_rows = [
        [author.hbo("פפ"), "Parashah petuchah (open paragraph)"],
        [author.hbo("סס"), "Parashah setumah (closed paragraph)"],
        [
            author.hbo("מ:ספר חדש"),
            "New book marker \u2014 marks the start of one of the 24 books with defined spacing. Not used for second halves of two-part books or individual Minor Prophets after Hosea.",
        ],
        [
            author.hbo("מ:אין פרשה בתחילת פרק"),
            "No $parashah at chapter start \u2014 tags chapters that don\u2019t begin with a visible $parashah.",
        ],
    ]
    sep_more_rows = [
        [
            author.hbo("פפפ"),
            "Open $parashah starting immediately on the next line (no blank line)",
        ],
        [
            author.hbo("ססס"),
            "Closed $parashah inline \u2014 blank spaces mid-line with text before and after",
        ],
        [author.hbo("סס2"), "Narrow closed $parashah"],
        [author.hbo("פסקא באמצע פסוק"), "Parashah division within a verse"],
        [author.hbo("מ:רווח בתרי עשר"), "Spacing between Minor Prophets"],
        [
            author.hbo("מ:רווח לספר בתהלים"),
            "Spacing between the 5 \u201cbooks\u201d of Psalms (Psalms 1, 42, 73, 90, 107)",
        ],
    ]
    return [
        author.heading_level_2("Verse (pseudo-verse) structure"),
        author.para(
            "Each verse is a 3-element array corresponding to the D, C, and E"
            " columns of the Google Sheet. (This ordering, rather than C, D, E,"
            " made more sense in this context.)"
        ),
        author.std_table(col_rows),
        author.heading_level_3("Index 0 (Google column D): Verse label"),
        author.para(
            [
                "The context at index 0 is empty ",
                mb_html.code("[]"),
                " for pseudo-verses. For normal verses, it is a list containing exactly"
                " one element: the ",
                author.hbo("מ:פסוק"),
                " template labeling the verse, e.g. for Job 1:2:",
            ]
        ),
        json_block.json_block_raw_html(_JSON_INDEX_0),
        author.para(
            [
                "The three required parameters are book name (Hebrew alphabet string),"
                " chapter number (Hebrew numeral), and verse number (Hebrew numeral)."
                " Optional named parameters include ",
                author.hbo("סדר="),
                " (seder number) and ",
                author.hbo("עלייה="),
                " (Torah $aliyah identification).",
            ]
        ),
        author.heading_level_3("Index 1 (Google column C): Verse separator"),
        author.para(
            [
                "The contents at index 1 indicate how this verse is separated from"
                " the preceding verse. ",
                mb_html.code('"__"'),
                " is by far the most common value, indicating a plain space."
                " More interesting values include:",
            ]
        ),
        author.std_table(sep_rows, arg_to_troh=["Template", "Meaning"]),
        author.para("Additional $parashah-related templates that may appear:"),
        author.std_table(sep_more_rows, arg_to_troh=["Template", "Meaning"]),
        author.para(
            [
                "The ",
                mb_html.code('"//"\u200b'),
                " strings sometimes sprinkled in"
                " index 1 are Wikitext line breaks from the Google Sheet.",
            ]
        ),
        author.heading_level_3("EP column (index 2): Verse text"),
        author.para(
            "Contains the actual verse text as a mixed array of strings"
            " (Hebrew text with cantillation marks) and template objects"
            " (inline markup). Example (Job 1:1):"
        ),
        json_block.json_block_raw_html(_JSON_EP_EXAMPLE),
    ]


def _s_template_objects():
    return [
        author.heading_level_2("Template objects in plain"),
        author.para("The plain format uses three kinds of template objects:"),
        author.heading_level_3("1. Stringified template (stmpl)"),
        author.para(
            [
                "Many templates are simple enough to appear as a pipe-delimited string:",
            ]
        ),
        json_block.json_block_raw_html(_JSON_STMPL),
        author.para(
            [
                "This represents the Wikitext ",
                mb_html.code("{{מ:פסוק|איוב|א|ב}}"),
                "." " The first segment (before ",
                mb_html.code("|"),
                ") is the template name; remaining segments are positional arguments.",
            ]
        ),
        author.heading_level_3("2. Parsed template tree (tmpl)"),
        author.para("Longer and/or more complex templates appear as parse trees:"),
        json_block.json_block_raw_html(_JSON_TMPL),
        author.para(
            [
                "The first sub-array is the template name."
                " Subsequent sub-arrays are the arguments,"
                " which may contain nested template \u201ccalls\u201d.",
            ]
        ),
        author.heading_level_3("3. Custom XML tag (custom_tag)"),
        author.para("Wikitext custom XML tags that appear in pseudo-verses:"),
        json_block.json_block_raw_html(_JSON_CUSTOM_TAG),
    ]


def _s_common_templates():
    kq_rows = [
        [
            author.hbo('כו"ק'),
            [
                "Standard ketiv-$qere. Param 1 = unpointed ketiv,"
                " param 2 = pointed $qere.",
            ],
        ],
        [
            author.hbo('קו"כ'),
            [
                "Post-$maqaf ketiv-$qere. Same parameters as ",
                author.hbo('כו"ק'),
                " but used when the pair follows a $maqaf.",
            ],
        ],
        [
            author.hbo('מ:קו"כ-אם-2'),
            [
                "Trivial ketiv-$qere. Param 1 = pointed ketiv, param 2 = unpointed ketiv,"
                " param 3 = pointed $qere.",
            ],
        ],
        [
            author.hbo("כתיב ולא קרי"),
            [
                "Ketiv without $qere. Single parameter = the ketiv.",
            ],
        ],
        [
            author.hbo("קרי ולא כתיב"),
            [
                "Qere without ketiv. Single parameter = the $qere.",
            ],
        ],
        [
            author.hbo('מ:כו"ק מיוחד'),
            [
                "Special ketiv-$qere. The required ",
                author.hbo("סוג="),
                " named parameter identifies the subtype." " See the ",
                mb_html.anchor_h("plus format documentation", _PLUS_DOC),
                " for the full subtype list.",
            ],
        ],
    ]
    special_letter_rows = [
        [
            author.hbo("מ:אות-ג"),
            "Large letter. Marks a masoretically large letter. Parameter is the pointed letter.",
        ],
        [
            author.hbo("מ:אות-ק"),
            "Small letter. Marks a masoretically small letter. Parameter is the pointed letter.",
        ],
        [
            author.hbo("מ:אות תלויה"),
            "Suspended (hung) letter. Appears raised in the text.",
        ],
        [
            author.hbo("מ:אות מנוקדת"),
            "Dotted letter/word. Marks words with masoretic dots above/below.",
        ],
        [
            author.hbo('מ:נו"ן הפוכה'),
            "Reversed $nun. The inverted $nun mark (Unicode character).",
        ],
    ]
    accent_rows = [
        [
            author.hbo("מ:לגרמיה-2"),
            "$Legarmeh. The vertical line \u05c0 as $legarmeh (part of the word\u2019s cantillation). Shares Unicode with $paseq but differs in function.",
        ],
        [
            author.hbo("מ:פסק"),
            "$Paseq. The vertical line \u05c0 as $paseq in the narrow sense, i.e. $paseq as distinct from $legarmeh.",
        ],
        [
            author.hbo("מ:מקף אפור"),
            "Gray $maqaf. A $maqaf that is only implicit in the manuscript. Appears only in poetic verses.",
        ],
        [
            author.hbo("מ:דחי"),
            "De\u1e25i variation. Presents both stress-helped and non-stress-helped versions of a word.",
        ],
        [
            author.hbo("מ:צינור"),
            "Tsinnor variation. Presents both stress-helped and non-stress-helped versions of a word.",
        ],
        [
            author.hbo("גלגל-2"),
            "Galgal. Distinguishes poetic from prose uses of Unicode YERAH BEN YOMO.",
        ],
        [
            author.hbo("ירח בן יומו"),
            "Yera\u1e25 ben yomo. Distinguishes prose from poetic uses of Unicode YERAH BEN YOMO.",
        ],
        [
            author.hbo("אתנח הפוך"),
            "Atna\u1e25 hafukh. Helps distinguish this accent from galgal/yera\u1e25 ben yomo.",
        ],
        [
            author.hbo("מ:קמץ"),
            [
                "Qamats variation. Named params: ",
                author.hbo("ד="),
                " (grammatical) and ",
                author.hbo("ס="),
                " (Sephardic tradition).",
            ],
        ],
    ]
    jer_rows = [
        [
            author.hbo("מ:ירושלם"),
            "Handles the masoretic spelling of Jerusalem without $yod. Two params (vowel and accent of $lamed).",
        ],
        [
            author.hbo("מ:ירושלמה"),
            "Like \u05de:\u05d9\u05e8\u05d5\u05e9\u05dc\u05dd but for the directional form \u201cto Jerusalem\u201d (4 cases).",
        ],
    ]
    poetic_rows = [
        [
            author.hbo("ר1"),
            "Following stich on its own line, one indent. In 2 cases (Ps 70, 108) represents a closed $parashah.",
        ],
        [author.hbo("ר2"), "Following stich on its own line, two indents."],
        [author.hbo("ר3"), "Following stich at line start, no indent."],
        [author.hbo("ר4"), "New verse at line start, no indent."],
        [
            author.hbo("ר0"),
            "Extra division point when a verse has an odd number of stiches, for even-column display.",
        ],
        [
            author.hbo("פרשה-מרכז"),
            "Centered title. For \u201ctitles\u201d in Job and Proverbs. Parameter is the title text.",
        ],
    ]
    other_rows = [
        [
            [author.hbo("פפ"), " / ", author.hbo("סס")],
            "Parashah petuchah / setumah (primarily in D column)",
        ],
        [
            author.hbo("מ:סיום בטוב"),
            "Good ending. Repeats the penultimate verse so public reading ends positively. Used at the end of Lamentations, Ecclesiastes, Isaiah, and Malachi.",
        ],
        [
            author.hbo("מ:טעם ומתג באות אחת"),
            "Normalization-robust meteg for 10 cases where a below-accent and meteg share one letter.",
        ],
        [
            author.hbo("מ:גרש ותלישא גדולה"),
            "Combined $geresh + $telisha gedolah (2 words, 3 uses). No parameters.",
        ],
        [
            author.hbo("מ:גרשיים ותלישא גדולה"),
            "Combined gershayim + $telisha gedolah (3 words, 4 uses). No parameters.",
        ],
    ]
    sheets_link = mb_html.anchor_h("Templates tab", _SHEETS_TMPL)
    sheets_data_link = mb_html.anchor_h("MAM Google Sheet", _SHEETS_DATA)
    return [
        author.heading_level_2("Common templates in the EP (verse text) column"),
        author.para(
            [
                "For authoritative English and Hebrew descriptions of every template,"
                " see the ",
                sheets_link,
                " of the ",
                sheets_data_link,
                ".",
            ]
        ),
        author.heading_level_3("Documentation template (\u05e0\u05d5\u05e1\u05d7)"),
        author.para(
            [
                "Its first parameter is the \u201ctarget\u201d \u2014 what is being documented."
                " The second parameter contains the documentation"
                " (anomalous forms, variant readings, uncertain readings, etc.):",
            ]
        ),
        json_block.json_block_raw_html(_JSON_NUSACH),
        author.heading_level_3("Ketiv-$qere templates"),
        author.std_table(kq_rows, arg_to_troh=["Template", "Purpose"]),
        author.para(
            [
                "Current values observed for optional ",
                author.hbo("סוג="),
                " in ",
                author.hbo('מ:קו"כ-אם-2'),
                ":",
            ]
        ),
        author.unordered_list(
            [
                author.hbo('אל"ף נחה באמצע תיבה ולא נקראת'),
                author.hbo('כתיב ה"א בסיומת של חולם'),
                author.hbo("כתיב הוא קרי היא"),
                author.hbo('כתיב חסר יו"ד בסיומת של קמץ ואחריו וי"ו'),
                author.hbo("כתיב נער קרי נערה"),
            ]
        ),
        author.para("Example of standard ketiv-$qere:"),
        json_block.json_block_raw_html(_JSON_KQ),
        author.heading_level_3("Special letter templates"),
        author.std_table(special_letter_rows, arg_to_troh=["Template", "Purpose"]),
        author.heading_level_3("Accent and cantillation templates"),
        author.std_table(accent_rows, arg_to_troh=["Template", "Purpose"]),
        author.heading_level_3("Jerusalem spelling"),
        author.std_table(jer_rows, arg_to_troh=["Template", "Purpose"]),
        author.heading_level_3(
            "Poetic form templates (\u05e1\u05e4\u05e8\u05d9 \u05d0\u05de\u05ea)"
        ),
        author.std_table(poetic_rows, arg_to_troh=["Template", "Purpose"]),
        author.para(
            "Many editions will choose to skip poetic formatting by treating"
            " \u05e40\u2013\u05e44 as simple word spaces."
        ),
        author.heading_level_3("Footnote template"),
        author.std_table(
            [
                [
                    author.hbo("מ:הערה"),
                    "Scroll-difference footnote (Torah and Esther only). Footnote markers appear within the text itself. Parameter is the footnote text.",
                ]
            ],
            arg_to_troh=["Template", "Purpose"],
        ),
        author.heading_level_3("Other templates"),
        author.std_table(other_rows, arg_to_troh=["Template", "Purpose"]),
    ]


def _s_pseudo_verses():
    return [
        author.heading_level_2("Pseudo-verses (0 and \u05ea\u05ea\u05ea)"),
        author.para(
            [
                "The ",
                mb_html.code('"0"'),
                " and ",
                author.hbo('"תתת"'),
                " keys are pseudo-verses that contain"
                " Wiki-specific navigation and formatting markup, not biblical text."
                " They can generally be skipped when extracting verse content.",
            ]
        ),
        author.unordered_list(
            [
                [
                    mb_html.code('"0"'),
                    ": Contains ",
                    mb_html.code("noinclude"),
                    " tags, navigation templates, margin settings.",
                ],
                [
                    author.hbo('"תתת"'),
                    ": Contains end-of-chapter markers, unnumbered-verse section.",
                ],
            ]
        ),
    ]
