# Initially generated by GitHub Copilot.
"""Shared table data for reading_mam_parsed_plain and reading_mam_parsed_plus docs."""

from mb_misc import mb_html
from author_util import author
from author_util import json_block

# ---------------------------------------------------------------------------
# JSON snippets shared by plain and plus common-templates sections
# ---------------------------------------------------------------------------

JSON_KQ = """\
{"stmpl": "קו\\"כ|את|אַ֠תָּ֠ה"}"""

JSON_NUSACH = """\
{"stmpl": "נוסח|וּבֵרְﬞכ֥וּ|2=א=וּבֵרֲכ֥וּ (חטף)"}"""

# ---------------------------------------------------------------------------
# Table row data
# ---------------------------------------------------------------------------

KQ_ROWS = [
    [
        author.hbo('כו"ק'),
        [
            "Standard ketiv-$qere. Param 1 = unpointed ketiv,"
            " param 2 = pointed $qere.",
        ],
    ],
    [
        author.hbo('קו"כ'),
        [
            "Post-$maqaf ketiv-$qere. Same parameters as ",
            author.hbo('כו"ק'),
            " but used when the pair follows a $maqaf.",
        ],
    ],
    [
        author.hbo('מ:קו"כ-אם-2'),
        [
            "Trivial ketiv-$qere. Param 1 = pointed ketiv, param 2 = unpointed ketiv,"
            " param 3 = pointed $qere.",
        ],
    ],
    [
        author.hbo("כתיב ולא קרי"),
        [
            "Ketiv without $qere. Single parameter = the ketiv.",
        ],
    ],
    [
        author.hbo("קרי ולא כתיב"),
        [
            "Qere without ketiv. Single parameter = the $qere.",
        ],
    ],
    [
        author.hbo('מ:כו"ק מיוחד'),
        [
            "Special ketiv-$qere. The required ",
            author.hbo("סוג="),
            " named parameter identifies the subtype. Nine subtypes.",
        ],
    ],
]

KQ_AM2_SUG_LIST = [
    author.hbo('אל"ף נחה באמצע תיבה ולא נקראת'),
    author.hbo('כתיב ה"א בסיומת של חולם'),
    author.hbo("כתיב הוא קרי היא"),
    author.hbo('כתיב חסר יו"ד בסיומת של קמץ ואחריו וי"ו'),
    author.hbo("כתיב נער קרי נערה"),
]

SPECIAL_LETTER_ROWS = [
    [
        author.hbo("מ:אות-ג"),
        "Large letter. Marks a masoretically large letter. Parameter is the pointed letter.",
    ],
    [
        author.hbo("מ:אות-ק"),
        "Small letter. Marks a masoretically small letter. Parameter is the pointed letter.",
    ],
    [
        author.hbo("מ:אות תלויה"),
        "Suspended (hung) letter. Appears raised in the text.",
    ],
    [
        author.hbo("מ:אות מנוקדת"),
        "Dotted letter/word. Marks words with masoretic dots above/below.",
    ],
    [
        author.hbo('מ:נו"ן הפוכה'),
        "Reversed $nun. The inverted $nun mark (Unicode character).",
    ],
]

ACCENT_ROWS = [
    [
        author.hbo("מ:לגרמיה-2"),
        "$Legarmeh. The vertical line \u05c0 as $legarmeh (part of the word\u2019s cantillation). Shares Unicode with $paseq but differs in function.",
    ],
    [
        author.hbo("מ:פסק"),
        "$Paseq. The vertical line \u05c0 as $paseq in the narrow sense, i.e. $paseq as distinct from $legarmeh.",
    ],
    [
        author.hbo("מ:מקף אפור"),
        "Gray $maqaf. A $maqaf that is only implicit in the manuscript. Appears only in poetic verses.",
    ],
    [
        author.hbo("מ:דחי"),
        "De\u1e25i variation. Presents both stress-helped and non-stress-helped versions of a word.",
    ],
    [
        author.hbo("מ:צינור"),
        "Tsinnor variation. Presents both stress-helped and non-stress-helped versions of a word.",
    ],
    [
        author.hbo("גלגל-2"),
        "Galgal. Distinguishes poetic from prose uses of Unicode YERAH BEN YOMO.",
    ],
    [
        author.hbo("ירח בן יומו"),
        "Yera\u1e25 ben yomo. Distinguishes prose from poetic uses of Unicode YERAH BEN YOMO.",
    ],
    [
        author.hbo("אתנח הפוך"),
        "Atna\u1e25 hafukh. Helps distinguish this accent from galgal/yera\u1e25 ben yomo.",
    ],
    [
        author.hbo("מ:קמץ"),
        [
            "Qamats variation. Named params: ",
            author.hbo("ד="),
            " (grammatical) and ",
            author.hbo("ס="),
            " (Sephardic tradition).",
        ],
    ],
]

JER_ROWS = [
    [
        author.hbo("מ:ירושלם"),
        "Handles the masoretic spelling of Jerusalem without $yod. Two params (vowel and accent of $lamed).",
    ],
    [
        author.hbo("מ:ירושלמה"),
        "Like \u05de:\u05d9\u05e8\u05d5\u05e9\u05dc\u05dd but for the directional form \u201cto Jerusalem\u201d (4 cases).",
    ],
]

POETIC_ROWS = [
    [
        author.hbo("ר1"),
        "Following stich on its own line, one indent. In 2 cases (Ps 70, 108) represents a closed $parashah.",
    ],
    [author.hbo("ר2"), "Following stich on its own line, two indents."],
    [author.hbo("ר3"), "Following stich at line start, no indent."],
    [author.hbo("ר4"), "New verse at line start, no indent."],
    [
        author.hbo("ר0"),
        "Extra division point when a verse has an odd number of stiches, for even-column display.",
    ],
    [
        author.hbo("פרשה-מרכז"),
        "Centered title. For \u201ctitles\u201d in Job and Proverbs. Parameter is the title text.",
    ],
]

FOOTNOTE_ROW = [
    author.hbo("מ:הערה"),
    "Scroll-difference footnote (Torah and Esther only). Footnote markers appear within the text itself. Parameter is the footnote text.",
]

OTHER_ROWS = [
    [
        [author.hbo("פפ"), " / ", author.hbo("סס")],
        "Parashah petuchah / setumah (primarily in D column)",
    ],
    [
        author.hbo("מ:סיום בטוב"),
        "Good ending. Repeats the penultimate verse so public reading ends positively. Used at the end of Lamentations, Ecclesiastes, Isaiah, and Malachi.",
    ],
    [
        author.hbo("מ:טעם ומתג באות אחת"),
        "Normalization-robust meteg for 10 cases where a below-accent and meteg share one letter.",
    ],
    [
        author.hbo("מ:גרש ותלישא גדולה"),
        "Combined $geresh + $telisha gedolah (2 words, 3 uses). No parameters.",
    ],
    [
        author.hbo("מ:גרשיים ותלישא גדולה"),
        "Combined gershayim + $telisha gedolah (3 words, 4 uses). No parameters.",
    ],
]

KQ_SPECIAL_ROWS = [
    [
        author.hbo('כו"ק בין שני מקפים'),
        "Ketiv-$qere between two maqafim (Isaiah 26:20 only)",
    ],
    [
        author.hbo('כו"ק כתיב מילה חדה וקרי תרתין מילין'),
        "1-word ketiv mapped to 2-atom $qere",
    ],
    [
        author.hbo('כו"ק כתיב מילה חדה וקרי תרתין מילין בין שני מקפים'),
        "Same as above but between maqafim (1 Chronicles 9:4 only)",
    ],
    [
        author.hbo('כו"ק כתיב תרתין מילין וקרי מילה חדה'),
        "2-word ketiv mapped to 1-atom $qere",
    ],
    [
        author.hbo('קו"כ כתיב מילה חדה וקרי תרתין מילין'),
        "Like the k1\u2192q2 case but in reversed (qk) display order, for use after $maqaf (Nehemiah 2:13 only)",
    ],
    [
        author.hbo('כו"ק קרי שונה מהכתיב בשתי מילים'),
        "1-word ketiv, 2-word $qere (kq display order)",
    ],
    [
        author.hbo('קו"כ קרי שונה מהכתיב בשתי מילים'),
        "1-word ketiv, 2-word $qere in reversed (qk) display order (2 Kgs 18:27, Isa 36:12)",
    ],
    [author.hbo('כו"ק של שתי מילים בהערה אחת'), "2-word ketiv, 2-atom $qere"],
    [
        author.hbo('כו"ק של שלוש מילים בהערה אחת'),
        "3-word ketiv, 3-atom $qere (2 Samuel 21:12)",
    ],
]

# ---------------------------------------------------------------------------
# Google Sheet URLs (shared by plain and plus docs)
# ---------------------------------------------------------------------------

SHEETS_TMPL = "https://purl.org/mam/google-sheet#gid=1670945398"
SHEETS_DATA = "https://purl.org/mam/google-sheet#gid=920165745"

# ---------------------------------------------------------------------------
# Top-level, composite-book, and book39 JSON snippets
# (shared by plain and plus docs)
# ---------------------------------------------------------------------------

JSON_TOP_LEVEL = """\
{
  "header": {
    "book24_names": ["ספר איוב"],
    "sub_book_names": {},
    "chapter_counts": [
      {
        "book24_name": "ספר איוב",
        "sub_book_name": null,
        "chapter_count": 42
      }
    ]
  },
  "book39s": []
}"""

JSON_COMPOSITE = """\
{
  "header": {
    "book24_names": ["ספר שמואל"],
    "sub_book_names": {"ספר שמואל": ["שמ\\"א", "שמ\\"ב"]},
    "chapter_counts": [
      {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"א", "chapter_count": 31},
      {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"ב", "chapter_count": 24}
    ]
  },
  "book39s": [
    {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"א", "chapters": {}},
    {"book24_name": "ספר שמואל", "sub_book_name": "שמ\\"ב", "chapters": {}}
  ]
}"""

JSON_BOOK39 = """\
{
  "book24_name": "ספר איוב",
  "sub_book_name": null,
  "chapters": {}
}"""


# ---------------------------------------------------------------------------
# File naming section (shared by plain and plus docs)
# ---------------------------------------------------------------------------


def s_file_naming():
    rows = [
        [
            "A1\N{EN DASH}A5",
            "Torah",
            "Genesis, Exodus, Leviticus, Numbers, Deuteronomy",
        ],
        ["B1, B2, BA, BC", "Former Prophets", "Joshua, Judges, Samuel, Kings"],
        [
            "C1\N{EN DASH}C3, CA",
            "Latter Prophets",
            "Isaiah, Jeremiah, Ezekiel, The 12 Minor Prophets",
        ],
        ["D1\N{EN DASH}D3", "Wisdom", "Psalms, Proverbs, Job"],
        [
            "E1\N{EN DASH}E5",
            "Five Scrolls",
            "Song of Songs, Ruth, Lamentations, Ecclesiastes, Esther",
        ],
        ["F1, FA, FC", "Late Books", "Daniel, Ezra-Nehemiah, Chronicles"],
    ]
    return [
        author.heading_level_2("File naming"),
        author.para(
            [
                "File names (e.g. ",
                mb_html.code("A1-Genesis.json"),
                ") start with two characters that identify the book"
                " (in the \u201c24 books\u201d sense) and provide a standard ordering."
                " The first character (",
                mb_html.code("sec_char"),
                ") comes from the set ABCDEF and indicates the section of Tanakh."
                " The second character (",
                mb_html.code("book24_char"),
                ") comes from the set 12345AC and indicates the book within that section.",
            ]
        ),
        author.para(
            [
                "Files are named ",
                mb_html.code("{sec_char}{book24_char}-{EnglishName}.json"),
                ":",
            ]
        ),
        author.std_table(rows, arg_to_troh=["Prefix", "Section", "Books"]),
        author.para(
            [
                "When ",
                mb_html.code("book24_char"),
                " is A or C,"
                " the file is a composite book containing multiple sub-books"
                " (e.g. BA-Samuel contains both 1 Samuel and 2 Samuel)."
                " The letter B is not used in order to keep compatibility"
                " with a set of codes used for the 39-book system.",
            ]
        ),
    ]
