# Initially generated by GitHub Copilot.
"""HTML document: reading MAM-parsed plus JSON format."""

from mb_misc import mb_html
from author_util import author
from author import reading_mam_parsed_plus_body as body

_FNAME = "reading_mam_parsed_plus.html"
_TITLE = "Reading MAM-parsed plus JSON"


def gen_html_file(tdm_ch):
    """Generate reading_mam_parsed_plus.html in the given output directory."""
    cbody = _build_body()
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def _build_body():
    plain_link = mb_html.anchor_h("plain format", body._PLAIN_DOC)
    return [
        mb_html.heading_level_1(_TITLE),
        *body.s_intro(plain_link),
        *body.s_top_level(),
        *body.s_book39(),
        *body.s_chapter_verse(),
        *body.s_plus_only_templates(),
        *body.s_common_templates(),
        *body.s_not_in_plus(),
    ]
