# Initially generated by GitHub Copilot.
"""Bot edit: add סוג=... to מ:קו"כ-אם-2 for named trivial k/q subtypes.

Targets only the five named z-trivial subtypes:
  - QyV
  - extra-alef
  - hi-spelled-hu
  - n3rh-spelled-n3r
  - xolam-he

For subtype misc, no סוג is added.

Concordance is fail-fast: for every encountered מ:קו"כ-אם-2 template,
classifier output must match FOI subtype for the same (bcv_short, pqere).

Warnings are accumulated in _warnings and retrieved via get_warnings().
The caller is responsible for writing them to a file.
"""

from functools import partial

from foi import kq_trivial_types as ktt
from foi import kq_trivial_sug as kqs
from mb_cmn import bib_locales as tbn
from mb_cmn import hebrew_verse_numerals as hvn
from mb_cmn import uni_denorm as udn
from mb_cmn import ws_tmpl1 as wtp1
from mb_cmn import ws_tmpl2 as wtp
from mb_cmn.my_utils import dv_dispatch
from mb_cmn.my_utils import dkv_map
from mb_cmn.my_utils import sl_map
from mb_cmn.my_utils import sum_of_map
from mb_cmn.shrink import shrink
from ws import ws_fmt_2_back_to_wikitext as btw
from ws import ws_get_bk_in_both_fmts as wsin
from ws import ws_unparse
from ws import ws_foi_kq_trivial_scope as kq_scope

# Module-level context set per chapter/verse during edit_page_text.
_ctx = {
    "bk39id": None,
    "he_chnu": None,
    "chapter": None,
    "he_vrnu": None,
    "verse": None,
}
_warnings = []
_subtypes_by_bcv_pqere = None

_TMPL_NAME = 'מ:קו"כ-אם-2'


def get_warnings():
    """Return accumulated warning entries (list of dicts)."""
    return list(_warnings)


def _warn(reason, tmpl, **extra):
    _warnings.append(
        {
            "bk39id": _ctx["bk39id"],
            "he_chnu": _ctx["he_chnu"],
            "chapter": _ctx["chapter"],
            "he_vrnu": _ctx["he_vrnu"],
            "verse": _ctx["verse"],
            "bcv_short": _bcv_short(),
            "reason": reason,
            "old_tmpl_text": ws_unparse.unparse(tmpl),
            **extra,
        }
    )


def _bcv_short():
    return tbn.short_bcv((_ctx["bk39id"], _ctx["chapter"], _ctx["verse"]))


def _foi_subtypes_by_bcv_pqere():
    global _subtypes_by_bcv_pqere
    if _subtypes_by_bcv_pqere is None:
        _subtypes_by_bcv_pqere = kq_scope.subtype_by_bcv_pqere()
    return _subtypes_by_bcv_pqere


def _assert_foi_concordance(bcv_short, pqere_std, pqere_raw, classifier_subtype):
    foi_subtype = _foi_subtypes_by_bcv_pqere().get((bcv_short, pqere_std))
    assert foi_subtype is not None, (
        "Missing FOI subtype for trivial-kq template",
        {
            "book39": _ctx["bk39id"],
            "chapter": _ctx["chapter"],
            "verse": _ctx["verse"],
            "bcv_short": bcv_short,
            "pqere": pqere_raw,
            "classifier_subtype": classifier_subtype,
            "foi_subtype": foi_subtype,
        },
    )
    assert classifier_subtype == foi_subtype, (
        "FOI/classifier subtype mismatch for trivial-kq template",
        {
            "book39": _ctx["bk39id"],
            "chapter": _ctx["chapter"],
            "verse": _ctx["verse"],
            "bcv_short": bcv_short,
            "pqere": pqere_raw,
            "classifier_subtype": classifier_subtype,
            "foi_subtype": foi_subtype,
        },
    )


def _transform_kq_triv_add_type(tmpl):
    """Add סוג=... on a single מ:קו"כ-אם-2 template when applicable."""
    tmpl2 = wtp.use_tmpl2(tmpl)
    assert wtp.is_template_with_name(tmpl2, _TMPL_NAME), tmpl2

    classifier_subtype = ktt.subtype_for_path(tmpl2)
    pqere_raw = ktt.pointed_qere_text(tmpl2)
    pqere_std = udn.give_std_mark_order(pqere_raw)
    bcv_short = _bcv_short()
    _assert_foi_concordance(bcv_short, pqere_std, pqere_raw, classifier_subtype)

    if classifier_subtype == ktt.MISC:
        return [tmpl]

    if "סוג" in wtp.template_param_keys(tmpl2):
        _warn(
            "existing-sug",
            tmpl,
            existing_sug=wtp.template_param_val(tmpl2, "סוג"),
            classifier_subtype=classifier_subtype,
        )
        return [tmpl]

    sug_text = kqs.sug_text_for_subtype(classifier_subtype)
    assert sug_text is not None, classifier_subtype

    old_els = wtp1.template_elements(tmpl)
    return [wtp1.mktmpl([*old_els, [f"סוג={sug_text}"]])]


def _pass_thru(val):
    return val


def _pass_thru_as_singleton(val):
    return [val]


def _edit_wtseq(wandlers, wtseq):
    return shrink(sum_of_map((_edit_wtel, wandlers), wtseq))


def _edit_wtel(wandlers, wtel):
    if isinstance(wtel, str):
        return wandlers["string"](wtel)
    if wtp1.is_abtag(wtel):
        return [wtel]
    return _edit_tmpl_call(wandlers, wtel)


def _edit_tmpl_call(wandlers, tmpl):
    if wandler := wandlers.get(wtp1.template_name(tmpl)):
        return wandler(tmpl)
    return _recurse_on_args(_get_wandlers, tmpl)


def _recurse_on_args(get_wandlers_fn, tmpl):
    tmpl_els_in = wtp1.template_elements(tmpl)
    assert isinstance(tmpl_els_in, list)
    wandlers = get_wandlers_fn()
    tmpl_args_out = sl_map((_edit_wtseq, wandlers), tmpl_els_in[1:])
    tmpl_els_out = [tmpl_els_in[0], *tmpl_args_out]
    return [wtp1.mktmpl(tmpl_els_out)]


def _get_wandlers():
    return _WANDLERS


def _edit_a_chap_body(vandlers, chap_body):
    return dkv_map((_edit_a_plb_verse, vandlers), chap_body)


def _edit_a_plb_verse(vandlers, he_vrnu, plb_verse):
    _ctx["he_vrnu"] = he_vrnu
    _ctx["verse"] = hvn.STR_TO_INT_DIC[he_vrnu]
    return dv_dispatch(vandlers, plb_verse)


_WANDLERS = {
    "string": _pass_thru_as_singleton,
    _TMPL_NAME: _transform_kq_triv_add_type,
}

_VANDLERS = {
    "prefix": _pass_thru,
    "location": _pass_thru,
    "verse-body": partial(_edit_wtseq, _WANDLERS),
}

_CANDLERS = {
    "ws-chap-noinclude-header": _pass_thru,
    "ws-chap-body": partial(_edit_a_chap_body, _VANDLERS),
    "ws-chap-good-ending": _pass_thru,
    "ws-chap-noinclude-footer": _pass_thru,
    "ws-chap-category": _pass_thru,
}


def edit_cif2(he_chnu, cif2):
    """Transform cif2 AST: add סוג on named trivial-k/q subtype templates."""
    out_cif2 = dv_dispatch(_CANDLERS, cif2)
    return out_cif2, btw.big_str(he_chnu, out_cif2)


def edit_page_text(bk39id, he_chnu, page_text):
    """Transform raw page text: add סוג on named trivial-k/q subtype templates."""
    _ctx["bk39id"] = bk39id
    _ctx["he_chnu"] = he_chnu
    _ctx["chapter"] = hvn.STR_TO_INT_DIC[he_chnu]
    cif2 = wsin.get_chap_in_fmt_2(page_text.splitlines())
    _out_cif2, big_str = edit_cif2(he_chnu, cif2)
    return big_str
