"""Render the redirect stubs that stand in for wlc-utils' published pages, and lint them.

WHAT A STUB IS FOR

``bdenckla.github.io/wlc-utils/<path>`` is cited from places Ben cannot edit -- five
citations of ``accgram/goerwitz.html`` in the tanach.us change list vendored into
UXLC-utils, four deep links carrying fragments in UXLC-utils' own published CLC notes,
and four paths in ``document-index/README.md``.  The pages themselves have moved to
``bdenckla.github.io/MAM-basics/wlc/<path>``, a pure prefix rewrite, so each old URL is
answered by a stub at its own old path that sends the reader on.  See
``doc/PLAN-evacuate-the-rest-of-wlc-utils.md``, Phases 8 and 9.

THE PAGE LIST IS THE SITE ITSELF, NOT A FILE

``page_paths`` derives the set from ``git ls-files gh-pages/wlc`` filtered to ``*.html``,
so nothing hand-maintained can drift from what is published: a page added later gets a
stub on the next ``build``, and one removed shows up in ``check`` as a stub with no page.
The relative path under ``gh-pages/wlc/`` is *both* the old wlc-utils path and the new
MAM-basics suffix, which is what makes the rewrite a prefix rewrite and this derivation
one string per page rather than a mapping.

A directory URL is covered only where the directory has an ``index.html``, which is the
right answer rather than an accident: ``document-index/README.md`` cites ``/420422/`` and
``/wlc-a-notes/``, and both hold one, so both get a stub that a bare directory URL
reaches.  ``/accgram/`` holds no ``index.html`` (issue #230 -- it 404s today, and always
did), so it correctly gets no stub and falls to the ``404.html`` catch-all below.

WITH JAVASCRIPT DISABLED, A FRAGMENT IS LOST -- AND THE JS IS NOT BELT-AND-BRACES

A stub carries the target three times over, and the three are not redundant.  The
``<link rel="canonical">`` tells a search engine which copy is current.  The
``<meta http-equiv="refresh">`` is the no-JavaScript path, and it takes a *fixed* URL.
Only the ``<script>`` can carry the incoming query and fragment, because
``#supplied-dt5v6-bet-atnax`` is arbitrary and is never sent to the server -- it is
readable only in the browser, as ``location.hash``.  So the degradation with JavaScript
off is precise: **UXLC-utils' four deep links land on the right page, at its top rather
than at the anchor.**  The script wins over the meta refresh when both are live, because
it runs synchronously while the document is parsed and the refresh is a scheduled task.

``404.html`` is the catch-all for every path with no stub -- the non-HTML assets Phase 9
deletes, ``/accgram/``, and anything mistyped.  It reads ``location.pathname``, strips the
leading ``/wlc-utils/`` and prepends the new site, so it forwards rather than guesses.
GitHub Pages serves it with an HTTP **404** status whatever it then does, which is exactly
why the per-page stubs exist: a cited URL has to answer 200.

WHAT ``build`` DOES NOT DO

It writes stubs and ``404.html`` and deletes nothing.  Phase 9's removal of wlc-utils'
130 non-HTML assets is a ``git rm``, kept out of a generator that can be pointed at
another repository's tree.  A stub left behind by a page that has since gone is reported
by ``check``, not silently cleaned up.
"""

from __future__ import annotations

from pathlib import Path
import re
import subprocess

from mb_cmn import paths

# The published site the stubs point at, and the path prefix the old site served under.
# Cite these by name rather than by their text: black splits a long string literal across
# adjacent literals to fit 88 columns, so a URL a page carries can appear nowhere in the
# source (Phase 7, finding 1).
NEW_SITE = "https://bdenckla.github.io/MAM-basics/wlc/"
OLD_PATH_PREFIX = "/wlc-utils/"

# The catch-all, which is a stub for no page and so is exempt from the correspondence
# check that every other .html in the tree faces.
NOT_FOUND_NAME = "404.html"

# Where the page list is read from, relative to this repo's root.
_PAGES_PREFIX = "gh-pages/wlc/"

# Any target URL the rendered text carries.  Stops at a quote, a space or a tag bracket,
# which is what bounds it in every one of the four places a stub spells it.
_TARGET_RE = re.compile(re.escape(NEW_SITE) + r"[^\"'\s<>]*")

# The four carriers, each identified by something only it has.  A stub missing one of
# these still redirects, so ``check`` has to look for them by name rather than trust that
# a file naming the right URL is a whole stub.
_CARRIERS = (
    ('rel="canonical"', "canonical link"),
    ('http-equiv="refresh"', "meta refresh"),
    ("location.replace(", "script"),
    ("<a href=", "visible fallback link"),
)

_STUB_TEMPLATE = """<!doctype html>
<!-- GENERATED by py/main_wlc_redirect_stubs.py -- do not edit; run that program again. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved to MAM-basics: {path}</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">
<script>
location.replace("{target}" + location.search + location.hash);
</script>
</head>
<body>
<p>This page has moved to <a href="{target}">{target}</a>.</p>
</body>
</html>
"""

_NOT_FOUND_TEMPLATE = """<!doctype html>
<!-- GENERATED by py/main_wlc_redirect_stubs.py -- do not edit; run that program again. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved to MAM-basics</title>
<script>
var wlcPrefix = "{old_prefix}";
var wlcPath = location.pathname;
var wlcRest = wlcPath.indexOf(wlcPrefix) === 0 ? wlcPath.slice(wlcPrefix.length) : "";
location.replace("{new_site}" + wlcRest + location.search + location.hash);
</script>
</head>
<body>
<p>These pages have moved to <a href="{new_site}">{new_site}</a>.</p>
</body>
</html>
"""


def wlc_utils_pages_dir() -> Path:
    """wlc-utils' published tree -- THE LAST REFERENCE TO THAT SIBLING IN THIS TREE.

    Phase 5 repointed every generator at this repo's own root, leaving the redirect stubs
    as the one thing that still has to name wlc-utils: the stubs are what that repository
    will hold, and they cannot be written or linted without finding it.  Routed through
    ``require_sibling`` so an absent clone says which two environment overrides point at
    one, rather than dying on a bare ``FileNotFoundError`` deep in a writer.
    """
    return (
        paths.require_sibling("wlc-utils", paths.sibling_repo("wlc-utils")) / "gh-pages"
    )


def default_out_dir() -> Path:
    """Where ``build`` writes when told neither ``--out`` nor ``--publish``.

    A gitignored scratch directory, so the safe destination is the default one and
    publishing into wlc-utils takes saying so.
    """
    return paths.novc_dir() / "wlc-redirect-stubs"


def page_paths(repo_root: Path) -> list[str]:
    """Every published page under ``gh-pages/wlc/``, as its path below that prefix.

    An empty result is a failure rather than an empty run: it means the site is not where
    this module thinks it is, and a build that then writes one file would look like it had
    worked.
    """
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", _PAGES_PREFIX],
        cwd=repo_root,
        capture_output=True,
        encoding="utf-8",
        check=True,
    )
    pages = sorted(
        entry[len(_PAGES_PREFIX) :]
        for entry in result.stdout.split("\0")
        if entry.endswith(".html")
    )
    if not pages:
        raise AssertionError(
            f"no .html tracked under {_PAGES_PREFIX} in {repo_root}: the published pages"
            " the stubs stand in for are not where this module looks for them, so every"
            " stub would be missing and nothing would say so."
        )
    return pages


def target_url(page_path: str) -> str:
    """The MAM-basics URL a stub at ``page_path`` sends the reader to."""
    return NEW_SITE + page_path


def render_stub(page_path: str) -> str:
    return _STUB_TEMPLATE.format(path=page_path, target=target_url(page_path))


def render_not_found() -> str:
    return _NOT_FOUND_TEMPLATE.format(old_prefix=OLD_PATH_PREFIX, new_site=NEW_SITE)


def write_stubs(repo_root: Path, out_dir: Path) -> list[str]:
    """Write a stub per page plus ``404.html``; return the paths written, site-relative."""
    written = []
    for page_path in page_paths(repo_root):
        destination = out_dir / page_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(render_stub(page_path), encoding="utf-8", newline="\n")
        written.append(page_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / NOT_FOUND_NAME).write_text(
        render_not_found(), encoding="utf-8", newline="\n"
    )
    return written + [NOT_FOUND_NAME]


def _found_html(stub_dir: Path) -> list[str]:
    return sorted(
        path.relative_to(stub_dir).as_posix()
        for path in stub_dir.rglob("*.html")
        if path.is_file()
    )


def check_problems(repo_root: Path, stub_dir: Path) -> list[str]:
    """Every way the tree at ``stub_dir`` fails to be the stub set for the live site.

    A mechanical lint over generated text, which is the second of the two test shapes
    ``CLAUDE.md`` sanctions: both sides are derived -- the page set from ``git ls-files``,
    each target from the stub's own path -- so a page added or renamed never needs this
    file edited.  Nothing here skips: an absent ``stub_dir`` and an empty page set are
    both failures.
    """
    if not stub_dir.is_dir():
        return [
            f"{stub_dir}: no such directory, so there are no stubs to check."
            " Run `build --out <dir>` first, or name the tree that holds them."
        ]
    expected = page_paths(repo_root)
    found = _found_html(stub_dir)
    problems = [
        f"{page_path}: published under {_PAGES_PREFIX} but no stub at that path in"
        f" {stub_dir} -- an old URL that is cited would 404 rather than redirect"
        for page_path in expected
        if page_path not in set(found)
    ]
    problems += [
        f"{stub_path}: a stub in {stub_dir} standing in for a page that is not published"
        f" under {_PAGES_PREFIX} -- delete it, or restore the page"
        for stub_path in found
        if stub_path != NOT_FOUND_NAME and stub_path not in set(expected)
    ]
    if NOT_FOUND_NAME not in found:
        problems.append(
            f"{NOT_FOUND_NAME}: absent from {stub_dir} -- every path with no stub of its"
            " own, the deleted non-HTML assets included, depends on that catch-all"
        )
    for stub_path in found:
        problems += _stub_problems(stub_dir / stub_path, stub_path)
    return problems


def _stub_problems(path: Path, stub_path: str) -> list[str]:
    text = path.read_text(encoding="utf-8")
    if stub_path == NOT_FOUND_NAME:
        return _not_found_problems(text)
    problems = [
        f"{stub_path}: names the target in no {description} -- the stub is incomplete"
        for marker, description in _CARRIERS
        if marker not in text
    ]
    expected = target_url(stub_path)
    named = set(_TARGET_RE.findall(text))
    if named != {expected}:
        problems.append(
            f"{stub_path}: should name {expected} and nothing else, but names"
            f" {sorted(named) or '(no MAM-basics URL at all)'} -- the target has to be"
            " the prefix rewrite of the stub's own path"
        )
    return problems


def _not_found_problems(text: str) -> list[str]:
    """The catch-all's own three requirements, which are not a per-page stub's four.

    It stands in for no one page, so it has neither a canonical link (it answers many
    paths, and each has its own current copy) nor a meta refresh (which takes a fixed URL,
    and the URL here is derived from the path that was asked for).  What it does need is
    the script, the visible link, and the incoming prefix it strips.
    """
    problems = [
        f"{NOT_FOUND_NAME}: names the new site in no {description} -- with that missing"
        " it forwards nothing"
        for marker, description in _CARRIERS
        if marker in ("location.replace(", "<a href=") and marker not in text
    ]
    if OLD_PATH_PREFIX not in text:
        problems.append(
            f"{NOT_FOUND_NAME}: does not name {OLD_PATH_PREFIX!r}, the prefix it has to"
            " strip off the incoming path before prepending the new site"
        )
    if NEW_SITE not in text:
        problems.append(
            f"{NOT_FOUND_NAME}: does not name {NEW_SITE}, so it has nowhere to send"
            " anyone"
        )
    return problems
