"""The CLC pilot index and redirects from its former HTML locations."""

import clc.clc_attribution as clc_attribution
import clc.clc_render as clc_render
from hkq_cmn.uxlc_external_links import book_display_name
from mb_cmn import paths
import uxlc_misc.uxlc_utils_html as H
import uxlc_paths

# Only these pages existed at the 2026-10-08 move. Future pages have no legacy URL.
_LEGACY_HTML_NAMES = (
    "Genesis.html",
    "Exodus-20.html",
    "Exodus-20-long-notes.html",
    "Deuter-5.html",
    "Deuter-5-long-notes.html",
    "2Samuel.html",
    "Proverbs.html",
)


def write_index(pages):
    """List the built pilot pages, including each available longer-notes page.

    Each page is (book_id, chapters, has_long_notes), supplied by the all build.
    """
    entries = []
    for book_id, chapters, has_long_notes in pages:
        label = clc_render.out_label(book_id, chapters)
        display = clc_render.disp_label(book_display_name(book_id), chapters)
        main_name = f"{label}.html"
        _require_page(main_name)
        entry = [H.anchor(display, {"href": main_name})]
        if has_long_notes:
            notes_name = f"{label}-long-notes.html"
            _require_page(notes_name)
            entry.extend([" — ", H.anchor("longer notes", {"href": notes_name})])
        entries.append(entry)
    if not entries:
        raise ValueError("The CLC index needs at least one reading page")
    body = [
        H.heading_level_1("Charitable Leningrad Codex (CLC)"),
        H.para(H.anchor("MAM-basics home", {"href": "../index.html"})),
        H.para("Available pages from the CLC pilot edition:"),
        H.unordered_list(entries),
        clc_attribution.top_credit(),
    ]
    out_path = uxlc_paths.clc_pages_dir() / "index.html"
    write_ctx = H.WriteCtx(title="Charitable Leningrad Codex (CLC)", path=out_path)
    H.write_html_to_file(body, write_ctx, "../uxlc/")
    return out_path


def _require_page(name):
    if not (uxlc_paths.clc_pages_dir() / name).is_file():
        raise FileNotFoundError(f"Missing CLC page: {name}")


def write_legacy_redirects():
    """Preserve the old reading and apparatus URLs, including verse fragments."""
    legacy_dir = paths.gh_pages_dir() / "uxlc" / "clc"
    legacy_dir.mkdir(parents=True, exist_ok=True)
    for name in _LEGACY_HTML_NAMES:
        _require_page(name)
        target = f"../../clc/{name}"
        text = f"""<!doctype html>
<!-- Generated by py/main_clc.py all. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>CLC page moved</title>
<link rel="canonical" href="{target}">
<meta http-equiv="refresh" content="0; url={target}">
<script>
location.replace("{target}" + location.search + location.hash);
</script>
</head>
<body>
<p>This CLC page has moved to <a href="{target}">{name}</a>.</p>
</body>
</html>
"""
        (legacy_dir / name).write_text(text, encoding="utf-8", newline="\n")
