# Initially generated by GitHub Copilot.
"""Mechanically apply ChangeOps to reconstruct text or structure.

Used by mpplus_verify to check that diff descriptions are complete:
if applying the ops to the old text/structure produces the new
text/structure (modulo normalization), the description is complete.

Exports:
    apply_text_ops       — apply text-level ops to produce reconstructed text
    apply_structural_ops — apply structural ops to produce reconstructed counter
"""

from collections import Counter

from mb_cmn.hebrew_punctuation import NU_GMAQ, PASOLEG
from mb_cmn.str_defs import DOUB_VERT_LINE
from mb_diff_mpu.change_ops import (
    ComplexReplace,
    GenericReplace,
    GenericTextReplace,
    GrayMaqafAdded,
    GrayMaqafRemoved,
    MarkAdded,
    MarkMoved,
    MarkRemoved,
    MarkReplaced,
    MarkReordered,
    PaseqAdded,
    PaseqRemoved,
    TemplateAdded,
    TemplateRemoved,
    TemplateRestructured,
    is_text_op,
)
from mb_diff_mpu.grapheme_diff import grapheme_clusters

# ── Grapheme cluster manipulation ────────────────────────────


def _is_letter(ch):
    return 0x05D0 <= ord(ch) <= 0x05EA


def _is_mark_or_accent(ch):
    cp = ord(ch)
    return (
        (0x0591 <= cp <= 0x05BD)
        or cp == 0x05BF
        or cp in (0x05C1, 0x05C2, 0x05C7)
        or cp == 0xFB1E
    )


def _split_cluster(cluster):
    """Split a grapheme cluster into (base, marks_list)."""
    if not cluster:
        return "", []
    return cluster[0], list(cluster[1:])


def _join_cluster(base, marks):
    """Rejoin a base character and its marks."""
    return base + "".join(marks)


def _find_letter_occurrence(clusters, letter, occurrence):
    """Find the cluster index for the Nth occurrence of *letter*."""
    seen = 0
    for i, cluster in enumerate(clusters):
        base, _ = _split_cluster(cluster)
        if base == letter:
            seen += 1
            if seen == occurrence:
                return i
    return None


# ── Text-level apply ─────────────────────────────────────────

_MARK_OPS = (
    MarkRemoved,
    MarkAdded,
    MarkMoved,
    MarkReplaced,
    GenericReplace,
    ComplexReplace,
    MarkReordered,
)


def _mark_edits(op):
    """Split a mark-level op into its removals and its placements.

    A removal is (letter, occurrence, mark).  A placement is (letter,
    occurrence, position, mark), *position* being the index the mark has
    among its cluster's marks in the new text.  MarkReplaced is a removal
    and a placement on one cluster, and MarkReordered takes its marks out
    and puts them back where the new text has them.
    """
    if isinstance(op, MarkRemoved):
        return [(op.on_letter, op.letter_occurrence, op.char)], []
    if isinstance(op, MarkAdded):
        return [], [(op.on_letter, op.letter_occurrence, op.position, op.char)]
    if isinstance(op, MarkMoved):
        return (
            [(op.from_letter, op.from_occurrence, op.char)],
            [(op.to_letter, op.to_occurrence, op.to_position, op.char)],
        )
    if isinstance(op, MarkReplaced):
        return (
            [(op.on_letter, op.letter_occurrence, op.old_char)],
            [(op.on_letter, op.letter_occurrence, op.new_position, op.new_char)],
        )
    if isinstance(op, GenericReplace):
        return (
            [(op.old_letter, op.old_occurrence, op.old_char)],
            [(op.new_letter, op.new_occurrence, op.new_position, op.new_char)],
        )
    if isinstance(op, ComplexReplace):
        return (
            [(letter, occ, mark) for mark, letter, occ in op.old_qualified],
            [
                (letter, occ, position, mark)
                for (mark, letter, occ), position in zip(
                    op.new_qualified, op.new_positions, strict=True
                )
            ],
        )
    if isinstance(op, MarkReordered):
        return (
            [(op.on_letter, op.letter_occurrence, mark) for mark in op.chars],
            [
                (op.on_letter, op.letter_occurrence, position, mark)
                for mark, position in zip(op.chars, op.new_positions, strict=True)
            ],
        )
    raise TypeError(f"not a mark-level op: {op!r}")


def _apply_mark_ops(clusters, ops):
    """Apply a run of consecutive mark-level ops as one edit.

    Every removal runs first, and then every placement, lowest position
    first.  That order is what lets a placement's position, an index in
    the new text's cluster, name the right place.  Once the removals have
    run, a cluster holds the marks no op touches, and when those marks
    have the same order in both texts they are exactly the new cluster's
    marks that no placement puts there.  Placing marks from the lowest
    position up then puts each one after every mark that precedes it in
    the new cluster.  So several ops on one cluster, a removal plus an
    addition or two additions, need no particular order among themselves.
    A cluster comes out wrong if its ops leave a change undescribed, or if
    its untouched marks change their order, which ops comparing one class
    of mark cannot say; either way the roundtrip verifier says so.
    """
    removals = []
    placements = []
    for op in ops:
        op_removals, op_placements = _mark_edits(op)
        removals.extend(op_removals)
        placements.extend(op_placements)
    for letter, occurrence, mark in removals:
        idx = _find_letter_occurrence(clusters, letter, occurrence)
        if idx is None:
            continue
        base, marks = _split_cluster(clusters[idx])
        if mark in marks:
            marks.remove(mark)
        clusters[idx] = _join_cluster(base, marks)
    for letter, occurrence, position, mark in sorted(placements, key=lambda p: p[2]):
        idx = _find_letter_occurrence(clusters, letter, occurrence)
        if idx is None:
            continue
        base, marks = _split_cluster(clusters[idx])
        marks.insert(position, mark)
        clusters[idx] = _join_cluster(base, marks)


def _apply_paseq_word_op(clusters, op, *, add):
    if op.on_word is None or op.word_occurrence is None:
        return False

    target_char = DOUB_VERT_LINE if op.paseq_type == "paseq" else PASOLEG
    words = "".join(clusters).split(" ")
    occurrence = 0
    for index, word in enumerate(words):
        base_word = word.replace(PASOLEG, "").replace(DOUB_VERT_LINE, "")
        if base_word != op.on_word:
            continue
        occurrence += 1
        if occurrence != op.word_occurrence:
            continue
        if add:
            words[index] = word + target_char
        else:
            words[index] = base_word
        clusters[:] = grapheme_clusters(" ".join(words))
        return True

    return False


def _apply_paseq_fragment_op(clusters, op):
    if op.old_fragment is None or op.new_fragment is None:
        return False

    text = "".join(clusters)
    replaced = text.replace(op.old_fragment, op.new_fragment, 1)
    if replaced == text:
        return False
    clusters[:] = grapheme_clusters(replaced)
    return True


def apply_text_ops(old_text, ops):
    """Apply text-level ChangeOps to *old_text* and return the result.

    This is the mechanical roundtrip: if the ops accurately describe the
    change, apply_text_ops(old, ops) should equal new (after normalization).
    """
    text_ops = [op for op in ops if is_text_op(op)]
    if not text_ops:
        return old_text

    # GenericTextReplace is a special case — it's a literal substitution
    # that passes trivially.
    if len(text_ops) == 1 and isinstance(text_ops[0], GenericTextReplace):
        op = text_ops[0]
        return old_text.replace(op.old_fragment, op.new_fragment, 1)

    # For mark-level ops, work on grapheme clusters
    clusters = grapheme_clusters(old_text)

    # A run of consecutive mark-level ops is one edit (_apply_mark_ops);
    # any other op ends the run.
    mark_run = []
    for op in text_ops:
        if isinstance(op, _MARK_OPS):
            mark_run.append(op)
            continue
        _apply_mark_ops(clusters, mark_run)
        mark_run = []
        if isinstance(op, GrayMaqafAdded):
            # A space becomes a gray maqaf (tilde) in flattened text
            for i, c in enumerate(clusters):
                if c == " ":
                    clusters[i] = NU_GMAQ
                    break
        elif isinstance(op, GrayMaqafRemoved):
            # A gray maqaf (tilde) is deleted — the words concatenate
            for i, c in enumerate(clusters):
                if c == NU_GMAQ:
                    del clusters[i]
                    break
        elif isinstance(op, PaseqAdded):
            # Insert the appropriate paseq-like character.
            # Legarmeh flattens to PASOLEG (U+05C0); paseq flattens to
            # DOUB_VERT_LINE.
            if _apply_paseq_word_op(clusters, op, add=True):
                continue
            if _apply_paseq_fragment_op(clusters, op):
                continue
            if op.paseq_type == "paseq":
                clusters.append(DOUB_VERT_LINE)
            else:
                clusters.append(PASOLEG)
        elif isinstance(op, PaseqRemoved):
            # Remove the first paseq-like character
            if _apply_paseq_word_op(clusters, op, add=False):
                continue
            if _apply_paseq_fragment_op(clusters, op):
                continue
            for i, c in enumerate(clusters):
                if c in (PASOLEG, DOUB_VERT_LINE, "\ufdd0", "\ufdd1"):
                    del clusters[i]
                    break
        elif isinstance(op, GenericTextReplace):
            # Literal substitution
            text = "".join(clusters)
            text = text.replace(op.old_fragment, op.new_fragment, 1)
            clusters = grapheme_clusters(text)
    _apply_mark_ops(clusters, mark_run)

    return "".join(clusters)


# ── Structural apply ─────────────────────────────────────────

# Sentinel indicating that any structure is acceptable (TemplateRestructured)
ANY_STRUCTURE = object()


def apply_structural_ops(old_ep_counter, ops):
    """Apply structural ChangeOps to a template-name counter.

    *old_ep_counter* is a Counter of template names from the old EP.
    Returns either a Counter (the expected new template-name counts) or
    ANY_STRUCTURE if a TemplateRestructured op was present.
    """
    result = Counter(old_ep_counter)
    for op in ops:
        if isinstance(op, TemplateAdded):
            result[op.name] += 1
        elif isinstance(op, TemplateRemoved):
            result[op.name] -= 1
            if result[op.name] <= 0:
                del result[op.name]
        elif isinstance(op, TemplateRestructured):
            return ANY_STRUCTURE
    return result
