# Initially generated by GitHub Copilot.
"""Copy Python example files from this repo to the MAM-parsed sibling repo."""

import os
import shutil

_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_PY_DIR = os.path.dirname(_MODULE_DIR)
_REPO_DIR = os.path.dirname(_PY_DIR)


def copy_support_files():
    """Copy files to the MAM-parsed repo."""
    mam_parsed_pyex = os.path.join(_REPO_DIR, MAM_PARSED_PYEX)
    if os.path.exists(mam_parsed_pyex):
        shutil.rmtree(mam_parsed_pyex)
    os.makedirs(mam_parsed_pyex)
    for pyfile_relpath in PYFILE_RELPATHS:
        src = os.path.join(_PY_DIR, pyfile_relpath)
        dst = f"{mam_parsed_pyex}/{pyfile_relpath}"
        shutil.copy(src, dst)


MAM_PARSED_PYEX = "../MAM-parsed/py-examples"
PYFILE_RELPATHS = ("./main_tmpl_survey_toy.py",)
