# Initially generated by GitHub Copilot.
"""Generate out/letter-small.txt from MAM-simple XML."""

import pathlib
import xml.etree.ElementTree as ET

_LETTER_SMALL_OUT_PATH = "out/letter-small.txt"
_MAM_SIMPLE_XML_DIR = "../MAM-simple/out/xml-vtrad-mam"


def write_letter_small_report():
    """Write all <letter-small> occurrences to the default output path."""
    write_letter_small_report_from_xml_dir(_MAM_SIMPLE_XML_DIR, _LETTER_SMALL_OUT_PATH)


def write_letter_small_report_from_xml_dir(xml_dir, out_path):
    """Write all <letter-small> occurrences by scanning all XML files in a dir."""
    lines = []
    for xml_path in sorted(pathlib.Path(xml_dir).glob("*.xml")):
        tree = ET.parse(xml_path)
        root = tree.getroot()
        for book39 in root:
            if book39.tag != "book39":
                continue
            for chapter in book39:
                if chapter.tag != "chapter":
                    continue
                for verse in chapter:
                    if verse.tag != "verse":
                        continue
                    book, ch, vr = verse.attrib["osisID"].split(".")
                    for el in verse.iter("letter-small"):
                        lines.append(
                            f"{book} {ch}:{vr}\t<small>{el.attrib['text']}</small>"
                        )
    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines))
        if lines:
            fp.write("\n")
    print(f"Wrote {len(lines)} lines to {out_path}")
