# Initially generated by GitHub Copilot.
"""Generate doc/vendoring-inventory.md from static rows plus live audit outputs."""

import ast
import json
import re
from pathlib import Path, PurePosixPath

from mb_cmn import paths
from mb_cmn import provenance as mb_provenance
from vendoring.discover import (
    IDENTITY_VALUES,
    ignored_repos,
    iter_inventory_seed_rows,
)

_REPO_ROOT = paths.repo_root()
_COMPARE_OUT = _REPO_ROOT / "out" / "vendoring_compare_out.txt"
_PROVENANCE_OUT = _REPO_ROOT / "out" / "vendoring_provenance_out.txt"
_PROVENANCE_OUT_JSON = _REPO_ROOT / "out" / "vendoring_provenance_out.json"
_GENERATOR_FILE = Path(__file__).resolve()
_INTENTIONALLY_NON_VENDORED_ROWS = [
    {
        "repo": "MAM-simple",
        "path": "py-examples/main_mam4sef_example.py",
        "notes": "Maintained directly in MAM-simple; not copied from MAM-basics.",
    },
    {
        "repo": "MAM-simple",
        "path": "py-examples/main_mam_osis_example.py",
        "notes": "Maintained directly in MAM-simple; not copied from MAM-basics.",
    },
    {
        "repo": "MAM-simple",
        "path": "py-examples/main_letter_small_job_example.py",
        "notes": "Maintained directly in MAM-simple; not copied from MAM-basics.",
    },
    {
        "repo": "MAM-parsed",
        "path": "py-examples/main_tmpl_survey_toy_example.py",
        "notes": "Maintained directly in MAM-parsed; not copied from MAM-basics.",
    },
]


def _make_source_path(src_pkg: str) -> str:
    if src_pkg == "mb_cmn":
        return ""
    return src_pkg


def _parse_compare_rows() -> dict[tuple[str, str, str], dict[str, str]]:
    rows: dict[tuple[str, str, str], dict[str, str]] = {}
    if not _COMPARE_OUT.exists():
        return rows

    # One space, not two.  compare.py writes fixed-width columns with a single
    # literal space between them, so a value that exactly fills its column is
    # separated from the next by that one space and nothing more.  Requiring two
    # made every such row unparseable, which is a crash rather than a wrong
    # answer: MAM-private's al-hatorah/py/mb_cmn/read_books_from_mam_parsed_plus.py
    # is 55 characters against a DEST_PATH column of 55 (compare.py:123,128).
    # Widening the column would only move the threshold.  One space is
    # unambiguous here because every field but the trailing notes is written
    # from a value that holds no whitespace.
    pattern = re.compile(
        r"^(?P<file>\S+)\s+"
        r"(?P<dest_repo>\S+)\s+"
        r"(?P<dest_path>\S+)\s+"
        r"(?P<identity>\S+)\s+"
        r"(?P<last_synced>\S+)"
        r"(?:\s+(?P<hint_notes>.*))?$"
    )

    for line in _COMPARE_OUT.read_text(encoding="utf-8").splitlines()[2:]:
        if not line.strip():
            continue
        match = pattern.match(line.rstrip())
        if not match:
            raise ValueError(f"Unparseable compare row: {line!r}")
        parsed = match.groupdict()
        key = (parsed["file"], parsed["dest_repo"], parsed["dest_path"])
        rows[key] = {
            "identity": parsed["identity"],
            "last_synced": parsed["last_synced"],
        }
    return rows


def _normalize_repo_relative_path(path: str) -> str:
    return path.replace("\\", "/").lstrip("./")


def _normalize_provenance_doc_path(repo: str, doc_path: str) -> str:
    normalized = _normalize_repo_relative_path(doc_path)
    repo_prefix = f"{repo}/"
    if normalized.startswith(repo_prefix):
        return normalized[len(repo_prefix) :]
    return normalized


def _parse_list_literal(raw_value: str) -> list[str]:
    parsed = ast.literal_eval(raw_value)
    if not isinstance(parsed, list) or not all(
        isinstance(item, str) for item in parsed
    ):
        raise ValueError(f"Expected list[str] literal, got: {raw_value!r}")
    return parsed


def _parse_provenance_rows_from_json() -> dict[str, dict[str, object]]:
    if not _PROVENANCE_OUT_JSON.exists():
        return {}

    data = json.loads(_PROVENANCE_OUT_JSON.read_text(encoding="utf-8"))
    repos_data = data.get("repos") if isinstance(data, dict) else data
    if not isinstance(repos_data, list):
        raise ValueError(
            "Expected vendoring_provenance_out.json to contain a list under 'repos'"
        )

    rows: dict[str, dict[str, object]] = {}
    for item in repos_data:
        if not isinstance(item, dict):
            raise ValueError(f"Expected repo entry to be an object, got: {item!r}")
        repo = item.get("repo")
        if not isinstance(repo, str) or not repo:
            raise ValueError(f"Missing/invalid repo in provenance JSON entry: {item!r}")

        raw_docs = item.get("found_provenance_docs", [])
        if not isinstance(raw_docs, list) or not all(
            isinstance(doc, str) for doc in raw_docs
        ):
            raise ValueError(
                f"Invalid found_provenance_docs for repo {repo}: {raw_docs!r}"
            )
        docs = sorted({_normalize_provenance_doc_path(repo, doc) for doc in raw_docs})

        rows[repo] = {"found_provenance_docs": docs}
    return rows


def _parse_provenance_rows_from_txt() -> dict[str, dict[str, object]]:
    rows: dict[str, dict[str, object]] = {}
    if not _PROVENANCE_OUT.exists():
        return rows

    current_repo = ""
    for raw_line in _PROVENANCE_OUT.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if line.startswith("=== ") and line.endswith(" ==="):
            current_repo = line[4:-4].strip()
            rows[current_repo] = {"found_provenance_docs": []}
            continue
        if not current_repo:
            continue

        if "PROVENANCE DOCS:" in line:
            _, _, docs_literal = line.partition("PROVENANCE DOCS:")
            docs = _parse_list_literal(docs_literal.strip())
            rows[current_repo]["found_provenance_docs"] = sorted(
                {_normalize_provenance_doc_path(current_repo, doc) for doc in docs}
            )
        elif "provenance docs: none" in line:
            rows[current_repo]["found_provenance_docs"] = []

    return rows


def _parse_provenance_rows() -> dict[str, dict[str, object]]:
    rows = _parse_provenance_rows_from_json()
    if rows:
        return rows
    return _parse_provenance_rows_from_txt()


def _dest_ancestor_dirs(dest_path: str) -> set[str]:
    ancestors: set[str] = set()
    current = PurePosixPath(dest_path)
    if current.suffix:
        current = current.parent
    while True:
        current_str = str(current)
        ancestors.add("." if current_str == "." else current_str)
        if current == PurePosixPath("."):
            break
        current = current.parent
    return ancestors


def _provenance_status_for_row(repo: str, dest_path: str, docs: list[str]) -> str:
    if not docs:
        return "no"
    ancestor_dirs = _dest_ancestor_dirs(dest_path)
    for doc in docs:
        doc_dir = str(PurePosixPath(doc).parent)
        if doc_dir in ancestor_dirs:
            return "yes"
    return "no"


def _merge_identity_into_notes(static_notes: str, identity: str) -> str:
    if not static_notes:
        return identity
    first_clause, sep, remainder = static_notes.partition(";")
    if first_clause in IDENTITY_VALUES:
        if sep:
            return f"{identity}; {remainder.strip()}"
        return identity
    return f"{identity}; {static_notes}"


def _merged_rows() -> list[dict[str, str]]:
    compare_rows = _parse_compare_rows()
    provenance_rows = _parse_provenance_rows()
    merged: list[dict[str, str]] = []

    for data in iter_inventory_seed_rows():
        compare_key = (data["file"], data["dest_repo"], data["dest_path"])
        compare_row = compare_rows.get(compare_key)
        provenance_row = provenance_rows.get(data["dest_repo"], {})
        found_provenance_docs = list(provenance_row.get("found_provenance_docs", []))

        if compare_row is not None:
            data["last_synced"] = compare_row["last_synced"]
            data["notes"] = _merge_identity_into_notes(
                data["notes"], compare_row["identity"]
            )
        data["provenance_doc"] = _provenance_status_for_row(
            data["dest_repo"], data["dest_path"], found_provenance_docs
        )
        merged.append(data)

    return merged


def _refresh_live_inputs() -> None:
    from vendoring import compare, provenance

    compare.main()
    provenance.main()


def main(refresh_live_inputs: bool = True) -> None:
    if refresh_live_inputs:
        _refresh_live_inputs()

    merged_rows = _merged_rows()
    ignored_repo_names = ignored_repos()
    groups: dict[tuple, list] = {}
    ignored_file_count = 0
    for d in merged_rows:
        dest_repo = d["dest_repo"]
        if dest_repo in ignored_repo_names:
            ignored_file_count += 1
            continue
        src_path = _make_source_path(d["src_pkg"])
        # The destination DIRECTORY is part of the key, not merely of the display.
        # A dest repo can hold the same source package in more than one directory,
        # and then those copies are two rows rather than one: MAM-private carries a
        # top-level directory per evacuated private repo, so mgketer/py/mb_cmn and
        # al-hatorah/py/mb_cmn are both mb_cmn copies of that one repo, arriving
        # 2026-08-08 and 2026-08-10. Keying without the directory grouped them
        # together and the row could then name only one of the two directories.
        dest_dir = d["dest_path"].rsplit("/", 1)[0]
        key = (
            src_path,
            dest_repo,
            dest_dir,
            d["mechanism"],
            d["provenance_doc"],
            d["category"],
            d["notes"],
        )
        groups.setdefault(key, []).append(d)

    sorted_groups = sorted(groups.items(), key=lambda kv: (kv[0][1], kv[0][2]))

    lines = [
        f"<!-- {mb_provenance.generated_html_comment(_GENERATOR_FILE)} -->",
        "",
        "# MAM-basics Vendoring Inventory",
        "",
        "Related issue: bdenckla/MAM-basics#60",
        "",
        "**Naming direction (2026-04-27):** Prefer `mb_cmn` (a directory) or an `mb_` prefix",
        "(for example `mb_diff_mpu`) at both source and destination. Legacy names may still appear below until migrations complete.",
        "",
        "**The `notes` column opens with the comparison verdict:** `identical` is byte-identical to the MAM-basics source;",
        "`eol-only` is the same content with different line endings on disk (the latent-CRLF condition, not drift);",
        "`DIFFERS` is content drift; `MISSING-DEST` is a copy the policy names that is no longer there.",
        "",
        '**The `category` column answers "is this copy being kept up?"** and `mechanism` answers "by what?":',
        "`active` is kept up and known to be up to date; `generated` is written by a generator here rather than maintained",
        "in the destination; `stale` is measured and behind; `unmeasured` is a copy nobody has looked at, whose one exit is to measure it.",
        "",
        "| file(s) | src_pkg | dest_repo | dest_path | mechanism | last_synced | provenance_doc | category | notes |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    row_count = 0
    for (
        src_path,
        dest_repo,
        dest_dir,
        mechanism,
        provenance_doc,
        category,
        notes,
    ), group_rows in sorted_groups:
        row_count += 1
        files = [row["file"] for row in group_rows]
        files_str = ", ".join(sorted(files))
        src_pkg_display = src_path if src_path else "mb_cmn"
        # A one-file row names the file's whole path; a several-file row names the
        # directory they share, which the key now guarantees they do. The guard that
        # used to check that agreement here is gone with the reason for it.
        dest_path_display = (
            dest_dir if len(group_rows) > 1 else group_rows[0]["dest_path"]
        )
        last_synced_values = {row["last_synced"] for row in group_rows}
        last_synced_display = (
            next(iter(last_synced_values)) if len(last_synced_values) == 1 else "mixed"
        )
        lines.append(
            f"| {files_str} | {src_pkg_display} | {dest_repo} | {dest_path_display} | {mechanism} | {last_synced_display} | {provenance_doc} | {category} | {notes} |"
        )
    ignored_repos_sorted = ", ".join(sorted(ignored_repo_names))
    # The parenthetical names WHICH repos were ignored, so with none ignored it has
    # nothing to say and would render as a dangling "(dest_repos: )". Empty became
    # reachable on 2026-08-07, when the four ignored repos -- MAM-for-Acc,
    # MAM-for-CCAR, MAM-for-JPS and TMC -- were dropped from in/vendoring_policy.json
    # on being moved out of GitRepos into FrozenRepos.
    ignored_suffix = (
        f" (dest_repos: {ignored_repos_sorted})" if ignored_repos_sorted else ""
    )
    file_count = sum(len(v) for v in groups.values())
    lines += [
        "",
        f"*{row_count} rows, {file_count} files. {ignored_file_count} files ignored{ignored_suffix}.*",
        "",
        "## Intentionally non-vendored",
        "",
        "These Python files live outside MAM-basics and are intentionally maintained in their destination repos.",
        "",
        "| repo | path | notes |",
        "|---|---|---|",
    ]
    for row in _INTENTIONALLY_NON_VENDORED_ROWS:
        lines.append(f"| {row['repo']} | {row['path']} | {row['notes']} |")
    lines.append("")

    out_path = _REPO_ROOT / "doc" / "vendoring-inventory.md"
    # newline="\n": see the same note in vendoring/compare.py's writer.
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(
        f"Wrote {row_count} rows ({file_count} files,"
        f" {ignored_file_count} ignored{ignored_suffix}) to {out_path}"
    )
