# Initially generated by GitHub Copilot.
"""Check for vendoring provenance docs and copy scripts in destination repos.

Results written to out/vendoring_provenance_out.txt and
out/vendoring_provenance_out.json.
"""

import json
import sys
from pathlib import Path, PurePosixPath

from mb_cmn import paths
from vendoring.discover import (
    destination_repo_path,
    iter_inventory_seed_rows,
    mb_cmn_scan_roots,
    provenance_dest_repos,
)

_MAM = paths.repo_root()
_OUT_TXT = _MAM / "out" / "vendoring_provenance_out.txt"
_OUT_JSON = _MAM / "out" / "vendoring_provenance_out.json"

PROVENANCE_NAMES = [
    "VENDORING.md",
    "vendoring.md",
    "VENDORS.md",
    "vendors.md",
    "vendored-from.md",
    "provenance.md",
    "PROVENANCE.md",
    "shared-with.md",
    "shared-with-MAM-basics.md",
    "copied-from.md",
    "vendored.md",
]

COPY_SCRIPT_PATTERNS = [
    "*copy*py*",
    "*vendor*py*",
    "*sync*py*",
    "*update_mb_cmn*",
]

# Path fragments the rglob below must not descend into. An agent worktree under
# .claude/worktrees/ is a SECOND FULL CHECKOUT of the repo, so without this every
# copy script is found twice -- once at its real path and once at a worktree path
# that will stop existing the moment the worktree is cleaned up, in a file that is
# committed. Found on 2026-08-02 with holman-ketiv-qere's festive-shamir-dad9ec.
# .git is here for the same reason and __pycache__/.venv were already: what the
# repo TRACKS is the question, and rglob answers a different one.
# .novc joined them on 2026-08-09 for that same reason, having produced the same
# symptom in the same tracked file: it is the gitignored scratch directory Ben's
# repos all use, and MAM-private's held copy_mgketer.py, the throwaway that copied
# mgketer's tree in at R.1. That matched *copy*py* and was written into
# out/vendoring_provenance_out.txt as one of MAM-private's COPY SCRIPTS -- a path
# git does not track, will not keep, and that names no vendoring mechanism at all.
_SCAN_EXCLUDED_FRAGMENTS = ("__pycache__", ".venv", ".claude", ".git", ".novc")


def _to_repo_relative_posix(path: Path, repo_path: Path) -> str:
    return str(path.relative_to(repo_path)).replace("\\", "/")


def _candidate_scan_dirs_for_repo(repo: str) -> list[str]:
    """Return repo-relative directories to scan for provenance docs.

    Includes repo root (".") and parent directories of discovered vendored
    destination files for the repo, walking up to repo root for each path.
    """
    dirs: set[str] = {"."}
    for data in iter_inventory_seed_rows():
        if data["dest_repo"] != repo:
            continue
        dest_path = PurePosixPath(data["dest_path"])
        current = dest_path.parent if dest_path.suffix else dest_path
        while True:
            dirs.add(str(current))
            if current == PurePosixPath("."):
                break
            current = current.parent

    return sorted(dirs, key=lambda rel: (0 if rel == "." else 1, rel.count("/"), rel))


def _find_provenance_docs(repo: str, repo_path: Path) -> list[str]:
    found_docs: set[str] = set()
    for rel_dir in _candidate_scan_dirs_for_repo(repo):
        scan_dir = repo_path if rel_dir == "." else repo_path / rel_dir
        if not scan_dir.exists():
            continue
        for name in PROVENANCE_NAMES:
            path = scan_dir / name
            if path.exists() and path.is_file():
                found_docs.add(_to_repo_relative_posix(path, repo_path))
    return sorted(found_docs)


def _find_copy_scripts(repo_path: Path) -> list[str]:
    copy_scripts: set[str] = set()
    for pat in COPY_SCRIPT_PATTERNS:
        for hit in repo_path.rglob(pat):
            if not hit.is_file():
                continue
            rel_parts = hit.relative_to(repo_path).parts
            if any(fragment in rel_parts for fragment in _SCAN_EXCLUDED_FRAGMENTS):
                continue
            copy_scripts.add(_to_repo_relative_posix(hit, repo_path))
    return sorted(copy_scripts)


def _scan_repo(repo: str) -> dict[str, object]:
    repo_path = destination_repo_path(repo)
    scanned_dirs = _candidate_scan_dirs_for_repo(repo)
    found_docs = _find_provenance_docs(repo, repo_path)
    copy_scripts = _find_copy_scripts(repo_path)
    mb_cmn_dirs: list[dict[str, object]] = []

    for mb_cmn_rel in mb_cmn_scan_roots(repo):
        mb_cmn_path = repo_path / mb_cmn_rel
        if not mb_cmn_path.exists():
            continue
        files = sorted(
            p.name
            for p in mb_cmn_path.iterdir()
            if p.suffix == ".py" and p.name != "__init__.py"
        )
        mb_cmn_dirs.append({"path": mb_cmn_rel, "files": files})

    return {
        "repo": repo,
        "scanned_dirs": scanned_dirs,
        "found_provenance_docs": found_docs,
        "copy_scripts": copy_scripts,
        "mb_cmn_dirs": mb_cmn_dirs,
    }


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    repo_summaries = [_scan_repo(repo) for repo in provenance_dest_repos()]

    # newline="\n": see the same note in vendoring/compare.py's writer.
    with _OUT_TXT.open("w", encoding="utf-8", newline="\n") as f:
        for summary in repo_summaries:
            repo = str(summary["repo"])
            f.write(f"\n=== {repo} ===\n")

            # Check for provenance docs
            found_docs = list(summary["found_provenance_docs"])
            if found_docs:
                f.write(f"  PROVENANCE DOCS: {found_docs}\n")
            else:
                f.write("  provenance docs: none\n")

            # Check for copy/sync scripts
            copy_scripts = list(summary["copy_scripts"])
            if copy_scripts:
                f.write(f"  COPY SCRIPTS: {copy_scripts}\n")
            else:
                f.write("  copy scripts: none found\n")

            # List mb_cmn directory if present at top level or common paths
            for mb_cmn_dir in list(summary["mb_cmn_dirs"]):
                f.write(f"  mb_cmn dir ({mb_cmn_dir['path']}): {mb_cmn_dir['files']}\n")

    json_payload = {"repos": repo_summaries}
    with _OUT_JSON.open("w", encoding="utf-8", newline="\n") as f:
        json.dump(json_payload, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Wrote to {_OUT_TXT}")
    print(f"Wrote to {_OUT_JSON}")
