# Initially generated by GitHub Copilot.
"""Generate the process pipeline graph from structured pipeline data."""

from tmpl_survey import survey_dot
from mb_cmn import graphviz_pin
from mb_cmn import provenance

from pipeline_graph import pipeline_graph_spec as spec

_OUT_DOT_PATH = "doc/process-documentation/pipeline.dot"
_OUT_SVG_PATH = "doc/process-documentation/pipeline.svg"


def _validate_spec():
    ids = [node.node_id for node in (*spec.STORE_NODES, *spec.PROGRAM_NODES)]
    assert len(ids) == len(set(ids)), ids
    for edge in spec.EDGES:
        assert edge.source_id in ids, edge.source_id
        assert edge.target_id in ids, edge.target_id
    assert len(spec.EDGES) == len(set(spec.EDGES)), spec.EDGES


def _quote_dot(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def _attrs_text(attrs):
    if not attrs:
        return ""
    parts = []
    for key, value in attrs:
        if value in {"solid", "dashed"}:
            parts.append(f"{key}={value}")
            continue
        parts.append(f"{key}={_quote_dot(value)}")
    return " [" + ", ".join(parts) + "]"


def _node_line(node, width):
    return f"    {node.node_id:<{width}}{_attrs_text((('label', node.label),))};"


def render_dot_text(generator_file=None):
    _validate_spec()
    all_nodes = (*spec.STORE_NODES, *spec.PROGRAM_NODES)
    node_width = max(len(node.node_id) for node in all_nodes) + 1
    generated_by = None
    if generator_file is not None:
        generated_by = provenance.generated_by_text(generator_file)
    lines = [
        "digraph mam_pipeline {",
    ]
    if generated_by is not None:
        lines.extend(
            [
                f"    // {generated_by}",
                "    // Do not edit by hand; edit py/pipeline_graph/pipeline_graph_spec.py instead.",
                f"    graph [comment={_quote_dot(generated_by)}];",
            ]
        )
    else:
        lines.append(
            "    // Do not edit this file by hand; edit py/pipeline_graph/pipeline_graph_spec.py instead."
        )
    lines.extend(
        [
            "    // Generated from structured pipeline data.",
            "    rankdir=LR;",
            f'    graph [fontname="{graphviz_pin.FONTNAME}", fontsize=10,'
            f" labelloc=b, labeljust=l, label={_quote_dot(spec.LEGEND)}];",
            f'    node [fontname="{graphviz_pin.FONTNAME}", fontsize=10];',
            f'    edge [fontname="{graphviz_pin.FONTNAME}", fontsize=9];',
            "",
            "    // ── Data stores ──",
            "    node [shape=cylinder];",
        ]
    )
    for node in spec.STORE_NODES:
        lines.append(_node_line(node, node_width))
    lines.extend(
        [
            "",
            "    // ── Programs run by hand (not steps of py/main_0_mega.py) ──",
            "    node [shape=box, style=dashed, color=gray, fontcolor=gray];",
        ]
    )
    for node in spec.PROGRAM_NODES:
        if not node.step_ids:
            lines.append(_node_line(node, node_width))
    lines.extend(
        [
            "",
            "    // ── Programs that steps of py/main_0_mega.py run ──",
            '    node [shape=box, style="", color="", fontcolor=""];',
        ]
    )
    for node in spec.PROGRAM_NODES:
        if node.step_ids:
            lines.append(_node_line(node, node_width))
    lines.extend(["", "    // ── Edges ──"])
    for edge in spec.EDGES:
        attrs = (("tooltip", edge.tooltip),) if edge.tooltip else ()
        edge_text = f"    {edge.source_id:<{node_width}}-> {edge.target_id}"
        lines.append(f"{edge_text}{_attrs_text(attrs)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_dot_file(dot_path=_OUT_DOT_PATH, generator_file=None):
    with open(dot_path, "w", encoding="utf-8", newline="") as out_file:
        out_file.write(render_dot_text(generator_file=generator_file))


def render_svg(dot_path=_OUT_DOT_PATH, svg_path=_OUT_SVG_PATH, generator_file=None):
    # survey_dot.render_svg raises on a missing or unpinned Graphviz as of
    # 2026-09-09, so the "if not rendered" guard that stood here is gone rather
    # than kept as unreachable code. This function was the ONLY caller that
    # checked that flag; the two call-graph writers discarded it and rendered
    # nothing in silence, which is why the flag became an exception.
    survey_dot.render_svg(dot_path, svg_path, generator_file=generator_file)


def write_pipeline_files(
    dot_path=_OUT_DOT_PATH, svg_path=_OUT_SVG_PATH, generator_file=None
):
    write_dot_file(dot_path, generator_file=generator_file)
    render_svg(dot_path, svg_path, generator_file=generator_file)
