# Initially generated by Claude Code.
"""Resolve the codex-index-aleppo DATA root, and the places its CODE now sits.

THIS MODULE IS DELIBERATELY TWO-ROOTED, and that is the whole point of its
existence.  The code is here in MAM-basics since Phase 3 of
``doc/PLAN-evacuate-python-from-codex-index-trio.md``, 2026-08-22; the data it reads
and writes stayed in the sibling codex-index-aleppo and goes on being hosted there
indefinitely, along with the three pages that repo serves, per Ben's decision of
2026-08-22 recorded in that plan's section "This plan moves the Python and nothing
else".

  * the CODE root is ``mb_cmn.paths.repo_root()`` -- what ``py/`` is under, what
    ``git`` acts on, and what ``code_paths()`` below carves this repo's share of;
  * the DATA root is ``ac_data_root()`` -- the twelve trees and loose files named
    in the accessors below.

Both roots were inside codex-index-aleppo until the move, and every module there
reached the second by walking up from ``__file__`` to the first.  One expression
standing for two roots is what Phase 1 of the same plan ended, so that this phase
had one function body to change rather than nineteen walks to find.

WHAT THIS DID NOT HAVE TO FIX.  Unlike book-of-job and codex-index-cam1753, no
module under ``py/`` addressed its data by a cwd-relative literal: the tree was
already cwd-independent, and only the conflation was left.  The two cwd-relative
sites this repo did have are both in ``aleppo-wiki/`` -- the entry point's four
dead ``"aleppo/..."`` literals, repointed in the same phase, and the uncalled
``mam_book_names.mam_book_path``.

WHAT IS NOT ROUTED THROUGH HERE, and why each is deliberate:

  * ``py_ac_word_image_helper/codex_page.py`` and ``flat_index.py`` compose
    ``line-breaks``, ``column-coordinates``, ``aleppo-pages`` and
    ``index-flat-annotated.json`` off roots of their own.  Both files are ONE
    COMMITTED BLOB with MAM-basics' ``py/py_ac_word_image_helper/`` copy, which
    arrived there with book-of-job in 2026-08-19, and editing either here alone
    re-forks the family the programme's Phase 0 reconciled.  Phase 0 of the trio's
    plan settles them: ``codex_page.py``'s root is a ``.git`` walk and is already
    right in both repos; ``flat_index.py``'s ``parent.parent.parent`` is right in
    both repos too and names a file only this one has.  They move at Phase 3, and
    they move together.
  * ``check_mark_order.py``, ``check_escape_sequences.py``, ``fix_mark_order.py``
    and ``fix_escape_sequences.py`` lint SOURCE, so their root is the code root,
    not this one.  All four walk up to ``.git`` already, are one committed blob
    with codex-index-cam1753's copies, and become a hand-maintained scope list at
    Phase 3 the way ``MAM-basics/py/boj_paths.py``'s ``code_paths()`` did.
  * ``py/mb_cmn/`` is vendored from MAM-basics and composes no path.
  * ``py/tests/test_h_dot_below_nfc.py``'s ``"gh-pages/"`` and its five neighbours
    are entries of ``_EXCLUDE_DIR_PREFIXES``, repo-relative prefixes matched against
    an already-scanned path.  Nothing builds a path from them; rewriting one would
    be a bug.  That module finds its own root with ``git rev-parse``.
"""

from pathlib import Path

from mb_cmn import paths

DATA_REPO_NAME = "codex-index-aleppo"
"""The sibling repo that kept the data when the Python left it."""

AC_PACKAGES = ("py_ac_loc", "ac_wiki")
"""The two packages codex-index-aleppo's code landed in under this repo's ``py/``.

``py_ac_loc`` kept its name; ``ac_wiki`` was ``aleppo-wiki/py/``, which could not
keep a name it never had -- a directory called ``py`` inside a data directory,
importable as ``py.<module>`` only because that repo was entered two ways.
``py_ac_word_image_helper`` is NOT listed: it arrived here with book-of-job on
2026-08-19 and is one committed blob with codex-index-aleppo's copy, so it belongs
to ``boj_paths.BOJ_PACKAGES``, which lists it, and listing it twice would lint it
twice.
"""

AC_TOP_LEVEL_MODULES = (
    "ac_paths.py",
    "check_ac_all.py",
    "check_ac_word_finding.py",
    "main_ac_check_line_breaks.py",
    "main_ac_download_pages.py",
    "main_ac_find_word_in_images.py",
    "main_ac_gen_col_quad_editor.py",
    "main_ac_gen_flat_stream.py",
    "main_ac_gen_index_flat_annotated.py",
    "main_ac_gen_lb_flat_stream.py",
    "main_ac_gen_line_break_editor.py",
    "main_ac_kraken_seg_baselines.py",
    "main_ac_merge_line_markers.py",
    "main_ac_plot_col_coords.py",
    "main_ac_wikisource_page.py",
)
"""codex-index-aleppo's fifteen modules at the top of this repo's ``py/``.

EVERY ONE IS PREFIXED, and the prefix is mechanical: ``main_ac_`` plus the module
stem for an entry point, ``check_ac_`` plus the stem for a check.  Five of the
fifteen had to be renamed because MAM-basics already held the name -- the four
source lints and ``check_all.py``, which is book-of-job's by Ben's decision of
2026-08-19 that ``check_all`` stays per-repo -- and the rest were renamed for the
same reason ahead of time: codex-index-cam1753 holds a counterpart of six of them,
against the same manuscript problem on a different manuscript, and its Phase 3 lands
them as ``main_cam1753_`` plus the same stems.

``main_gen_permission_glob.py`` is not in that list, and was not while it existed: it
moved with this code without belonging to it, generating a Claude Code permission glob
from a shell command and mentioning no manuscript, so it landed unprefixed at the top of
``py/`` as a utility of this repo's rather than inside this per-repo lint scope.  Ben
deleted it on 2026-08-24, once Claude's Auto mode had made the permission globs it wrote
pointless.  It is named here because the trio plan counts it among the files that moved,
so a reader comparing the two would otherwise be a file short.
"""

CODE_DIR = Path(__file__).resolve().parent
"""This repo's ``py/`` -- the directory this module and the code that imports it
sit in.

Spelled off ``__file__`` rather than off ``ac_data_root() / "py"`` so that it stayed
right when the code moved out from under the data, which is what Phase 3 then did.
"""


def ac_data_root() -> Path:
    """Path to the codex-index-aleppo corpus this code reads and writes.

    The one function Phase 3 changed: it was ``CODE_DIR.parent`` while the code
    still sat in codex-index-aleppo.  Checked rather than merely composed, for the
    reason ``paths.require_sibling`` gives: an absent sibling is a misconfiguration
    whose fix the message can carry, and no CI here would catch a silent skip.
    """
    return paths.require_sibling(DATA_REPO_NAME, paths.sibling_repo(DATA_REPO_NAME))


def code_paths() -> list[Path]:
    """Every place codex-index-aleppo's Python lives here, for the source lints.

    Fails loudly on an entry that no longer exists, exactly as
    ``boj_paths.code_paths()`` does; only an unlisted ADDITION is silent, and this
    code is being evacuated rather than developed.  ``repo_scopes.code_paths()`` is
    what unions this with the other evacuated repos' lists.
    """
    named = [CODE_DIR / name for name in AC_PACKAGES]
    named += [CODE_DIR / name for name in AC_TOP_LEVEL_MODULES]
    missing = [p for p in named if not p.exists()]
    if missing:
        raise SystemExit(
            "ac_paths.code_paths: no longer present: "
            + ", ".join(str(p) for p in missing)
        )
    return named


def line_breaks_dir() -> Path:
    """Hand-annotated per-page word streams (35 tracked JSON), the human-in-the-loop
    output of ``py_ac_loc.gen_line_break_editor``."""
    return ac_data_root() / "line-breaks"


def col_coords_dir() -> Path:
    """Per-page column quadrilaterals (35 tracked JSON), from
    ``py_ac_loc.gen_col_quad_editor``."""
    return ac_data_root() / "column-coordinates"


def pages_dir() -> Path:
    """Aleppo Codex page scans (37 tracked JPEG), leaves 270-281 recto and verso.

    DOWNLOADED, not generated: ``download_aleppo_pages`` fetches them from
    archive.org, and no check regenerates them.
    """
    return ac_data_root() / "aleppo-pages"


def mam_xml_dir() -> Path:
    """Vendored MAM-XML snapshot (24 tracked XML), the word-sequence ground truth --
    see ``doc/reading-mam-simple.md``."""
    return ac_data_root() / "MAM-XML"


def ds_flat_stream_dir() -> Path:
    """Derived per-page flat streams (8 tracked JSON) from
    ``py_ac_loc.gen_flat_stream``."""
    return ac_data_root() / "ds-flat-stream"


def plot_col_coords_out_dir() -> Path:
    """The three tracked PNGs ``py_ac_loc.plot_col_coords`` keeps, as against the
    throwaway copies it also writes into ``novc_dir()``."""
    return ac_data_root() / "plot_col_coords-out"


def novc_dir() -> Path:
    """Gitignored scratch tree, where the two editors and the word previewer write
    the HTML they open in a browser."""
    return ac_data_root() / ".novc"


def wiki_dir() -> Path:
    """``aleppo-wiki/`` -- J David Stark's index, its three derived artifacts, and the
    hand-corrected ``index-flat-corrected.json`` that
    ``main_ac_gen_index_flat_annotated`` reads.

    Its own pipeline addressed it off ``__file__`` until Phase 3, that code having sat
    inside this directory; now that the code is in MAM-basics and the data is not,
    this accessor serves both, which is what Phase 3 item 2 of the plan asked for --
    no fourth spelling of the data root.
    """
    return ac_data_root() / "aleppo-wiki"


def wiki_index_csv_path() -> Path:
    """``aleppo-wiki/J David Stark Aleppo Codex Index.csv``, the wikisource
    pipeline's one input.

    Hand-made and written by no program: J David Stark's index of the Aleppo Codex,
    under the licence in ``LICENSE.txt`` beside it.
    """
    return wiki_dir() / "J David Stark Aleppo Codex Index.csv"


def wiki_index_flat_path() -> Path:
    """``aleppo-wiki/index-flat.json``, the pipeline's first artifact: the CSV's rows
    as JSON.

    Distinct from ``flat_index_corrected_path()``, which is this file with
    corrections applied by hand and is the annotator's input rather than this
    pipeline's output.
    """
    return wiki_dir() / "index-flat.json"


def wiki_index_grouped_path() -> Path:
    """``aleppo-wiki/index-grouped-by-book.json``, the pipeline's second artifact:
    those rows grouped by book."""
    return wiki_dir() / "index-grouped-by-book.json"


def wiki_index_wikitext_path() -> Path:
    """``aleppo-wiki/index.wiki``, the pipeline's third artifact and its point -- the
    wikitext of the Wikisource page."""
    return wiki_dir() / "index.wiki"


def flat_index_corrected_path() -> Path:
    """Hand-corrected flat index (``<wiki_dir>/index-flat-corrected.json``).

    Written by no program: it is ``index-flat.json`` with corrections applied by
    hand, and it is the input to ``gen_index_flat_annotated``.
    """
    return wiki_dir() / "index-flat-corrected.json"


def flat_index_annotated_path() -> Path:
    """Annotated flat index (``<data_root>/index-flat-annotated.json``), written by
    ``gen_index_flat_annotated`` and read by ``py_ac_word_image_helper.flat_index``."""
    return ac_data_root() / "index-flat-annotated.json"


def check_line_breaks_html_path() -> Path:
    """The line-break check's HTML report (``<data_root>/check_line_breaks.html``),
    tracked, and rewritten by every run of ``py_ac_loc.check_line_breaks``."""
    return ac_data_root() / "check_line_breaks.html"


def word_finding_test_data_path() -> Path:
    """``<data_root>/test-data-from-book-of-job.json`` -- the minimal extract of
    book-of-job's enriched quirk records that ``check_word_finding`` runs against."""
    return ac_data_root() / "test-data-from-book-of-job.json"
