# Initially generated by Claude Code.
"""Resolve Cambridge 1753's data tree and the code that serves it.

``cam1753/`` holds the Cambridge Ms. Add. 1753 scans, annotations, generated
reports, and procedures. ``MAM-simple/xml-vtrad-mam/`` is the MAM-native XML
corpus the Cambridge 1753 reader uses as its word-sequence ground truth. The code
lives under this repository's ``py/`` directory.

TWO MODULES WERE CWD-RELATIVE OUTRIGHT, not merely conflated -- ``gutter_profile``
and ``split_spreads``, which between them named five of those trees and files as bare
relative strings and so ran from that repo's root and nowhere else.  Phase 1 spelled
them off this module; Phase 3 gave both a ``main()``, which they had never had.

WHAT IS NOT ROUTED THROUGH HERE, and why each is deliberate:

  * ``check_mark_order.py``, ``check_escape_sequences.py``, ``fix_mark_order.py``
    and ``fix_escape_sequences.py`` lint SOURCE, so their root is the code root, not
    this one.  They take their scope from ``repo_scopes``, which unions
    ``code_paths()`` below with the other evacuated repos' lists.
    codex-index-cam1753's own copies of all four are Phase 4 deletions.
  * ``mb_cmn/`` was vendored from this repo and composed no path; it is a Phase 4
    deletion too, all three files byte-identical.
  * ``py_ac_loc/mam_xml_verses.py`` takes the XML path as an argument and composes
    none.  It is codex-index-aleppo's module and ``py_cam1753_loc.gen_flat_stream``
    imports it: codex-index-cam1753's ``py_mam_xml/mam_xml_verses.py`` was the same
    tool with 32 lines of drift, reconciled onto that one at Phase 3 rather than
    landed as a second copy.  See ``py_cam1753_loc/gen_flat_stream.py`` for what the
    reconciliation turned on.

``py_cam1753_word_image/page.py`` WAS the fourth entry in that list and is not any
more.  It composed ``cam1753-line-breaks``, ``cam1753-col-quads`` and
``cam1753-pages`` off a ``parent.parent`` of its own -- right in
codex-index-cam1753, where the package sat at the repo root, and inert here, where
it named ``py/`` and all three directories are absent.  Phase 0 of the trio's plan
ruled it had to be settled in both repos at once or not at all, and Phase 3 is where
"at once" became possible: it now calls ``line_breaks_dir()``, ``col_quads_dir()``
and ``pages_dir()`` below.  That ends its one-blob relationship with
codex-index-cam1753's copy, deliberately, that copy being a Phase 4 deletion.
``py_ac_word_image_helper/codex_page.py`` was repaired the same way the day before,
and for the same reason.

WHAT NO PROGRAM HERE READS OR WRITES: ``cam1753-page-index.json``, the
hand-made verse-to-column index, cited only by ``page-snips/README.md`` and
``things-noticed-in-cam1753.md``; ``page-snips/`` (2 files); and the three
``doc/``.  They are named here so that Phase 4's inventory of artifacts with no
generator does not have to re-derive them.
"""

from pathlib import Path

from mb_cmn import paths

CAM_PACKAGES = ("py_cam1753_loc",)
"""The one package codex-index-cam1753's code landed in under this repo's ``py/``.

There was no package to keep: all fifteen of that repo's modules sat loose at its
root, beside the data.  ``py_cam1753_loc`` is named for ``py_ac_loc``, the tree
codex-index-aleppo already had for the same job on a different manuscript, and the
eight modules in it drop a now-redundant ``cam1753`` infix that the package name
carries -- ``gen_cam1753_flat_stream.py`` is ``py_cam1753_loc.gen_flat_stream``,
which is what makes ``main_cam1753_`` plus the module stem a rule rather than a
list.  Four of the eight are named for their ``py_ac_loc`` counterparts exactly:
``check_line_breaks``, ``gen_flat_stream``, ``gen_line_break_editor`` and
``gen_col_quad_editor``.

``py_cam1753_word_image`` is NOT listed: it arrived here with book-of-job on
2026-08-19 and is one committed blob with codex-index-cam1753's copy, so it belongs
to ``boj_paths.BOJ_PACKAGES``, which lists it, and listing it twice would lint it
twice.
"""

CAM_TOP_LEVEL_MODULES = (
    "cam1753_paths.py",
    "check_cam1753_all.py",
    "check_cam1753_word_finding.py",
    "main_cam1753_check_line_breaks.py",
    "main_cam1753_download_spreads.py",
    "main_cam1753_find_word_in_images.py",
    "main_cam1753_gen_col_quad_editor.py",
    "main_cam1753_gen_flat_stream.py",
    "main_cam1753_gen_line_break_editor.py",
    "main_cam1753_gutter_profile.py",
    "main_cam1753_split_spreads.py",
)
"""codex-index-cam1753's eleven modules at the top of this repo's ``py/``.

EVERY ONE IS PREFIXED, on the rule codex-index-aleppo's Phase 3 settled the day
before: ``main_cam1753_`` plus the module stem for an entry point,
``check_cam1753_`` plus the stem for a check.  Six of these have a
``main_ac_``-prefixed counterpart addressing the same problem on the Aleppo Codex,
which is exactly why that phase prefixed all fifteen of its own rather than only the
five whose names were taken.
"""

CODE_DIR = Path(__file__).resolve().parent
"""This repo's ``py/`` -- the directory this module and the code that imports it
sit in.

Spelled off ``__file__`` rather than off ``cam1753_data_root()`` so that it stayed
right when the code moved out from under the data, which is what Phase 3 then did.
"""


def cam1753_data_root() -> Path:
    """Path to the Cambridge 1753 corpus under this repository's root."""
    return paths.repo_root() / "cam1753"


def code_paths() -> list[Path]:
    """Every place codex-index-cam1753's Python lives here, for the source lints.

    Fails loudly on an entry that no longer exists, exactly as
    ``boj_paths.code_paths()`` and ``ac_paths.code_paths()`` do; only an unlisted
    ADDITION is silent, and this code is being evacuated rather than developed.
    ``repo_scopes.code_paths()`` is what unions this with the other evacuated repos'
    lists.
    """
    named = [CODE_DIR / name for name in CAM_PACKAGES]
    named += [CODE_DIR / name for name in CAM_TOP_LEVEL_MODULES]
    missing = [p for p in named if not p.exists()]
    if missing:
        raise SystemExit(
            "cam1753_paths.code_paths: no longer present: "
            + ", ".join(str(p) for p in missing)
        )
    return named


def line_breaks_dir() -> Path:
    """Hand-annotated per-page word streams (27 tracked JSON), the human-in-the-loop
    output of ``gen_cam1753_line_break_editor``."""
    return cam1753_data_root() / "cam1753-line-breaks"


def col_quads_dir() -> Path:
    """Per-page column quadrilaterals (28 tracked JSON), from
    ``gen_col_quad_editor``."""
    return cam1753_data_root() / "cam1753-col-quads"


def pages_dir() -> Path:
    """Derived single-page images, written from the tracked spreads.

    The directory is gitignored: rerun ``main_cam1753_split_spreads`` before a crop
    or editor task that needs its 28 JPEGs.
    """
    return cam1753_data_root() / "cam1753-pages"


def spreads_dir() -> Path:
    """Two-page spread scans (14 tracked JPEG).

    DOWNLOADED, not generated: ``download_cam1753_spreads`` fetches them from
    archive.org, and nothing in this repo calls that script.
    """
    return cam1753_data_root() / "cam1753-spreads"


def spread_splits_doc_dir() -> Path:
    """Per-spread split records (15 tracked JSON: 14 plus ``_all-splits.json``),
    written by ``split_cam1753_spreads`` so a split can be audited without re-running
    the gutter finder."""
    return cam1753_data_root() / "cam1753-spread-splits-doc"


def mam_xml_dir() -> Path:
    """MAM-simple's MAM-native XML, the word-sequence ground truth."""
    return paths.repo_root() / "MAM-simple" / "xml-vtrad-mam"


def gutter_profiles_png_path() -> Path:
    """The one tracked chart ``gutter_profile`` writes
    (``<data_root>/cam1753-gutter-profiles.png``)."""
    return cam1753_data_root() / "cam1753-gutter-profiles.png"


def check_line_breaks_html_path() -> Path:
    """The line-break check's HTML report (``<data_root>/check_line_breaks.html``),
    tracked, and rewritten by every run of ``check_line_breaks``."""
    return cam1753_data_root() / "check_line_breaks.html"


def word_finding_test_data_path() -> Path:
    """``<data_root>/test-data-from-book-of-job.json`` -- the minimal extract of
    book-of-job's enriched quirk records that ``check_word_finding`` runs against."""
    return cam1753_data_root() / "test-data-from-book-of-job.json"


def novc_dir() -> Path:
    """Gitignored scratch tree, where the two editors and the word previewer write
    the HTML they open in a browser."""
    return cam1753_data_root() / ".novc"
