# Initially generated by GitHub Copilot.
"""Dispatch diff and comparison tools.

Subcommands:
    ctr-vs-mam
                Compare CTR verse data against MAM verse data.
    mpp
                Compare MAM-parsed-plus revisions and generate HTML reports.
    wsgo
                Diff Wikisource against Google Sheets and emit auto-edits output.

Examples:
    .venv/Scripts/python.exe py/main_diff.py ctr-vs-mam
    .venv/Scripts/python.exe py/main_diff.py mpp --old <rev> --new <rev>
    .venv/Scripts/python.exe py/main_diff.py wsgo
"""

import argparse

from subcommands import diff_ctr_vs_mam
from subcommands import diff_mpp
from subcommands import diff_wsgo


def build_parser() -> argparse.ArgumentParser:
    """The fully-configured parser, so a test can read the subcommands off it."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="subcommand", metavar="SUBCOMMAND")
    subparsers.required = True
    _add_subcommands(subparsers)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


def _add_subcommands(subparsers) -> None:
    ctr_parser = subparsers.add_parser(
        "ctr-vs-mam",
        help="Compare CTR verse data against MAM verse data.",
    )
    ctr_parser.set_defaults(func=_run_ctr_vs_mam)

    mpp_parser = subparsers.add_parser(
        "mpp",
        help="Compare MAM-parsed-plus revisions and write HTML diff reports.",
    )
    diff_mpp.add_arguments(mpp_parser)
    mpp_parser.set_defaults(func=_run_mpp)

    wsgo_parser = subparsers.add_parser(
        "wsgo",
        help="Diff Wikisource versus Google Sheets and write auto-edits output.",
    )
    wsgo_parser.set_defaults(func=_run_wsgo)


def _run_ctr_vs_mam(_args: argparse.Namespace) -> None:
    diff_ctr_vs_mam.run()


def _run_mpp(args: argparse.Namespace) -> None:
    diff_mpp.run_from_args(args)


def _run_wsgo(_args: argparse.Namespace) -> None:
    diff_wsgo.run()


if __name__ == "__main__":
    main()
