# Initially generated by GitHub Copilot.
"""Generate doc/mp-claims.md — a human-readable index of all registered claims.

Each row shows: claim id, kind, subject, defined_in module, verifier function
name (or "pending" if none), and the verifier's docstring (or blank).

Usage (from repo root):

    .venv\\Scripts\\python.exe py\\main_gen_claims_doc.py

Writes doc/mp-claims.md. Does NOT require the corpus or survey artifact to be
present — it only loads the author modules to register claims and inspects the
verifier modules for matching function names.
"""

import sys

from verify_mp import registry_load
from verify_mp import driver as _driver
from verify_mp import verifiers_plus, verifiers_both

_OUT_PATH = "doc/mp-claims.md"

_VERIFIER_MODULES = (verifiers_plus, verifiers_both)


def _find_verifier_fn(claim_id: str):
    """Return the verifier function for claim_id, or None if pending."""
    fn_name = _driver.claim_id_to_fn_name(claim_id)
    for mod in _VERIFIER_MODULES:
        fn = getattr(mod, fn_name, None)
        if fn is not None:
            return fn
    return None


def _fn_docstring(fn) -> str:
    """Return first paragraph of fn's docstring, collapsed to one line."""
    doc = fn.__doc__ or ""
    first_para = doc.split("\n\n")[0]
    return " ".join(first_para.split())


def _subject_label(subject: str) -> str:
    return subject.replace("mp:", "mp:")  # keep as-is; readable already


def generate() -> str:
    """Return the full Markdown text for doc/mp-claims.md."""
    from author_util.claim import REGISTRY

    lines = [
        "<!-- Initially generated by GitHub Copilot. -->",
        "# MAM-parsed claims index",
        "",
        "Auto-generated by `py/main_gen_claims_doc.py`. Do not edit by hand.",
        "",
        "| Claim id | Kind | Subject | Defined in | Verifier | Verifier docstring |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for claim_id, record in sorted(REGISTRY.items()):
        fn = _find_verifier_fn(claim_id)
        if fn is not None:
            fn_name = fn.__name__
            docstring = _fn_docstring(fn)
        else:
            fn_name = "pending"
            docstring = ""

        # Escape pipe characters in any cell that might contain them
        def esc(s: str) -> str:
            return s.replace("|", "\\|")

        lines.append(
            f"| {esc(record.id)} "
            f"| {esc(record.kind)} "
            f"| {esc(record.subject)} "
            f"| {esc(record.defined_in)} "
            f"| {esc(fn_name)} "
            f"| {esc(docstring)} |"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    registry_load.populate()
    text = generate()
    with open(_OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {_OUT_PATH}")


if __name__ == "__main__":
    main()
