# Initially generated by GitHub Copilot.
"""Generate both graphs in doc/process-documentation/.

TWO GRAPHS, TWO PROVENANCES, AND ONLY ONE OF THE `.dot` FILES IS GENERATED.

  * `pipeline.dot` and `pipeline.svg` are generated here from the structured
    spec in `py/pipeline_graph/pipeline_graph_spec.py`. Both carry a
    "Do not edit by hand" line, and both mean it.
  * `MAM-process.dot` is HAND-AUTHORED and stays that way. Only its `.svg` is
    rendered here. Do not add a "do not edit by hand" line to that `.dot`, and
    do not translate it into a spec: it was written by hand in `d86e5779` and
    has never been edited since -- `git log --follow` on it shows two directory
    renames and nothing else -- and it carries hand-tuned layout (an invisible
    edge, a `rank=same` pair, a `rank=sink` caption node) that a spec would have
    to reproduce for no gain.

WHY THE SECOND ONE IS RENDERED HERE RATHER THAN BY HAND. Until 2026-09-09
`MAM-process.dot.svg` had no generator at all, so the only way to re-render it
was a hand `dot` invocation. That bypasses `graphviz_pin.check_installed`, which
is what refuses to write a file at the wrong Graphviz version, and it bypasses
the `CLAUDE_CODE_REMOTE` cloud skip. The file therefore sat at Graphviz
14.1.2 (20260124.0452) while every other tracked SVG here moved to 16.0.0,
and `a254d450` re-rendered it by hand that day rather than fixing the cause.
Routing it through `survey_dot.render_svg` is the fix: the pin is checked before
anything is written, a container skips the render instead of dying, and the
command to regenerate it is this file rather than a line in a test docstring.

Run it from the repo root -- both paths below are cwd-relative, as
`pipeline_graph.py`'s own output paths are:

  C:/Users/BenDe/GitRepos/MAM-basics/.venv/Scripts/python.exe py/main_pipeline_graph.py
"""

from pipeline_graph import pipeline_graph
from tmpl_survey import survey_dot

_PROCESS_DOT_PATH = "doc/process-documentation/MAM-process.dot"
_PROCESS_SVG_PATH = "doc/process-documentation/MAM-process.dot.svg"


def almost_main():
    """Write the pipeline graph's DOT and SVG, and render the process graph's SVG."""
    pipeline_graph.write_pipeline_files(generator_file=__file__)
    survey_dot.render_svg(_PROCESS_DOT_PATH, _PROCESS_SVG_PATH, generator_file=__file__)


def main():
    """Write both of doc/process-documentation/'s graphs."""
    almost_main()


if __name__ == "__main__":
    main()
