# Initially generated by GitHub Copilot.
"""Dispatch download tools.

Subcommands:
    fr-google
                Download MAM data from Google Sheets.
    fr-sefaria
                Download MAM CSVs from Sefaria.
    fr-wikisource
                Download MAM JSON from Hebrew Wikisource.
    fr-ws-intro
                Download the MAM introduction from Hebrew Wikisource.

fr-ws-intro is deliberately separate from fr-wikisource rather than a step of it: the
books and the introduction have unrelated refresh rhythms, nothing downstream reparses
when the introduction moves, and a chapter-scoped fr-wikisource run should not pay for
1.8 MB of introduction.  Ben's decision, 2026-08-31.

Examples:
    .venv/Scripts/python.exe py/main_download.py fr-google
    .venv/Scripts/python.exe py/main_download.py fr-google --section Torah
    .venv/Scripts/python.exe py/main_download.py fr-sefaria --book39 1Kings
    .venv/Scripts/python.exe py/main_download.py fr-wikisource --book39 Joshua --chapter 11
    .venv/Scripts/python.exe py/main_download.py fr-ws-intro
"""

import argparse

from mb_cmn import bib_locales as tbn
from subcommands import download_google
from subcommands import download_sefaria
from subcommands import download_wikisource
from subcommands import download_wikisource_intro
from ws import ws_download_selector as wsds


def build_parser() -> argparse.ArgumentParser:
    """The fully-configured parser, so a test can read the subcommands off it."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="subcommand", metavar="SUBCOMMAND")
    subparsers.required = True
    _add_subcommands(subparsers)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


def _add_subcommands(subparsers) -> None:
    google_parser = subparsers.add_parser(
        "fr-google",
        help="Download MAM data from Google Sheets and optionally parse it.",
    )
    google_parser.add_argument(
        "--section",
        choices=tbn.ALL_SECIDS,
        help="Download only the named section instead of all sections",
    )
    google_parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Skip downloading; just parse and check existing CSVs",
    )
    google_parser.add_argument(
        "--download-only",
        action="store_true",
        help="Download requested CSVs and exit without parsing or checking",
    )
    google_parser.set_defaults(func=_run_google)

    sefaria_parser = subparsers.add_parser(
        "fr-sefaria",
        help="Download MAM CSVs from Sefaria.",
    )
    sefaria_mutex = sefaria_parser.add_mutually_exclusive_group()
    sefaria_mutex.add_argument("--book39")
    sefaria_mutex.add_argument("--section6")
    sefaria_parser.set_defaults(func=_run_sefaria)

    ws_parser = subparsers.add_parser(
        "fr-wikisource",
        help="Download MAM chapters from Hebrew Wikisource and reparse affected books.",
    )
    wsds.add_selector_opts(ws_parser)
    ws_parser.set_defaults(func=_run_wikisource)

    ws_intro_parser = subparsers.add_parser(
        "fr-ws-intro",
        help="Download the MAM introduction from Hebrew Wikisource.",
    )
    ws_intro_parser.set_defaults(func=_run_wikisource_intro)


def _bkids_from_args(args):
    if getattr(args, "book39", None):
        return (args.book39,)
    if getattr(args, "section6", None):
        return tbn.bk39s_of_sec(args.section6)
    return tbn.ALL_BK39_IDS


def _run_google(args: argparse.Namespace) -> None:
    download_google.run(
        section=args.section,
        skip_download=args.skip_download,
        download_only=args.download_only,
    )


def _run_sefaria(args: argparse.Namespace) -> None:
    download_sefaria.run(_bkids_from_args(args))


def _run_wikisource(args: argparse.Namespace) -> None:
    download_wikisource.run_from_args(args)


def _run_wikisource_intro(args: argparse.Namespace) -> None:
    download_wikisource_intro.run_from_args(args)


if __name__ == "__main__":
    main()
