# Initially generated by GitHub Copilot.
"""Run routine downstream rebuilds after refreshing UXLC inputs.

This is the UXLC-utils pipeline, not the tree-wide one: it rebuilds the derived
output under the sibling UXLC-utils' ``out/``, ``gh-pages/`` and ``data/``, which
is where those five steps write (see ``uxlc_paths``).  It was that repo's own
``py/main_0_mega.py`` before the Python moved here, and is named
``main_uxlc_mega.py`` so it neither collides with nor impersonates this repo's
``py/main_0_mega.py``.

Each step is imported and called in-process rather than run as a child process,
so a step's own ``main()`` -- including the ``sys.std*.reconfigure`` at the top of
each -- runs exactly as it would if the step were invoked directly.
"""

import sys

import main_amb_early_mtg
import main_fois
import main_uxlc_check_changes
import main_uxlc_word_list
import main_write_page_break_info

_STEPS = [
    main_uxlc_check_changes,
    main_fois,
    main_write_page_break_info,
    main_amb_early_mtg,
    main_uxlc_word_list,
]


def main():
    """Run derived-output rebuilds that depend on refreshed UXLC inputs."""
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
    for mod in _STEPS:
        print(f"{__name__} {mod.__name__}")
        mod.main()


if __name__ == "__main__":
    main()
