"""Build or check the local near-Aleppo dataset, census and example edition.

All inputs and outputs live in this checkout. No private repository, comparison
tree, scan archive, or adoption handoff is a runtime dependency.

Run without flags to regenerate census, dataset and HTML in that order.
Use --check to compare all products without writing, or select one step with
--census, --build or --html. --check-note-review verifies every changed-note
presentation against a fresh enumeration of MAM's notes.
"""

import argparse
import importlib
import subprocess
import sys

from near_aleppo import build_paths
from near_aleppo import main_build
from near_aleppo import main_html_pages

_INSTRUMENTS = (
    "template_inventory",
    "qamats_params",
    "divine_name_split",
    "adonai_census",
    "stress_helper_census",
)


def _census(check):
    """Gather all five results before writing any baseline or provenance."""
    from near_aleppo import build_expectations

    input_dir = build_paths.mam_parsed_plus_dir()
    current = build_expectations.current_census_input_ids(
        input_dir, check_provenance=check
    )
    outputs = {}
    for name in _INSTRUMENTS:
        result = subprocess.run(
            [sys.executable, __file__, "--instrument", name],
            capture_output=True,
            check=True,
        )
        # Census output is a text baseline with repository-standard LF endings.
        outputs[name + ".txt"] = result.stdout.replace(b"\r\n", b"\n")
    if current != build_expectations.current_census_input_ids(
        input_dir, check_provenance=check
    ):
        raise AssertionError("MAM inputs changed during the census")
    directory = build_paths.input_dir() / "census"
    if check:
        differences = [
            name
            for name, data in outputs.items()
            if (directory / name).read_bytes() != data
        ]
        if differences:
            raise AssertionError(f"Near-Aleppo census differs: {differences}")
        print("All five local MAM census baselines agree")
        return
    for name, data in outputs.items():
        (directory / name).write_bytes(data)
    provenance = (
        "# Near-Aleppo census provenance\n\n"
        "The five population baselines are checked or regenerated by "
        "`py/main_near_aleppo.py --census`. They read only repository-local "
        "MAM data and the Aleppo coverage index.\n\n"
        "Content identities of the clean tracked inputs:\n\n"
        + "\n".join(
            f"MAM-basics {rel}: {identity}" for rel, identity in current.items()
        )
        + "\n"
    )
    (directory / "provenance.md").write_text(provenance, encoding="utf-8", newline="\n")
    print("Regenerated five local MAM census baselines")


def almost_main(argv=None):
    sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description=__doc__)
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--census", action="store_true")
    selection.add_argument("--build", action="store_true")
    selection.add_argument("--html", action="store_true")
    selection.add_argument("--instrument", choices=_INSTRUMENTS, help=argparse.SUPPRESS)
    selection.add_argument("--check-note-review", action="store_true")
    selection.add_argument("--refresh-note-review", action="store_true")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare against tracked output; write nothing.",
    )
    parser.add_argument(
        "--refresh-expectations",
        action="store_true",
        help="Refresh only census-backed populations after a successful census.",
    )
    args = parser.parse_args(argv)
    if args.instrument:
        importlib.import_module("near_aleppo.census." + args.instrument).main()
        return 0
    if args.check_note_review or args.refresh_note_review:
        flag = (
            "--check-note-review" if args.check_note_review else "--refresh-note-review"
        )
        return main_html_pages.main([flag]) or 0
    selected = args.census or args.build or args.html
    check_args = ["--check"] if args.check else []
    if args.census or not selected:
        _census(args.check)
    if args.build or not selected:
        code = main_build.main(
            check_args
            + (["--refresh-expectations"] if args.refresh_expectations else [])
        )
        if code:
            return code
    if args.html or not selected:
        return main_html_pages.main(check_args) or 0
    return 0


if __name__ == "__main__":
    sys.exit(almost_main())
