# Initially generated by GitHub Copilot.
"""Find <letter-small> elements in Job and write a report."""

from mb_misc import letter_small_job

_XML_PATH = "../MAM-simple/xml-vtrad-mam/Job.xml"


def almost_main():
    """Find <letter-small> elements in Job."""
    letter_small_job.almost_main(_XML_PATH)


if __name__ == "__main__":
    almost_main()
