# Initially generated by GitHub Copilot.

import unittest

from subcommands import ws_bot_real as mod


class WsBotRealDiffLinksTests(unittest.TestCase):
    def test_diff_url_matches_expected_shape(self):
        url = mod._diff_url("שמואל ב יא/טעמים", 3009296, 3007998)

        self.assertEqual(
            url,
            "https://he.wikisource.org/w/index.php?"
            "title=%D7%A9%D7%9E%D7%95%D7%90%D7%9C%20%D7%91%20%D7%99%D7%90%2F"
            "%D7%98%D7%A2%D7%9E%D7%99%D7%9D&diff=3009296&oldid=3007998",
        )

    def test_markdown_for_modified_pages(self):
        markdown = mod._modified_chapter_diffs_markdown(
            [
                {
                    "title": "שמואל ב יא/טעמים",
                    "newrevid": 3009296,
                    "oldrevid": 3007998,
                },
                {
                    "title": "יחזקאל מז/טעמים",
                    "newrevid": 3009297,
                    "oldrevid": 3008029,
                },
            ]
        )

        self.assertIn(
            "- [שמואל ב יא/טעמים](https://he.wikisource.org/w/index.php?", markdown
        )
        self.assertIn("&diff=3009296&oldid=3007998)", markdown)
        self.assertIn(
            "- [יחזקאל מז/טעמים](https://he.wikisource.org/w/index.php?", markdown
        )
        self.assertIn("&diff=3009297&oldid=3008029)", markdown)

    def test_markdown_for_no_modified_pages(self):
        markdown = mod._modified_chapter_diffs_markdown([])

        self.assertEqual(markdown, "_No modified chapters in this run._\n")


if __name__ == "__main__":
    unittest.main()
