# Initially generated by GitHub Copilot.

import unittest

from pycmn import ws_tmpl2 as wtp
from pyfoi import foi_struct as fct
from pyfoi import foiz_wt_kq_1
from pyfoi import kq_trivial_types as ktt


def _trivial_tmpl(pointed_ketiv, unpointed_ketiv, pointed_qere):
    return wtp.mktmpl(
        [
            ['מ:קו"כ-אם-2'],
            [pointed_ketiv],
            [unpointed_ketiv],
            [pointed_qere],
        ],
        ignore_equals=True,
    )


def _std_kq_tmpl(pointed_ketiv, pointed_qere):
    return wtp.mktmpl([['כו"ק'], [pointed_ketiv], [pointed_qere]], ignore_equals=True)


class TrivialKqSubtypeClassifierTests(unittest.TestCase):
    def test_classify_xolam_he(self):
        tmpl = _trivial_tmpl("סוּתֹֽה", "סותה", "סוּתֽוֹ")

        self.assertEqual(ktt.classify_tmpl(tmpl), ktt.XOLAM_HE)

    def test_classify_qyv(self):
        tmpl = _trivial_tmpl("עֹֽלוֹתָ֔ו", "עלותו", "עֹֽלוֹתָ֔יו")

        self.assertEqual(ktt.classify_tmpl(tmpl), ktt.QYV)

    def test_leave_unmatched_blank(self):
        tmpl = _trivial_tmpl("סוּתֹֽה", "סותה", "סוּתִֽי")

        self.assertIsNone(ktt.classify_tmpl(tmpl))

    def test_subtype_for_path_uses_misc_for_unmatched(self):
        tmpl = _trivial_tmpl("סוּתֹֽה", "סותה", "סוּתִֽי")

        self.assertEqual(ktt.subtype_for_path(tmpl), ktt.MISC)


class TrivialKqFoiQualificationTests(unittest.TestCase):
    def test_record_kq_as_foi_uses_xolam_he_path_and_pqere(self):
        tmpl = _trivial_tmpl("סוּתֹֽה", "סותה", "סוּתֽוֹ")

        found = foiz_wt_kq_1._record_kq_as_foi(None, tuple(), tmpl)
        foi_path, foi_target = found[0]

        self.assertEqual(foi_path, ("kq-simple", "z-trivial", ktt.XOLAM_HE))
        self.assertEqual(fct.qtar_qual(foi_target), {"pqere": "סוּתֽוֹ"})

    def test_record_kq_as_foi_uses_misc_path_for_unmatched_trivial(self):
        tmpl = _trivial_tmpl("סוּתֹֽה", "סותה", "סוּתִֽי")

        found = foiz_wt_kq_1._record_kq_as_foi(None, tuple(), tmpl)
        foi_path, foi_target = found[0]

        self.assertEqual(foi_path, ("kq-simple", "z-trivial", ktt.MISC))
        self.assertEqual(fct.qtar_qual(foi_target), {"pqere": "סוּתִֽי"})

    def test_record_kq_as_foi_uses_qyv_path_and_pqere(self):
        tmpl = _trivial_tmpl("עֹֽלוֹתָ֔ו", "עלותו", "עֹֽלוֹתָ֔יו")

        found = foiz_wt_kq_1._record_kq_as_foi(None, tuple(), tmpl)
        foi_path, foi_target = found[0]

        self.assertEqual(foi_path, ("kq-simple", "z-trivial", ktt.QYV))
        self.assertEqual(fct.qtar_qual(foi_target), {"pqere": "עֹֽלוֹתָ֔יו"})

    def test_record_kq_as_foi_leaves_other_kq_templates_unchanged(self):
        tmpl = _std_kq_tmpl("עֹֽלוֹתָ֔ו", "עֹֽלוֹתָ֔יו")

        found = foiz_wt_kq_1._record_kq_as_foi(None, tuple(), tmpl)
        foi_path, foi_target = found[0]

        self.assertEqual(foi_path, ("kq-simple", "k1q1"))
        self.assertIsInstance(foi_target, tuple)


if __name__ == "__main__":
    unittest.main()
