"""Tests for the wlc-utils provenance wrapper (wlc-utils issue #34).

The wrapper binds wlc-utils' logical name (``wlc_paths.REPO_NAME``) so breadcrumbs on
the artifacts under wlc-utils' ``out/`` and ``gh-pages/`` read "wlc-utils/..." rather
than naming whatever checkout the generator sits in.  The repo-agnostic override
mechanism itself is unit-tested next door in ``test_mb_cmn_provenance.py``.

THE GENERATOR PATH IS A CODE-ROOT PATH, and that is what the assertions below turn on.
``main_accgram.py`` lives in this repo now; the artifacts it writes live in wlc-utils.
``mb_cmn.provenance._display_path`` reads the actual checkout name off its own location
and swaps in the logical name, so a generator at ``MAM-basics/py/main_accgram.py``
still yields the ``wlc-utils/py/main_accgram.py`` breadcrumb the committed artifacts
carry -- which is exactly what keeps byte-identical regeneration available as the
oracle for the move.  Phase 5 of ``doc/PLAN-evacuate-python-from-wlc-utils.md`` is
where that override is deliberately retired and these strings change.
"""

from __future__ import annotations

from mb_cmn import paths

import wlc_paths
import wlc_provenance


def test_wrapper_supplies_repo_name() -> None:
    assert wlc_paths.REPO_NAME == "wlc-utils"
    generator = paths.repo_root() / "py" / "main_accgram.py"
    assert "wlc-utils/py/main_accgram.py" in wlc_provenance.generated_by_text(
        str(generator)
    )


def test_wrapper_html_comment_and_json_use_repo_name() -> None:
    generator = paths.repo_root() / "py" / "main_accgram.py"
    assert "wlc-utils/py/main_accgram.py" in wlc_provenance.generated_html_comment(
        str(generator)
    )
    payload = wlc_provenance.with_json_provenance({"x": 1}, str(generator))
    assert payload["provenance"].startswith("This file was generated by wlc-utils/")
    assert payload["x"] == 1
