# Initially generated by GitHub Copilot.

import unittest

from tmpl_survey import nesting_normal_form as nnf


class TestTmplSurveyNestingNormalForm(unittest.TestCase):
    def test_regex_like_grammar_shape(self):
        self.assertEqual("a?b?c?d?e?f?", nnf.regex_like_grammar())

    def test_allows_nondecreasing_rank_order(self):
        stack_counts = {
            ("מ:אות-מיוחדת-במילה", "E/מ:כפול/נוסח/כו״ק/מ:קמץ/מ:דחי"): 2,
        }
        nnf.assert_stack_counts_in_normal_form(stack_counts, dataset_name="unit")

    def test_ignores_unranked_templates_between_ranked_templates(self):
        stack_counts = {
            ("מ:דחי", "E/מ:הערה-2/מ:קמץ"): 4,
        }
        nnf.assert_stack_counts_in_normal_form(stack_counts, dataset_name="unit")

    def test_rejects_descending_rank_transition(self):
        stack_counts = {
            ("מ:קמץ", "E/מ:דחי"): 3,
        }
        with self.assertRaises(AssertionError) as ctx:
            nnf.assert_stack_counts_in_normal_form(stack_counts, dataset_name="unit")
        self.assertIn("מ:דחי (rank 4) -> מ:קמץ (rank 3)", str(ctx.exception))

    def test_aggregates_violation_counts(self):
        stack_counts = {
            ("מ:קמץ", "E/מ:דחי"): 3,
            ("מ:קמץ", "D/נוסח/מ:דחי"): 5,
        }
        violations = nnf.find_rank_violations(stack_counts)
        self.assertEqual(1, len(violations))
        self.assertEqual("מ:דחי", violations[0]["caller"])
        self.assertEqual("מ:קמץ", violations[0]["callee"])
        self.assertEqual(8, violations[0]["count"])


if __name__ == "__main__":
    unittest.main()
