# Initially generated by GitHub Copilot.
import importlib
import unittest

import author_util.claim as claim_mod
from verify_mp import claims_doc, driver


class TestExplicitClaims(unittest.TestCase):
    def test_claim_collection_allows_identical_duplicate_emissions(self):
        claims = claim_mod.ClaimCollection()

        payload1 = claims.claim(
            "mp.plus.example.same-record",
            {"row": 1},
            kind="example",
            subject="mp:plus",
            data={"x": 1},
        )
        payload2 = claims.claim(
            "mp.plus.example.same-record",
            {"row": 2},
            kind="example",
            subject="mp:plus",
            data={"x": 1},
        )

        self.assertEqual(payload1, {"row": 1})
        self.assertEqual(payload2, {"row": 2})
        self.assertEqual(len(claims.records_by_id), 1)
        self.assertEqual(len(claims.emissions), 2)

    def test_claim_collection_rejects_conflicting_duplicate_id(self):
        claims = claim_mod.ClaimCollection()
        claims.claim(
            "mp.plus.example.conflict",
            "first",
            kind="example",
            subject="mp:plus",
            data={"x": 1},
        )

        with self.assertRaisesRegex(
            ValueError,
            r"conflicting duplicate claim id: 'mp\.plus\.example\.conflict'",
        ):
            claims.claim(
                "mp.plus.example.conflict",
                "second",
                kind="example",
                subject="mp:plus",
                data={"x": 2},
            )

    def test_legacy_global_registry_api_is_removed(self):
        self.assertFalse(hasattr(claim_mod, "REGISTRY"))
        self.assertFalse(hasattr(claim_mod, "claim"))

    def test_claims_doc_generate_uses_explicit_claims(self):
        claims = claim_mod.ClaimCollection()
        claims.claim(
            "mp.plus.verse.is-3-tuple",
            "Each verse is a 3-element array [C, D, E].",
            kind="struct",
            subject="mp:plus",
            data={"shape": ["sep", "label", "text"]},
        )

        text = claims_doc.generate(claims)

        self.assertIn("| mp.plus.verse.is-3-tuple |", text)
        self.assertIn("| verify_mp_plus_verse_is_3_tuple |", text)

    def test_build_verifiers_uses_explicit_claims(self):
        claims = claim_mod.ClaimCollection()
        claims.claim(
            "mp.plus.verse.is-3-tuple",
            "payload",
            kind="struct",
            subject="mp:plus",
        )

        verifiers = driver.build_verifiers(claims)

        self.assertIn("mp.plus.verse.is-3-tuple", verifiers)
        self.assertEqual(
            verifiers["mp.plus.verse.is-3-tuple"].__name__,
            "verify_mp_plus_verse_is_3_tuple",
        )

    def test_mpplus_aot_import_has_no_claim_side_effects(self):
        importlib.invalidate_caches()
        aot = importlib.import_module("author.mpplus_aot")

        self.assertFalse(hasattr(aot, "populate_claims"))

    def test_mpplus_aot_build_body_requires_explicit_claims(self):
        aot = importlib.import_module("author.mpplus_aot")

        with self.assertRaises(TypeError):
            aot._build_body()

    def test_mpplus_aot_populate_claims_requires_explicit_claims(self):
        aot = importlib.import_module("author.mpplus_aot")
        self.assertFalse(hasattr(aot, "populate_claims"))

    def test_mpplus_aot_build_body_can_emit_explicit_claim(self):
        aot = importlib.import_module("author.mpplus_aot")
        claims = claim_mod.ClaimCollection()

        aot._build_body(claims=claims)

        self.assertIn("mp.plus.templates.aot.arg5-derivable", claims.records_by_id)

    def test_mpplus_haarah_2_import_has_no_claim_side_effects(self):
        importlib.invalidate_caches()
        haarah_2 = importlib.import_module("author.mpplus_haarah_2")

        self.assertFalse(hasattr(haarah_2, "populate_claims"))

    def test_mpplus_haarah_2_build_body_has_no_implicit_claim_side_effects(self):
        haarah_2 = importlib.import_module("author.mpplus_haarah_2")
        claims = claim_mod.ClaimCollection()

        haarah_2._build_body(claims=claims)

    def test_mpplus_haarah_2_has_no_populate_claims_symbol(self):
        haarah_2 = importlib.import_module("author.mpplus_haarah_2")
        self.assertFalse(hasattr(haarah_2, "populate_claims"))

    def test_mpplus_haarah_2_build_body_can_emit_explicit_claim(self):
        haarah_2 = importlib.import_module("author.mpplus_haarah_2")
        claims = claim_mod.ClaimCollection()

        haarah_2._build_body(claims=claims)

        self.assertIn("mp.plus.example.haarah-2-context", claims.records_by_id)

    def test_mpplus_kaful_import_has_no_claim_side_effects(self):
        importlib.invalidate_caches()
        kaful = importlib.import_module("author.mpplus_kaful")

        self.assertFalse(hasattr(kaful, "populate_claims"))

    def test_mpplus_kaful_build_body_requires_explicit_claims(self):
        kaful = importlib.import_module("author.mpplus_kaful")

        with self.assertRaises(TypeError):
            kaful._build_body()

    def test_mpplus_kaful_build_body_can_emit_explicit_claim(self):
        kaful = importlib.import_module("author.mpplus_kaful")
        claims = claim_mod.ClaimCollection()

        kaful._build_body(claims=claims)

        self.assertIn("mp.plus.example.kaful-template-object", claims.records_by_id)

    def test_mpplain_import_has_no_claim_side_effects(self):
        importlib.invalidate_caches()
        mpplain = importlib.import_module("author.mpplain")

        self.assertFalse(hasattr(mpplain, "populate_claims"))

    def test_mpplain_build_body_has_no_implicit_claim_side_effects(self):
        mpplain = importlib.import_module("author.mpplain")
        claims = claim_mod.ClaimCollection()

        mpplain._build_body(claims=claims)

    def test_mpplain_has_no_populate_claims_symbol(self):
        mpplain = importlib.import_module("author.mpplain")
        self.assertFalse(hasattr(mpplain, "populate_claims"))

    def test_mpplain_build_body_can_emit_explicit_claims(self):
        mpplain = importlib.import_module("author.mpplain")
        claims = claim_mod.ClaimCollection()

        mpplain._build_body(claims=claims)

        self.assertIn("mp.plain.book39.fields", claims.records_by_id)


if __name__ == "__main__":
    unittest.main()
