# Initially generated by GitHub Copilot.

import unittest

from mb_cmn.he_wikisource_url import he_diff_url, he_page_url, he_taamim_url


class HeWikisourceUrlTests(unittest.TestCase):
    def test_he_page_url(self):
        self.assertEqual(
            he_page_url("מקרא_על_פי_המסורה"),
            "https://he.wikisource.org/wiki/"
            "%D7%9E%D7%A7%D7%A8%D7%90_%D7%A2%D7%9C_%D7%A4%D7%99_%D7%94%D7%9E%D7%A1%D7%95%D7%A8%D7%94",
        )

    def test_he_page_url_with_fragment(self):
        self.assertEqual(
            he_page_url("ויקיטקסט:מבוא_למקרא_על_פי_המסורה/פרק_ב", "הסבר קצר"),
            "https://he.wikisource.org/wiki/"
            "%D7%95%D7%99%D7%A7%D7%99%D7%98%D7%A7%D7%A1%D7%98:%D7%9E%D7%91%D7%95%D7%90_"
            "%D7%9C%D7%9E%D7%A7%D7%A8%D7%90_%D7%A2%D7%9C_%D7%A4%D7%99_%D7%94%D7%9E%D7%A1%D7%95%D7%A8%D7%94/"
            "%D7%A4%D7%A8%D7%A7_%D7%91#%D7%94%D7%A1%D7%91%D7%A8%20%D7%A7%D7%A6%D7%A8",
        )

    def test_he_taamim_url(self):
        self.assertEqual(
            he_taamim_url("ויקרא", "ב"),
            "https://he.wikisource.org/wiki/"
            "%D7%95%D7%99%D7%A7%D7%A8%D7%90_%D7%91/%D7%98%D7%A2%D7%9E%D7%99%D7%9D",
        )

    def test_he_diff_url(self):
        self.assertEqual(
            he_diff_url("שמואל ב יא/טעמים", 3009296, 3007998),
            "https://he.wikisource.org/w/index.php?"
            "title=%D7%A9%D7%9E%D7%95%D7%90%D7%9C%20%D7%91%20%D7%99%D7%90%2F"
            "%D7%98%D7%A2%D7%9E%D7%99%D7%9D&diff=3009296&oldid=3007998",
        )

    def test_he_diff_url_next_short_form(self):
        self.assertEqual(
            he_diff_url("יהושע כד/טעמים", "next", 3007998),
            "https://he.wikisource.org/w/index.php?"
            "title=%D7%99%D7%94%D7%95%D7%A9%D7%A2%20%D7%9B%D7%93%2F"
            "%D7%98%D7%A2%D7%9E%D7%99%D7%9D&diff=next&oldid=3007998",
        )


if __name__ == "__main__":
    unittest.main()
