# Initially generated by GitHub Copilot.

import unittest
from pathlib import Path

from mb_cmn import provenance


class TestMbCmnProvenance(unittest.TestCase):
    @staticmethod
    def _repo_name() -> str:
        return Path(__file__).resolve().parents[2].name

    def test_generated_by_text_prefixes_mam_basics(self):
        generator_path = Path(__file__).resolve()
        repo_root = generator_path.parents[2]
        rel = generator_path.relative_to(repo_root).as_posix()
        expected = f"This file was generated by {self._repo_name()}/{rel}."
        self.assertEqual(provenance.generated_by_text(str(generator_path)), expected)

    def test_generated_html_comment_prefixes_mam_basics(self):
        generator_path = Path(__file__).resolve()
        rel = generator_path.relative_to(generator_path.parents[2]).as_posix()
        expected = (
            "Do not edit by hand. "
            f"This file was generated by {self._repo_name()}/{rel}."
        )
        self.assertEqual(
            provenance.generated_html_comment(str(generator_path)), expected
        )

    def test_with_json_provenance_inserts_first_key(self):
        generator_path = Path(__file__).resolve()
        root = {"a": 1, "provenance": "old", "b": 2}
        out = provenance.with_json_provenance(root, str(generator_path))
        self.assertEqual(list(out.keys())[0], "provenance")
        self.assertEqual(out["a"], 1)
        self.assertEqual(out["b"], 2)
        self.assertTrue(
            out["provenance"].startswith(
                f"This file was generated by {self._repo_name()}/"
            )
        )

    def test_directory_provenance_markdown_uses_prefixed_generator_path(self):
        generator_path = Path(__file__).resolve()
        markdown = provenance.directory_provenance_markdown(
            str(generator_path), "demo artifacts"
        )
        self.assertIn("This directory contains generated demo artifacts.", markdown)
        self.assertIn(
            f"This file was generated by {self._repo_name()}/",
            markdown,
        )

    def test_generated_by_text_raises_for_non_local_repo_path(self):
        repos_root = Path(__file__).resolve().parents[3]
        non_mam_path = repos_root / "MAM-simple" / "py" / "fake_generator.py"
        with self.assertRaises(ValueError):
            provenance.generated_by_text(str(non_mam_path))


if __name__ == "__main__":
    unittest.main()
