# Initially generated by GitHub Copilot.
import unittest

from mb_cmn import hebrew_punctuation as hpu
from mb_cmn import template_names as tmpln
from mb_cmn import ws_tmpl2 as wtp
from mpplus import mpplus_scrdfftar


def _mk_scrdff(note_text: str):
    return wtp.mktmpl([[tmpln.SCRDFF_NO_TAR], [note_text]])


class MpplusScrdfftarTests(unittest.TestCase):
    def test_replaces_non_targeted_scrdff_without_retaining_original(self):
        wtseq = (
            "מִנְּשֹֽׂא",
            _mk_scrdff("בספרי ספרד ואשכנז מִנְּשֽׂוֹא"),
        )

        out = mpplus_scrdfftar.add(wtseq)

        self.assertEqual(len(out), 1)
        self.assertEqual(out[0]["tmpl_name"], tmpln.SCRDFF_TAR)
        tmpl_names = [x["tmpl_name"] for x in out if isinstance(x, dict)]
        self.assertNotIn(tmpln.SCRDFF_NO_TAR, tmpl_names)
        self.assertEqual(out[0]["tmpl_params"]["1"], "מִנְּשֹֽׂא")
        self.assertEqual(out[0]["tmpl_params"]["2"], "בספרי ספרד ואשכנז מִנְּשֽׂוֹא")
        self.assertEqual(out[0]["tmpl_params"]["3"], "אאא*")

    def test_deut_11_21_edge_keeps_sof_pasuq_outside_target(self):
        wtseq = (
            "יְמֵיכֶם" + hpu.SOPA,
            _mk_scrdff("בספרי ספרד ואשכנז יְמֵיכֶֽם"),
            " הָאֲדָמָה",
        )

        out = mpplus_scrdfftar.add(wtseq)

        self.assertEqual(out[0]["tmpl_name"], tmpln.SCRDFF_TAR)
        self.assertEqual(out[0]["tmpl_params"]["1"], "יְמֵיכֶם")
        self.assertEqual(out[0]["tmpl_params"]["3"], "אאא*")
        self.assertEqual(out[1], hpu.SOPA)
        self.assertEqual(out[2], " הָאֲדָמָה")


if __name__ == "__main__":
    unittest.main()
