# Initially generated by GitHub Copilot.
"""Helpers for explicit mp_cmn claim-definition emission."""

from typing import Any, Iterable

from mb_author.claim import ClaimCollection

ClaimDef = tuple[str, Any, str, str, Any]


def claim_def(
    claim_id: str,
    payload,
    *,
    kind: str,
    subject: str,
    data: Any = None,
) -> ClaimDef:
    return claim_id, payload, kind, subject, data


def emit_claim_defs(*, claims: ClaimCollection, claim_defs: Iterable[ClaimDef]) -> None:
    for claim_id, payload, kind, subject, data in claim_defs:
        claims.claim(claim_id, payload, kind=kind, subject=subject, data=data)
