# Initially generated by GitHub Copilot.
"""
HTML document: Documentation template (docnote / נוסח) in plus format.

To regenerate the output HTML, run from the repo root::

    .venv/Scripts/python.exe py/main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplus_docnote.html.
"""

from mb_author import author
from mb_author import json_block
from mb_author.claim import ClaimCollection
from author_misc import mp_cmn as cmn

_FNAME = "mpplus_docnote.html"
_TITLE = "Documentation template (docnote / נוסח)"

_PLUS_DOC = "mpplus.html"


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplus_docnote.html in the given output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def build_body(*, claims: ClaimCollection):
    json_docnote_plus = cmn.emit_claim_by_id(
        claims=claims,
        claim_id="mp.plus.example.docnote",
    )
    plus_back_link = author.anchor_h("Reading $MAM-parsed-plus", _PLUS_DOC)
    return [
        author.heading_level_1(["Documentation template (", author.hbo("נוסח"), ")"]),
        author.para(["<- Back to ", plus_back_link]),
        author.para(
            [
                "Its first parameter is the \u201ctarget\u201d - what is being documented."
                " The second parameter contains the documentation"
                " (anomalous forms, variant readings, uncertain readings, etc.).",
            ]
        ),
        json_block.json_block_raw_html(json_docnote_plus),
    ]


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
