# Initially generated by GitHub Copilot.
"""
HTML document: Good-ending template (מ:סיום בטוב) in plain format.

To regenerate the output HTML, run from the repo root::

    .venv/Scripts/python.exe py/main_authored.py gen-mam-parsed-docs

Output goes to ../MAM-parsed/gh-pages/mpplain_good_ending_tmpl.html.
"""

from mb_author import author
from mb_author import json_block
from mb_author.claim import ClaimCollection
from author_misc import mp_cmn_json_snippets as jsnip
from author_misc import mp_good_ending_common

_FNAME = "mpplain_good_ending_tmpl.html"
_TITLE = "Good-ending template (מ:סיום בטוב)"
_CLAIM_ID_EXAMPLE_GOOD_ENDING_TMPL = "mp.plain.example.good-ending-template-stmpl"

_PLAIN_DOC = "mpplain.html"

_JSON_GOOD_ENDING_TMPL = jsnip.read_text(
    "mpplain_good_ending_tmpl", "good_ending_tmpl_plain.json"
)


def gen_html_file(tdm_ch, claims: ClaimCollection):
    """Generate mpplain_good_ending_tmpl.html in the given output directory."""
    cbody = build_body(claims=claims)
    return author.help_gen_html_file(__file__, tdm_ch, _FNAME, _TITLE, cbody)


def build_body(*, claims: ClaimCollection):
    plain_back_link = author.anchor_h("Reading $MAM-parsed-plain", _PLAIN_DOC)
    json_good_ending_tmpl = claims.claim(
        _CLAIM_ID_EXAMPLE_GOOD_ENDING_TMPL,
        _JSON_GOOD_ENDING_TMPL,
        kind="example",
        subject="mp:plain",
    )

    return [
        author.heading_level_1(
            ["Good-ending template (", author.hbo("מ:סיום בטוב"), ")"]
        ),
        author.para(["← Back to ", plain_back_link]),
        author.para(mp_good_ending_common.MAIN_DESCRIPTION),
        json_block.json_block_raw_html(json_good_ending_tmpl),
    ]


def _build_body(*, claims: ClaimCollection):
    return build_body(claims=claims)
