"""Validate transient parser-stage data before MAM-parsed-plus conversion."""

import collections
import json

from mb_cmn import file_io
from mb_cmn import kq_special_templates as kqst
from mb_cmn.my_utils import first_and_only
from mb_cmn.my_utils import first_and_only_and_str
from mb_cmn import paths
from mb_cmn import parser_stage_template_schema
from mb_cmn import ws_tmpl1 as wtp1
from mb_cmn import ws_tmpl2 as wtp2
from mb_cmn import ws_tmpl_named_params as wtnp
from tmpl_survey import column_d_0_process_all_mpasuq_calls as cdp
from tmpl_survey import column_d_0_store_the_mpasuq_call as cds
from tmpl_survey import column_d_0_store_the_mpasuq_call_plus as cds_plus
from tmpl_survey import nesting_normal_form

_EXPANDED_STACK_GRAMMAR_LOCK_PATH = (
    paths.repo_root() / "py/verify_mp/expanded_stack_grammar_parser_stage.lock.json"
)
_EXPANDED_STACK_GRAMMAR_LOCK_PROVENANCE = (
    "This file was generated by MAM-basics/py/main_parse.py ws"
    " --write-parser-stage-grammar-lock."
)
# The D column's label parameters, which validate_plus_conversion compares between
# the parser stage and plus.  Parameters 1 to 3 of מ:פסוק are its coordinates, which
# the mpasuq collectors already check.
_PASUQ_COORDINATE_PARAMS = frozenset({"1", "2", "3"})
_ALIYAH_LABEL_PARAMS = frozenset({"א", "ב0", "ב1", "ב2", "ב3", "ג0", "ג1", "ג2", "ג3"})
_EXPECTED_ARGC = {
    "כו״ק": 2,
    "מ:אות מנוקדת": 1,
    kqst.UNIFIED_SPECIAL_KQ_TEMPLATE_NAME: (2, 3, 4, 5, 6),
}
_MID_VERSE_PARAGRAPH_TEMPLATES = frozenset({"סס", "פפ", "פפפ"})
_RANK_MAPS = {
    "C": nesting_normal_form.build_rank_map(
        nesting_normal_form.RANK_GROUPS_FOR_PLAIN_C
    ),
    "D": nesting_normal_form.build_rank_map(
        nesting_normal_form.RANK_GROUPS_FOR_PLAIN_D
    ),
    "E": nesting_normal_form.build_rank_map(
        nesting_normal_form.RANK_GROUPS_FOR_PLAIN_E
    ),
}


def node_type_and_subtype(node):
    """Validate and classify one non-string parser-stage node."""
    if wtp1.is_template(node):
        template_name = parser_stage_template_schema.validate_parser_stage_template(
            node
        )
        if kqst.is_special_kq_template_name(template_name):
            assert kqst.is_unified_special_kq_template_name(
                template_name
            ), template_name
        return "tmpl", template_name
    if wtp1.is_abtag(node):
        return (
            "custom_tag",
            parser_stage_template_schema.validate_parser_stage_custom_tag(node),
        )
    raise TypeError(f"unclassified current parser-stage node: {node!r}")


def validate_template_arg_count(template_name, arg_count):
    """Validate the constrained argument counts in parser-stage templates."""
    expected = _EXPECTED_ARGC.get(template_name)
    if isinstance(expected, int):
        expected = (expected,)
    assert expected is None or arg_count in expected


def child_stack_symbols(parent_template_name, argument_index):
    """Return the stack symbols contributed by one template argument."""
    _ = argument_index
    return (parent_template_name,)


def _validate_special_kq(template, template_name):
    if template_name != kqst.UNIFIED_SPECIAL_KQ_TEMPLATE_NAME:
        return
    params = wtnp.get_tmpl_params_ss(wtp1.template_arguments(template))
    ketiv = params["1"]
    qere = params["2"]
    sug = first_and_only_and_str(params["סוג"])
    assert isinstance(ketiv, list) and ketiv
    assert isinstance(qere, list) and qere
    kqst.canonical_special_kq_type_from_name_and_sug(template_name, sug)


def _validate_mid_verse_paragraph_argument(template, template_name):
    if template_name not in _MID_VERSE_PARAGRAPH_TEMPLATES:
        return
    arguments = wtp1.template_arguments(template)
    if arguments:
        assert arguments == [["פסקא באמצע פסוק"]]


def _stack_rest(stack):
    return "/".join(stack)


def _validate_node(stack_counts, stack, node, *, nested=False):
    if isinstance(node, str):
        return
    assert isinstance(node, dict)
    node_type, node_subtype = node_type_and_subtype(node)
    if nested:
        assert node_type == "tmpl"
    if node_type != "tmpl":
        return
    _validate_special_kq(node, node_subtype)
    _validate_mid_verse_paragraph_argument(node, node_subtype)
    stack_counts[(node_subtype, _stack_rest(stack))] += 1
    arguments = wtp1.template_arguments(node)
    validate_template_arg_count(node_subtype, len(arguments))
    for argument_index, argument in enumerate(arguments, start=1):
        child_stack = *stack, *child_stack_symbols(node_subtype, argument_index)
        for child in argument:
            _validate_node(stack_counts, child_stack, child, nested=True)


def _parser_stage_d_labels(column):
    """One true verse's parser-stage D cell as (wrapped, labels): closed dispatch."""
    wtel = first_and_only(column)
    if wtp1.is_template_with_name(wtel, "נוסח"):
        params = wtnp.get_tmpl_params_ss(wtp1.template_arguments(wtel))
        # Parameter 2 is the documentation note, not a label parameter.
        if set(params) != {"1", "2"}:
            raise ValueError(f"נוסח in column D has parameters {sorted(params)}")
        return True, _parser_stage_pasuq_labels(first_and_only(params["1"]))
    return False, _parser_stage_pasuq_labels(wtel)


def _parser_stage_pasuq_labels(wtel):
    if not wtp1.is_template_with_name(wtel, "מ:פסוק"):
        raise ValueError(f"column D holds an unrecognized node: {wtel!r}")
    labels = {}
    params = wtnp.get_tmpl_params_ss(wtp1.template_arguments(wtel))
    for name, value in params.items():
        if name in _PASUQ_COORDINATE_PARAMS:
            continue
        if name == "סדר":
            labels[name] = first_and_only_and_str(value)
        elif name == "עלייה":
            labels[name] = _parser_stage_aliyah_labels(first_and_only(value))
        else:
            raise ValueError(f"מ:פסוק has an unrecognized parameter: {name}")
    return labels


def _parser_stage_aliyah_labels(wtel):
    if not wtp1.is_template_with_name(wtel, "מ:עלייה"):
        raise ValueError(f"עלייה holds an unrecognized node: {wtel!r}")
    labels = {}
    params = wtnp.get_tmpl_params_ss(wtp1.template_arguments(wtel))
    for name, value in params.items():
        if name not in _ALIYAH_LABEL_PARAMS:
            raise ValueError(f"מ:עלייה has an unrecognized parameter: {name}")
        labels[name] = first_and_only_and_str(value)
    return labels


def _plus_d_labels(column):
    """One verse's plus D cell as (wrapped, labels), projected as the parser stage is."""
    if not column:
        return False, {}
    wtel = first_and_only(column)
    if wtp2.is_template_with_name(wtel, "נוסח"):
        param_names = set(wtp2.template_param_keys(wtel))
        # Parameter 2 is the documentation note, not a label parameter.
        if param_names != {"1", "2"}:
            raise ValueError(f"נוסח in column D has parameters {sorted(param_names)}")
        inner = first_and_only(wtp2.template_param_val(wtel, "1"))
        return True, _plus_pasuq_labels(inner)
    return False, _plus_pasuq_labels(wtel)


def _plus_pasuq_labels(wtel):
    if not wtp2.is_template_with_name(wtel, "מ:פסוק"):
        raise ValueError(f"column D holds an unrecognized node: {wtel!r}")
    labels = {}
    for name in wtp2.template_param_keys(wtel):
        value = wtp2.template_param_val(wtel, name)
        if name in _PASUQ_COORDINATE_PARAMS:
            continue
        if name == "סדר":
            labels[name] = first_and_only_and_str(value)
        elif name == "עלייה":
            labels[name] = _plus_aliyah_labels(first_and_only(value))
        else:
            raise ValueError(f"מ:פסוק has an unrecognized parameter: {name}")
    return labels


def _plus_aliyah_labels(wtel):
    if not wtp2.is_template_with_name(wtel, "מ:עלייה"):
        raise ValueError(f"עלייה holds an unrecognized node: {wtel!r}")
    labels = {}
    for name in wtp2.template_param_keys(wtel):
        if name not in _ALIYAH_LABEL_PARAMS:
            raise ValueError(f"מ:עלייה has an unrecognized parameter: {name}")
        labels[name] = first_and_only_and_str(wtp2.template_param_val(wtel, name))
    return labels


def _validate_book39(book39, stack_counts, mpasuq_calls, d_labels):
    assert set(book39) == {"book24_name", "sub_book_name", "chapters"}
    book24_name = book39["book24_name"]
    sub_book_name = book39["sub_book_name"]
    chapters = book39["chapters"]
    assert isinstance(book24_name, str)
    assert sub_book_name is None or isinstance(sub_book_name, str)
    assert isinstance(chapters, dict)
    for chapter_number, chapter in chapters.items():
        assert isinstance(chapter_number, str)
        assert isinstance(chapter, dict) and chapter
        pseudo_verse_numbers = tuple(chapter)
        assert pseudo_verse_numbers[0] == "0"
        assert pseudo_verse_numbers[-1] == "תתת"
        for pseudo_verse_number, columns in chapter.items():
            assert isinstance(pseudo_verse_number, str)
            assert pseudo_verse_number in ("0", "תתת") or pseudo_verse_number.isdigit()
            assert isinstance(columns, (list, tuple)) and len(columns) == 3
            bscv = book24_name, sub_book_name, chapter_number, pseudo_verse_number
            for column_letter, column in zip(("C", "D", "E"), columns):
                assert isinstance(column, (list, tuple))
                for node in column:
                    _validate_node(stack_counts, (column_letter,), node)
            cds.store_the_mpasuq_call(mpasuq_calls, bscv, columns[1])
            if pseudo_verse_number not in ("0", "תתת"):
                d_labels[bscv] = _parser_stage_d_labels(columns[1])


def _validate_header(header, book39s):
    assert set(header) == {"book24_name", "sub_book_names", "chapter_counts"}
    assert isinstance(header["book24_name"], str)
    assert isinstance(header["sub_book_names"], list)
    assert isinstance(header["chapter_counts"], list)
    assert all(book39["book24_name"] == header["book24_name"] for book39 in book39s)
    expected_sub_book_names = [
        book39["sub_book_name"]
        for book39 in book39s
        if book39["sub_book_name"] is not None
    ]
    assert header["sub_book_names"] == expected_sub_book_names
    assert len(header["chapter_counts"]) == len(book39s)
    for chapter_count, book39 in zip(header["chapter_counts"], book39s):
        assert set(chapter_count) == {"sub_book_name", "chapter_count"}
        assert chapter_count["sub_book_name"] == book39["sub_book_name"]
        assert chapter_count["chapter_count"] == len(book39["chapters"])


def _validate_normal_form(stack_counts):
    for column_letter, rank_map in _RANK_MAPS.items():
        column_counts = {
            key: count
            for key, count in stack_counts.items()
            if key[1].split("/", maxsplit=1)[0] == column_letter
        }
        nesting_normal_form.assert_stack_counts_in_normal_form(
            column_counts,
            dataset_name=f"parser stage ({column_letter} column)",
            rank_map=rank_map,
        )


def _validate_expanded_stack_grammar(stack_counts):
    with _EXPANDED_STACK_GRAMMAR_LOCK_PATH.open(encoding="utf-8") as fp:
        grammar = json.load(fp)
    nesting_normal_form.assert_stack_counts_follow_expanded_grammar(
        stack_counts,
        grammar,
        dataset_name="parser stage",
    )


def _validate_structure(section):
    """Validate one group, except against the grammar lock, and collect its data.

    Returns the group's stack counts, its mpasuq calls and the D-column labels of its
    true verses.  validate checks the stack counts against the expanded stack grammar
    lock; write_expanded_stack_grammar_lock infers a new lock from them instead.
    """
    assert set(section) == {"header", "book39s"}
    book39s = section["book39s"]
    assert isinstance(book39s, list) and book39s
    _validate_header(section["header"], book39s)
    stack_counts = collections.defaultdict(int)
    mpasuq_calls = []
    d_labels = {}
    for book39 in book39s:
        _validate_book39(book39, stack_counts, mpasuq_calls, d_labels)
    _validate_normal_form(stack_counts)
    return stack_counts, mpasuq_calls, d_labels


def validate(section):
    """Validate one transient book24 group and return relationship data."""
    stack_counts, mpasuq_calls, d_labels = _validate_structure(section)
    _validate_expanded_stack_grammar(stack_counts)
    return {
        "mpasuq": cdp.process_all_mpasuq_calls(mpasuq_calls),
        "stack_counts": stack_counts,
        "d_labels": d_labels,
    }


def write_expanded_stack_grammar_lock(sections):
    """Infer the expanded stack grammar from every group and write its lock file.

    The caller passes all 24 transient book24 groups, then validates each group against
    the new lock as every run does.
    """
    stack_counts = collections.defaultdict(int)
    for section in sections:
        section_counts, _mpasuq_calls, _d_labels = _validate_structure(section)
        for key, count in section_counts.items():
            stack_counts[key] += count
    grammar = nesting_normal_form.infer_expanded_stack_grammar(stack_counts)
    file_io.json_dump_to_file_path(
        {"provenance": _EXPANDED_STACK_GRAMMAR_LOCK_PROVENANCE, **grammar},
        str(_EXPANDED_STACK_GRAMMAR_LOCK_PATH),
    )


# The keys of every transient parser-stage node.  node_type_and_subtype admits a node only
# through ws_tmpl1.dic_is_template, whose keys are the two template encodings ("tmpl" and
# "stmpl", which ws_tmpl1.simplify_wtel writes), or ws_tmpl1.is_abtag, whose key is the
# custom-tag encoding ("custom_tag", which ws_abtag_parser and ws_plain write).  Plus has
# templates as {"tmpl_name": ..., "tmpl_params": ...} and no custom tag, so a dict in plus
# with any of these keys is a parser-stage node that the conversion left behind.
PARSER_STAGE_NODE_KEYS = frozenset({"tmpl", "stmpl", "custom_tag"})


def _validate_no_parser_stage_encoding(node):
    if isinstance(node, dict):
        leaked = PARSER_STAGE_NODE_KEYS & set(node)
        assert not leaked, f"plus holds a parser-stage node: {node!r}"
        for value in node.values():
            _validate_no_parser_stage_encoding(value)
    elif isinstance(node, (list, tuple)):
        for item in node:
            _validate_no_parser_stage_encoding(item)


def _validate_plus_structure_and_collect(parser_stage_section, plus_section):
    mpasuq_calls = []
    d_labels = {}
    parser_stage_book39s = parser_stage_section["book39s"]
    plus_book39s = plus_section["book39s"]
    assert len(plus_book39s) == len(parser_stage_book39s)
    for parser_stage_book39, plus_book39 in zip(parser_stage_book39s, plus_book39s):
        assert plus_book39["book24_name"] == parser_stage_book39["book24_name"]
        assert plus_book39["sub_book_name"] == parser_stage_book39["sub_book_name"]
        parser_stage_chapters = parser_stage_book39["chapters"]
        plus_chapters = plus_book39["chapters"]
        assert tuple(plus_chapters) == tuple(parser_stage_chapters)
        book24_name = plus_book39["book24_name"]
        sub_book_name = plus_book39["sub_book_name"]
        for chapter_number, chapter in plus_chapters.items():
            expected_verses = tuple(
                number
                for number in parser_stage_chapters[chapter_number]
                if number not in ("0", "תתת")
            )
            assert tuple(chapter) == expected_verses
            for verse_number, columns in chapter.items():
                assert verse_number not in ("0", "תתת")
                assert isinstance(columns, (list, tuple)) and len(columns) == 3
                _validate_no_parser_stage_encoding(columns)
                bscv = book24_name, sub_book_name, chapter_number, verse_number
                cds_plus.store_the_mpasuq_call(mpasuq_calls, bscv, columns[1])
                d_labels[bscv] = _plus_d_labels(columns[1])
    return cdp.process_all_mpasuq_calls(mpasuq_calls), d_labels


def _assert_same_d_labels(parser_stage_d_labels, plus_d_labels):
    if plus_d_labels == parser_stage_d_labels:
        return
    for bscv, parser_stage_projection in parser_stage_d_labels.items():
        plus_projection = plus_d_labels.get(bscv)
        if plus_projection != parser_stage_projection:
            raise AssertionError(
                f"column D labels differ at {bscv}: parser stage"
                f" {parser_stage_projection!r}, plus {plus_projection!r}"
            )
    extra = sorted(set(plus_d_labels) - set(parser_stage_d_labels))
    raise AssertionError(f"plus has column D labels for verses it should not: {extra}")


def validate_plus_conversion(
    parser_stage_section, parser_stage_validation, plus_section
):
    """Validate retained raw-to-plus relationships before either value is written."""
    plus_mpasuq, plus_d_labels = _validate_plus_structure_and_collect(
        parser_stage_section, plus_section
    )
    assert plus_mpasuq == parser_stage_validation["mpasuq"]
    _assert_same_d_labels(parser_stage_validation["d_labels"], plus_d_labels)
