# Initially generated by GitHub Copilot.
"""Verifiers for mp.plain.* structural claims."""

from author_util.claim import ClaimRecord
from verify_mp import survey_artifact
from verify_mp.corpus import (
    Context,
    iter_plain_book39s,
    iter_plain_chapters,
    iter_plain_verses,
)


def _verify_template_set_plain_observed(
    record: ClaimRecord, ctx: Context, *, key: str = "templates"
) -> None:
    """Assert that every declared template appears in the plain corpus survey.

    key: the record.data key holding the name(s). If the value is a list,
    every element is checked. If it is a string, it is wrapped in a list first.
    """
    declared_raw = record.data[key]
    if isinstance(declared_raw, list):
        declared = frozenset(declared_raw)
    else:
        declared = frozenset([declared_raw])
    observed = survey_artifact.template_names_observed(ctx.survey_plain)
    missing = declared - observed
    assert (
        not missing
    ), f"declared templates not found in plain corpus survey: {sorted(missing)}"


def verify_mp_plain_templates_jerusalem_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared Jerusalem template appears at least once in the plain corpus."""
    _verify_template_set_plain_observed(record, ctx)


def verify_mp_plain_templates_plain_only_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared plain-only template appears at least once in the plain corpus."""
    _verify_template_set_plain_observed(record, ctx)


def verify_mp_plain_book39_fields(record: ClaimRecord, ctx: Context) -> None:
    """Every book39 object in the plain corpus has exactly the declared keys."""
    expected = frozenset(record.data["book39_keys"])
    for book39 in iter_plain_book39s(ctx.corpus_plain):
        actual = frozenset(book39.keys())
        assert actual == expected, (
            f"book39 {book39.get('book24_name')!r}:"
            f" keys {sorted(actual)} != expected {sorted(expected)}"
        )


def verify_mp_plain_verse_is_3_tuple(record: ClaimRecord, ctx: Context) -> None:
    """Every verse value in the plain corpus is a list of exactly 3 elements [C, D, E]."""
    for book39, ch_key, v_key, verse in iter_plain_verses(ctx.corpus_plain):
        assert isinstance(verse, list) and len(verse) == 3, (
            f"book39={book39['book24_name']!r} ch={ch_key} v={v_key}:"
            f" verse has {len(verse) if isinstance(verse, list) else type(verse).__name__}"
            f" elements (expected 3)"
        )


def verify_mp_plain_chapter_pseudo_verse_keys(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every chapter in the plain corpus contains pseudo-verse keys '0' and 'תתת'."""
    for book39, ch_key, chapter in iter_plain_chapters(ctx.corpus_plain):
        assert (
            "0" in chapter
        ), f"book39={book39['book24_name']!r} ch={ch_key}: missing pseudo-verse key '0'"
        assert (
            "תתת" in chapter
        ), f"book39={book39['book24_name']!r} ch={ch_key}: missing pseudo-verse key 'תתת'"
