# Initially generated by GitHub Copilot.
"""Verifiers for mp.plain.* structural claims."""

from author_util.claim import ClaimRecord
from verify_mp.corpus import (
    Context,
    iter_plain_book39s,
    iter_plain_chapters,
    iter_plain_verses,
)


def verify_mp_plain_book39_fields(record: ClaimRecord, ctx: Context) -> None:
    """Every book39 object in the plain corpus has exactly the declared keys."""
    expected = frozenset(record.data["book39_keys"])
    for book39 in iter_plain_book39s(ctx.corpus_plain):
        actual = frozenset(book39.keys())
        assert actual == expected, (
            f"book39 {book39.get('book24_name')!r}:"
            f" keys {sorted(actual)} != expected {sorted(expected)}"
        )


def verify_mp_plain_verse_is_3_tuple(record: ClaimRecord, ctx: Context) -> None:
    """Every verse value in the plain corpus is a list of exactly 3 elements [C, D, E]."""
    for book39, ch_key, v_key, verse in iter_plain_verses(ctx.corpus_plain):
        assert isinstance(verse, list) and len(verse) == 3, (
            f"book39={book39['book24_name']!r} ch={ch_key} v={v_key}:"
            f" verse has {len(verse) if isinstance(verse, list) else type(verse).__name__}"
            f" elements (expected 3)"
        )


def verify_mp_plain_chapter_pseudo_verse_keys(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every chapter in the plain corpus contains pseudo-verse keys '0' and 'תתת'."""
    for book39, ch_key, chapter in iter_plain_chapters(ctx.corpus_plain):
        assert (
            "0" in chapter
        ), f"book39={book39['book24_name']!r} ch={ch_key}: missing pseudo-verse key '0'"
        assert (
            "תתת" in chapter
        ), f"book39={book39['book24_name']!r} ch={ch_key}: missing pseudo-verse key 'תתת'"
