# Initially generated by GitHub Copilot.
"""Verifiers for mp.both.* claims (claims that apply to both plain and plus)."""

import glob
from pathlib import Path
from typing import Callable

from author_util.claim import ClaimRecord
from verify_mp import survey_artifact
from verify_mp import kq_special_counts
from verify_mp.corpus import (
    Context,
    iter_all_template_objects,
    iter_template_objects,
    iter_verses,
)

VerifierFn = Callable[[ClaimRecord, Context], None]

# Torah (Pentateuch) + Esther book24_name values — the only books where
# targeted scroll-difference notes (מ:הערה-2) may appear in plus.
_NOTE_BOOKS = frozenset(
    [
        "ספר בראשית",
        "ספר שמות",
        "ספר ויקרא",
        "ספר במדבר",
        "ספר דברים",
        "מגילת אסתר",
    ]
)

# Normalize straight double-quote (U+0022) → Hebrew gershayim (U+05F4).
# The plus corpus JSON stores sug= values with straight quotes; claim data uses
# gershayim.  Normalizing both sides ensures they compare equal.
_NORM_QUOTES = str.maketrans({'"': "״"})


def verify_mp_both_file_naming_book24_prefixes(
    record: ClaimRecord, ctx: Context
) -> None:
    """Observed plain/plus file-name prefixes match the declared set exactly."""
    del ctx  # This check reads file names directly.
    declared = frozenset(record.data["prefixes"])

    plus_paths = glob.glob("../MAM-parsed/plus/*.json")
    plain_paths = glob.glob("../MAM-parsed/plain/*.json")
    assert plus_paths, "no plus JSON files found for file-naming verification"
    assert plain_paths, "no plain JSON files found for file-naming verification"

    def _prefixes(paths: list[str]) -> frozenset[str]:
        result = set()
        for p in paths:
            stem = Path(p).stem
            prefix = stem.split("-", 1)[0]
            result.add(prefix)
        return frozenset(result)

    plus_prefixes = _prefixes(plus_paths)
    plain_prefixes = _prefixes(plain_paths)

    assert plus_prefixes == declared, (
        f"plus filename prefixes {sorted(plus_prefixes)}"
        f" != declared {sorted(declared)}"
    )
    assert plain_prefixes == declared, (
        f"plain filename prefixes {sorted(plain_prefixes)}"
        f" != declared {sorted(declared)}"
    )


def _verify_template_set_observed(
    record: ClaimRecord, ctx: Context, *, key: str = "templates"
) -> None:
    """Assert that every declared template appears in both corpus surveys.

    key: the record.data key holding the name(s). If the value is a list,
    every element is checked. If it is a string (e.g. key="template"), it is
    wrapped in a list first.

    Uses the intersection (plain ∩ plus): an mp:both claim asserts that a
    template appears in *both* corpora. Templates expanded to inline text by
    mpplus_boring_tmpls.py appear only in plain; they must not be listed in
    an mp:both claim's data.templates (they should be in an mp:plain claim).

    The reverse direction (observed ∩ declared) is covered by
    verify_mp_both_templates_all_groups_cover_all_observed.
    """
    declared_raw = record.data[key]
    if isinstance(declared_raw, list):
        declared = frozenset(declared_raw)
    else:
        declared = frozenset([declared_raw])
    observed = survey_artifact.template_names_observed_both_intersection(
        ctx.survey, ctx.survey_plain
    )
    missing = declared - observed
    assert (
        not missing
    ), f"declared templates not found in both corpus surveys: {sorted(missing)}"


def _verify_template_set_observed_in_plus(
    record: ClaimRecord, ctx: Context, *, key: str = "templates"
) -> None:
    """Assert that every declared template appears in the plus corpus survey."""
    declared_raw = record.data[key]
    if isinstance(declared_raw, list):
        declared = frozenset(declared_raw)
    else:
        declared = frozenset([declared_raw])
    observed = survey_artifact.template_names_observed(ctx.survey)
    missing = declared - observed
    assert (
        not missing
    ), f"declared templates not found in plus corpus survey: {sorted(missing)}"


def verify_mp_both_templates_kq_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared kq-family template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_special_letters_set(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every declared special-letters template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_accents_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared accents template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_poetic_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared poetic template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_other_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared other template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def _iter_template_occurrences_with_ancestors(node, *, ancestors=()):
    """Yield (template_obj, ancestors) pairs from a node tree.

    ancestors is a tuple of (parent_template_name, parent_param_key) pairs
    describing where the current template object was found.
    """
    if isinstance(node, dict):
        if "tmpl_name" in node:
            tmpl_name = node["tmpl_name"]
            yield node, ancestors
            for param_key, param_val in node.get("tmpl_params", {}).items():
                yield from _iter_template_occurrences_with_ancestors(
                    param_val,
                    ancestors=(*ancestors, (tmpl_name, str(param_key))),
                )
        else:
            for value in node.values():
                yield from _iter_template_occurrences_with_ancestors(
                    value,
                    ancestors=ancestors,
                )
    elif isinstance(node, list):
        for item in node:
            yield from _iter_template_occurrences_with_ancestors(
                item,
                ancestors=ancestors,
            )


def _verify_template_only_in_parent_param(record: ClaimRecord, ctx: Context) -> None:
    """Assert a template appears only under a specific parent template param."""
    target = record.data["template"]
    parent_tmpl = record.data["parent_template"]
    parent_param = str(record.data["parent_param"])

    bad: list[str] = []
    seen = 0
    col_letters = ("C", "D", "E")
    for book39, ch_key, v_key, verse in iter_verses(ctx.corpus):
        for col_idx, col in enumerate(verse):
            for tmpl, ancestors in _iter_template_occurrences_with_ancestors(col):
                if tmpl["tmpl_name"] != target:
                    continue
                seen += 1
                in_expected_context = any(
                    anc_name == parent_tmpl and anc_param == parent_param
                    for anc_name, anc_param in ancestors
                )
                if in_expected_context:
                    continue
                anc_text = " > ".join(f"{name}[{param}]" for name, param in ancestors)
                if not anc_text:
                    anc_text = "<root>"
                bad.append(
                    f"{book39['book24_name']} {ch_key}:{v_key}"
                    f" {col_letters[col_idx]} ancestors={anc_text}"
                )

    assert seen, f"template {target!r} not found in plus corpus"
    assert not bad, (
        f"template {target!r} found outside {parent_tmpl!r} param {parent_param!r};"
        f" sample locations: {bad[:5]}"
    )


def verify_mp_both_templates_modag_only_in_docnote_param2(
    record: ClaimRecord, ctx: Context
) -> None:
    """Template מודגש appears only in נוסח param 2."""
    _verify_template_only_in_parent_param(record, ctx)


def verify_mp_both_templates_sampe_pabp_arg_value(
    record: ClaimRecord, ctx: Context
) -> None:
    """When סס/ססס/פפ/פפפ have positional param 1, it must equal the declared arg_value."""
    expected = record.data["arg_value"]
    templates = frozenset(record.data["templates"])
    bad = []

    def _normalize_param_1(val):
        if isinstance(val, str):
            return val
        if isinstance(val, list):
            return "".join(val)
        return None

    for tmpl in iter_all_template_objects(ctx.corpus):
        if tmpl["tmpl_name"] not in templates:
            continue
        params = tmpl.get("tmpl_params", {})
        if "1" not in params:
            continue
        val = params["1"]
        if _normalize_param_1(val) != expected:
            bad.append(f"{tmpl['tmpl_name']} param 1 = {val!r}")
    assert not bad, f"unexpected param 1 values: {bad[:5]}"


def verify_mp_both_templates_sh_only_in_docnote_param2(
    record: ClaimRecord, ctx: Context
) -> None:
    """Template ש appears only in נוסח param 2."""
    _verify_template_only_in_parent_param(record, ctx)


def _verify_note_books_only(record: ClaimRecord, ctx: Context) -> None:
    """Assert note templates only appear in Torah and Esther books.

    Walks the raw plus corpus and collects every book24_name where a template
    whose name is in record.data["templates"] appears. Asserts the resulting
    set is a subset of _NOTE_BOOKS.
    """
    tmpl_names = frozenset(record.data["templates"])
    bad_books: set[str] = set()
    for book39, _ch_key, _v_key, verse in iter_verses(ctx.corpus):
        book = book39["book24_name"]
        if book in _NOTE_BOOKS:
            continue
        for col in verse:
            for tmpl in iter_template_objects(col):
                if tmpl["tmpl_name"] in tmpl_names:
                    bad_books.add(book)
    assert (
        not bad_books
    ), f"note templates found outside Torah/Esther: {sorted(bad_books)}"


def verify_mp_both_templates_note(record: ClaimRecord, ctx: Context) -> None:
    """Template מ:הערה-2 appears in plus and only in Torah and Esther books."""
    _verify_template_set_observed_in_plus(record, ctx)
    _verify_note_books_only(record, ctx)


def _verify_template_set_listed_in_docs_claims(
    record: ClaimRecord, ctx: Context, *, docs_claim_ids: tuple[str, ...]
) -> None:
    """Assert declared templates are listed in each provided docs-template claim."""
    assert (
        ctx.claim_records is not None
    ), "ctx.claim_records was not provided to verifier context"
    declared = frozenset(record.data["templates"])
    for claim_id in docs_claim_ids:
        docs_claim = ctx.claim_records[claim_id]
        listed = frozenset(docs_claim.data["templates"])
        missing = declared - listed
        assert (
            not missing
        ), f"templates from {record.id} missing in {claim_id}: {sorted(missing)}"


def verify_mp_both_templates_note_links_set(record: ClaimRecord, ctx: Context) -> None:
    """Declared note-link templates are observed in corpus and listed in both docs."""
    _verify_template_set_observed(record, ctx)
    _verify_template_set_listed_in_docs_claims(
        record,
        ctx,
        docs_claim_ids=(
            "mp.plain.docs.common-templates.templates-in-plain-survey",
            "mp.plus.docs.common-templates.templates-in-plus-survey",
        ),
    )


def verify_mp_both_templates_structural_set(record: ClaimRecord, ctx: Context) -> None:
    """Declared structural templates are observed in corpus and listed in both docs."""
    _verify_template_set_observed(record, ctx)
    _verify_template_set_listed_in_docs_claims(
        record,
        ctx,
        docs_claim_ids=(
            "mp.plain.docs.common-templates.templates-in-plain-survey",
            "mp.plus.docs.common-templates.templates-in-plus-survey",
        ),
    )


def verify_mp_both_templates_navigation_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared navigation template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


# ---------------------------------------------------------------------------
# Raw-corpus helpers for named-parameter value checks (B2, B3)
# ---------------------------------------------------------------------------


def _verify_named_param_values_subset(record: ClaimRecord, ctx: Context) -> None:
    """Assert every observed tmpl_params[param] value is among the declared values.

    Walks the raw plus corpus; the survey does not preserve named-parameter values.
    Handles param values stored as plain strings or as 1-element string lists.

    Reads from record.data: "template" (tmpl_name to match), "param" (param key),
    "values" (declared allowed values).
    """
    tmpl_name = record.data["template"]
    param_name = record.data["param"]
    declared = frozenset(v.translate(_NORM_QUOTES) for v in record.data["values"])
    observed: set[str] = set()
    for tmpl in iter_all_template_objects(ctx.corpus):
        if tmpl["tmpl_name"] != tmpl_name:
            continue
        raw = tmpl.get("tmpl_params", {}).get(param_name)
        if raw is None:
            continue
        if isinstance(raw, str):
            observed.add(raw.translate(_NORM_QUOTES))
        elif isinstance(raw, list) and len(raw) == 1 and isinstance(raw[0], str):
            observed.add(raw[0].translate(_NORM_QUOTES))
        else:
            assert False, f"unexpected {param_name}= value structure: {raw!r}"
    unexpected = observed - declared
    assert (
        not unexpected
    ), f"unexpected {param_name}= values in {tmpl_name}: {sorted(unexpected)}"


def verify_mp_both_templates_kq_special_subtypes(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every סוג= value observed for מ:כו״ק מיוחד is among the nine declared subtypes."""
    _verify_named_param_values_subset(record, ctx)


def verify_mp_both_templates_kq_special_subtype_counts(
    record: ClaimRecord, ctx: Context
) -> None:
    """Each kq-special subtype has declared fixed ketiv/qere atom counts."""
    kq_special_counts.verify(record, ctx)


def verify_mp_both_templates_kq_am2_sug_values(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every observed סוג= value in מ:קו״כ-אם-2 is among the declared values."""
    _verify_named_param_values_subset(record, ctx)


# ---------------------------------------------------------------------------
# Global coverage check (B1)
# ---------------------------------------------------------------------------


def verify_mp_both_templates_all_groups_cover_all_observed(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every template observed in either survey is covered by at least one declared group.

    Collects all declared template names from mp.both.templates.*.set,
    mp.both.templates.note, and mp.plain.templates.*.set claims in
    ctx.claim_records, then asserts that every template name observed in either
    corpus survey (union) is in the resulting union of declared templates.
    """
    assert (
        ctx.claim_records is not None
    ), "ctx.claim_records was not provided to verifier context"
    declared: set[str] = set()
    for cid, rec in ctx.claim_records.items():
        is_both = cid.startswith("mp.both.templates.") and (
            cid.endswith(".set") or cid == "mp.both.templates.note"
        )
        is_plain = cid.startswith("mp.plain.templates.") and cid.endswith(".set")
        is_plus = cid.startswith("mp.plus.templates.") and cid.endswith(".set")
        if not (is_both or is_plain or is_plus):
            continue
        if cid == record.id:
            continue
        d = rec.data
        if "templates" in d:
            declared.update(d["templates"])
        if "template" in d:
            declared.add(d["template"])
    observed = survey_artifact.template_names_observed_both(
        ctx.survey, ctx.survey_plain
    )
    uncovered = observed - declared
    assert (
        not uncovered
    ), f"observed templates not covered by any declared group: {sorted(uncovered)}"


REGISTRY: dict[str, VerifierFn] = {
    "mp.both.file-naming.book24-prefixes": verify_mp_both_file_naming_book24_prefixes,
    "mp.both.templates.accents.set": verify_mp_both_templates_accents_set,
    "mp.both.templates.all-groups-cover-all-observed": verify_mp_both_templates_all_groups_cover_all_observed,
    "mp.both.templates.kq-am2.sug-values": verify_mp_both_templates_kq_am2_sug_values,
    "mp.both.templates.kq-special.subtype-counts": verify_mp_both_templates_kq_special_subtype_counts,
    "mp.both.templates.kq-special.subtypes": verify_mp_both_templates_kq_special_subtypes,
    "mp.both.templates.kq.set": verify_mp_both_templates_kq_set,
    "mp.both.templates.modag.only-in-docnote-param2": verify_mp_both_templates_modag_only_in_docnote_param2,
    "mp.both.templates.navigation.set": verify_mp_both_templates_navigation_set,
    "mp.both.templates.note": verify_mp_both_templates_note,
    "mp.both.templates.note-links.set": verify_mp_both_templates_note_links_set,
    "mp.both.templates.other.set": verify_mp_both_templates_other_set,
    "mp.both.templates.poetic.set": verify_mp_both_templates_poetic_set,
    "mp.both.templates.sampe.pabp-arg-value": verify_mp_both_templates_sampe_pabp_arg_value,
    "mp.both.templates.sh.only-in-docnote-param2": verify_mp_both_templates_sh_only_in_docnote_param2,
    "mp.both.templates.special-letters.set": verify_mp_both_templates_special_letters_set,
    "mp.both.templates.structural.set": verify_mp_both_templates_structural_set,
}

