# Initially generated by GitHub Copilot.
"""Verifiers for mp.both.* claims (claims that apply to both plain and plus)."""

from author_util.claim import ClaimRecord, REGISTRY
from verify_mp import survey_artifact
from verify_mp import kq_special_counts
from verify_mp.corpus import (
    Context,
    iter_all_template_objects,
    iter_template_objects,
    iter_verses,
)

# Torah (Pentateuch) + Esther book24_name values — the only books where
# מ:הערה / מ:הערה-2 may appear.
_FOOTNOTE_BOOKS = frozenset(
    [
        "ספר בראשית",
        "ספר שמות",
        "ספר ויקרא",
        "ספר במדבר",
        "ספר דברים",
        "מגילת אסתר",
    ]
)

# Normalize straight double-quote (U+0022) → Hebrew gershayim (U+05F4).
# The plus corpus JSON stores sug= values with straight quotes; claim data uses
# gershayim.  Normalizing both sides ensures they compare equal.
_NORM_QUOTES = str.maketrans({'"': "״"})


def _verify_template_set_observed(
    record: ClaimRecord, ctx: Context, *, key: str = "templates"
) -> None:
    """Assert that every declared template appears in both corpus surveys.

    key: the record.data key holding the name(s). If the value is a list,
    every element is checked. If it is a string (e.g. key="template"), it is
    wrapped in a list first.

    Uses the intersection (plain ∩ plus): an mp:both claim asserts that a
    template appears in *both* corpora. Templates expanded to inline text by
    mpplus_boring_tmpls.py appear only in plain; they must not be listed in
    an mp:both claim's data.templates (they should be in an mp:plain claim).

    The reverse direction (observed ∩ declared) is covered by
    verify_mp_both_templates_all_groups_cover_all_observed.
    """
    declared_raw = record.data[key]
    if isinstance(declared_raw, list):
        declared = frozenset(declared_raw)
    else:
        declared = frozenset([declared_raw])
    observed = survey_artifact.template_names_observed_both_intersection(
        ctx.survey, ctx.survey_plain
    )
    missing = declared - observed
    assert (
        not missing
    ), f"declared templates not found in both corpus surveys: {sorted(missing)}"


def verify_mp_both_templates_kq_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared kq-family template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_special_letters_set(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every declared special-letters template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_accents_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared accents template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_poetic_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared poetic template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_other_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared other template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def _verify_footnote_books_only(record: ClaimRecord, ctx: Context) -> None:
    """Assert footnote templates only appear in Torah and Esther books.

    Walks the raw plus corpus and collects every book24_name where a template
    whose name is in record.data["templates"] appears.  Asserts the resulting
    set is a subset of _FOOTNOTE_BOOKS.
    """
    tmpl_names = frozenset(record.data["templates"])
    bad_books: set[str] = set()
    for book39, _ch_key, _v_key, verse in iter_verses(ctx.corpus):
        book = book39["book24_name"]
        if book in _FOOTNOTE_BOOKS:
            continue
        for col in verse:
            for tmpl in iter_template_objects(col):
                if tmpl["tmpl_name"] in tmpl_names:
                    bad_books.add(book)
    assert (
        not bad_books
    ), f"footnote templates found outside Torah/Esther: {sorted(bad_books)}"


def verify_mp_both_templates_footnote(record: ClaimRecord, ctx: Context) -> None:
    """The footnote templates (מ:הערה, מ:הערה-2) appear at least once in the plus corpus
    (per the precomputed tmpl-survey artifact) and only in Torah and Esther books."""
    _verify_template_set_observed(record, ctx)
    _verify_footnote_books_only(record, ctx)


def verify_mp_both_templates_footnote_links_set(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every declared footnote-link template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_structural_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared structural template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


def verify_mp_both_templates_navigation_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared navigation template appears at least once in the plus corpus
    (per the precomputed tmpl-survey artifact)."""
    _verify_template_set_observed(record, ctx)


# ---------------------------------------------------------------------------
# Raw-corpus helpers for named-parameter value checks (B2, B3)
# ---------------------------------------------------------------------------


def _verify_named_param_values_subset(record: ClaimRecord, ctx: Context) -> None:
    """Assert every observed tmpl_params[param] value is among the declared values.

    Walks the raw plus corpus; the survey does not preserve named-parameter values.
    Handles param values stored as plain strings or as 1-element string lists.

    Reads from record.data: "template" (tmpl_name to match), "param" (param key),
    "values" (declared allowed values).
    """
    tmpl_name = record.data["template"]
    param_name = record.data["param"]
    declared = frozenset(v.translate(_NORM_QUOTES) for v in record.data["values"])
    observed: set[str] = set()
    for tmpl in iter_all_template_objects(ctx.corpus):
        if tmpl["tmpl_name"] != tmpl_name:
            continue
        raw = tmpl.get("tmpl_params", {}).get(param_name)
        if raw is None:
            continue
        if isinstance(raw, str):
            observed.add(raw.translate(_NORM_QUOTES))
        elif isinstance(raw, list) and len(raw) == 1 and isinstance(raw[0], str):
            observed.add(raw[0].translate(_NORM_QUOTES))
        else:
            assert False, f"unexpected {param_name}= value structure: {raw!r}"
    unexpected = observed - declared
    assert (
        not unexpected
    ), f"unexpected {param_name}= values in {tmpl_name}: {sorted(unexpected)}"


def verify_mp_both_templates_kq_special_subtypes(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every סוג= value observed for מ:כו״ק מיוחד is among the nine declared subtypes."""
    _verify_named_param_values_subset(record, ctx)


def verify_mp_both_templates_kq_special_subtype_counts(
    record: ClaimRecord, ctx: Context
) -> None:
    """Each kq-special subtype has declared fixed ketiv/qere atom counts."""
    kq_special_counts.verify(record, ctx)


def verify_mp_both_templates_kq_am2_sug_values(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every observed סוג= value in מ:קו״כ-אם-2 is among the declared values."""
    _verify_named_param_values_subset(record, ctx)


# ---------------------------------------------------------------------------
# Global coverage check (B1)
# ---------------------------------------------------------------------------


def verify_mp_both_templates_all_groups_cover_all_observed(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every template observed in either survey is covered by at least one declared group.

    Collects all declared template names from mp.both.templates.*.set,
    mp.both.templates.footnote, and mp.plain.templates.*.set claims in
    REGISTRY, then asserts that every template name observed in either
    corpus survey (union) is in the resulting union of declared templates.
    """
    declared: set[str] = set()
    for cid, rec in REGISTRY.items():
        is_both = cid.startswith("mp.both.templates.") and (
            cid.endswith(".set") or cid == "mp.both.templates.footnote"
        )
        is_plain = cid.startswith("mp.plain.templates.") and cid.endswith(".set")
        is_plus = cid.startswith("mp.plus.templates.") and cid.endswith(".set")
        if not (is_both or is_plain or is_plus):
            continue
        if cid == record.id:
            continue
        d = rec.data
        if "templates" in d:
            declared.update(d["templates"])
        if "template" in d:
            declared.add(d["template"])
    observed = survey_artifact.template_names_observed_both(
        ctx.survey, ctx.survey_plain
    )
    uncovered = observed - declared
    assert (
        not uncovered
    ), f"observed templates not covered by any declared group: {sorted(uncovered)}"
