# Initially generated by GitHub Copilot.
"""MAM-parsed-plus template and file-naming claim verifiers."""

import glob
import re
from collections import Counter
from pathlib import Path
from typing import Callable

from mb_author.claim import ClaimRecord
from mb_cmn import paths
from verify_mp import kq_qere_first_contexts
from verify_mp import kq_special_counts
from verify_mp.corpus import (
    Context,
    iter_all_template_objects,
    iter_template_objects,
    iter_verses,
)

VerifierFn = Callable[[ClaimRecord, Context], None]

# Torah (Pentateuch) + Esther book24_name values — the only books where
# targeted scroll-difference notes (מ:הערה-2) may appear in plus.
_NOTE_BOOKS = frozenset(
    [
        "ספר בראשית",
        "ספר שמות",
        "ספר ויקרא",
        "ספר במדבר",
        "ספר דברים",
        "מגילת אסתר",
    ]
)

# Normalize straight double-quote (U+0022) → Hebrew gershayim (U+05F4).
# The plus corpus JSON stores sug= values with straight quotes; claim data uses
# gershayim.  Normalizing both sides ensures they compare equal.
_NORM_QUOTES = str.maketrans({'"': "״"})


def verify_mp_plus_file_naming_book24_prefixes(
    record: ClaimRecord, ctx: Context
) -> None:
    """Observed plus file-name prefixes match the declared set exactly."""
    del ctx  # This check reads file names directly.
    declared = frozenset(record.data["prefixes"])

    plus_paths = glob.glob(str(paths.mam_parsed_dir() / "plus" / "*.json"))
    assert plus_paths, "no plus JSON files found for file-naming verification"

    def _prefixes(paths: list[str]) -> frozenset[str]:
        result = set()
        for p in paths:
            stem = Path(p).stem
            prefix = stem.split("-", 1)[0]
            result.add(prefix)
        return frozenset(result)

    plus_prefixes = _prefixes(plus_paths)
    assert plus_prefixes == declared, (
        f"plus filename prefixes {sorted(plus_prefixes)}"
        f" != declared {sorted(declared)}"
    )


def _verify_template_set_observed(
    record: ClaimRecord, ctx: Context, *, key: str = "templates"
) -> None:
    """Assert that every declared template appears in the plus corpus.

    key: the record.data key holding the name(s). If the value is a list,
    every element is checked. If it is a string (e.g. key="template"), it is
    wrapped in a list first.

    The reverse direction (observed subset of declared) is covered by
    verify_mp_plus_templates_all_groups_cover_all_observed.
    """
    declared_raw = record.data[key]
    if isinstance(declared_raw, list):
        declared = frozenset(declared_raw)
    else:
        declared = frozenset([declared_raw])
    missing = declared - ctx.template_names
    assert (
        not missing
    ), f"declared templates not found in plus corpus: {sorted(missing)}"


def verify_mp_plus_templates_kq_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared kq-family template appears at least once in the plus corpus."""
    _verify_template_set_observed(record, ctx)


def verify_mp_plus_templates_special_letters_set(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every declared special-letters template appears at least once in the plus corpus."""
    _verify_template_set_observed(record, ctx)


def verify_mp_plus_templates_accents_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared accents template appears at least once in the plus corpus."""
    _verify_template_set_observed(record, ctx)


def verify_mp_plus_templates_poetic_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared poetic template appears at least once in the plus corpus."""
    _verify_template_set_observed(record, ctx)


def verify_mp_plus_templates_other_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared other template appears at least once in the plus corpus."""
    _verify_template_set_observed(record, ctx)


def _iter_template_occurrences_with_ancestors(node, *, ancestors=()):
    """Yield (template_obj, ancestors) pairs from a node tree.

    ancestors is a tuple of (parent_template_name, parent_param_key) pairs
    describing where the current template object was found.
    """
    if isinstance(node, dict):
        if "tmpl_name" in node:
            tmpl_name = node["tmpl_name"]
            yield node, ancestors
            for param_key, param_val in node.get("tmpl_params", {}).items():
                yield from _iter_template_occurrences_with_ancestors(
                    param_val,
                    ancestors=(*ancestors, (tmpl_name, str(param_key))),
                )
        else:
            for value in node.values():
                yield from _iter_template_occurrences_with_ancestors(
                    value,
                    ancestors=ancestors,
                )
    elif isinstance(node, list):
        for item in node:
            yield from _iter_template_occurrences_with_ancestors(
                item,
                ancestors=ancestors,
            )


def _verify_template_only_in_parent_param(record: ClaimRecord, ctx: Context) -> None:
    """Assert a template appears only under a specific parent template param."""
    target = record.data["template"]
    parent_tmpl = record.data["parent_template"]
    parent_param = str(record.data["parent_param"])

    bad: list[str] = []
    seen = 0
    col_letters = ("C", "D", "E")
    for book39, ch_key, v_key, verse in iter_verses(ctx.corpus):
        for col_idx, col in enumerate(verse):
            for tmpl, ancestors in _iter_template_occurrences_with_ancestors(col):
                if tmpl["tmpl_name"] != target:
                    continue
                seen += 1
                in_expected_context = any(
                    anc_name == parent_tmpl and anc_param == parent_param
                    for anc_name, anc_param in ancestors
                )
                if in_expected_context:
                    continue
                anc_text = " > ".join(f"{name}[{param}]" for name, param in ancestors)
                if not anc_text:
                    anc_text = "<root>"
                bad.append(
                    f"{book39['book24_name']} {ch_key}:{v_key}"
                    f" {col_letters[col_idx]} ancestors={anc_text}"
                )

    assert seen, f"template {target!r} not found in plus corpus"
    assert not bad, (
        f"template {target!r} found outside {parent_tmpl!r} param {parent_param!r};"
        f" sample locations: {bad[:5]}"
    )


def verify_mp_plus_templates_modag_only_in_docnote_param2(
    record: ClaimRecord, ctx: Context
) -> None:
    """Template מודגש appears only in נוסח param 2."""
    _verify_template_only_in_parent_param(record, ctx)


def verify_mp_plus_templates_sampe_pabp_arg_value(
    record: ClaimRecord, ctx: Context
) -> None:
    """When סס/ססס/פפ/פפפ have positional param 1, it must equal the declared arg_value."""
    expected = record.data["arg_value"]
    templates = frozenset(record.data["templates"])
    bad = []

    def _normalize_param_1(val):
        if isinstance(val, str):
            return val
        if isinstance(val, list):
            return "".join(val)
        return None

    for tmpl in iter_all_template_objects(ctx.corpus):
        if tmpl["tmpl_name"] not in templates:
            continue
        params = tmpl.get("tmpl_params", {})
        if "1" not in params:
            continue
        val = params["1"]
        if _normalize_param_1(val) != expected:
            bad.append(f"{tmpl['tmpl_name']} param 1 = {val!r}")
    assert not bad, f"unexpected param 1 values: {bad[:5]}"


def verify_mp_plus_templates_sh_only_in_docnote_param2(
    record: ClaimRecord, ctx: Context
) -> None:
    """Template ש appears only in נוסח param 2."""
    _verify_template_only_in_parent_param(record, ctx)


def verify_mp_plus_templates_note_link_external_only_in_docnote_param2(
    record: ClaimRecord, ctx: Context
) -> None:
    """Template מ:קישור בהערה appears only in נוסח param 2."""
    _verify_template_only_in_parent_param(record, ctx)


def verify_mp_plus_templates_note_link_internal_only_in_docnote_param2(
    record: ClaimRecord, ctx: Context
) -> None:
    """Template מ:קישור פנימי בהערה appears only in נוסח param 2."""
    _verify_template_only_in_parent_param(record, ctx)


def _verify_note_books_only(record: ClaimRecord, ctx: Context) -> None:
    """Assert note templates only appear in Torah and Esther books.

    Walks the raw plus corpus and collects every book24_name where a template
    whose name is in record.data["templates"] appears. Asserts the resulting
    set is a subset of _NOTE_BOOKS.
    """
    tmpl_names = frozenset(record.data["templates"])
    bad_books: set[str] = set()
    for book39, _ch_key, _v_key, verse in iter_verses(ctx.corpus):
        book = book39["book24_name"]
        if book in _NOTE_BOOKS:
            continue
        for col in verse:
            for tmpl in iter_template_objects(col):
                if tmpl["tmpl_name"] in tmpl_names:
                    bad_books.add(book)
    assert (
        not bad_books
    ), f"note templates found outside Torah/Esther: {sorted(bad_books)}"


def verify_mp_plus_templates_note(record: ClaimRecord, ctx: Context) -> None:
    """Template מ:הערה-2 appears in plus and only in Torah and Esther books."""
    _verify_template_set_observed(record, ctx)
    _verify_note_books_only(record, ctx)


def _verify_template_set_listed_in_docs_claims(
    record: ClaimRecord, ctx: Context, *, docs_claim_ids: tuple[str, ...]
) -> None:
    """Assert declared templates are listed in each provided docs-template claim."""
    assert (
        ctx.claim_records is not None
    ), "ctx.claim_records was not provided to verifier context"
    declared = frozenset(record.data["templates"])
    for claim_id in docs_claim_ids:
        docs_claim = ctx.claim_records[claim_id]
        listed = frozenset(docs_claim.data["templates"])
        missing = declared - listed
        assert (
            not missing
        ), f"templates from {record.id} missing in {claim_id}: {sorted(missing)}"


def verify_mp_plus_templates_note_links_set(record: ClaimRecord, ctx: Context) -> None:
    """Declared note-link templates are observed and listed in the plus docs."""
    _verify_template_set_observed(record, ctx)
    _verify_template_set_listed_in_docs_claims(
        record,
        ctx,
        docs_claim_ids=("mp.plus.docs.common-templates.templates-in-plus-survey",),
    )


def verify_mp_plus_templates_structural_set(record: ClaimRecord, ctx: Context) -> None:
    """Declared structural templates are observed and listed in the plus docs."""
    _verify_template_set_observed(record, ctx)
    _verify_template_set_listed_in_docs_claims(
        record,
        ctx,
        docs_claim_ids=("mp.plus.docs.common-templates.templates-in-plus-survey",),
    )


def verify_mp_plus_templates_navigation_set(record: ClaimRecord, ctx: Context) -> None:
    """Every declared navigation template appears at least once in the plus corpus."""
    _verify_template_set_observed(record, ctx)


# ---------------------------------------------------------------------------
# Raw-corpus helpers for named-parameter value checks (B2, B3)
# ---------------------------------------------------------------------------


def _verify_named_param_values_subset(record: ClaimRecord, ctx: Context) -> None:
    """Assert every observed tmpl_params[param] value is among the declared values.

    Walks the raw plus corpus; the survey does not preserve named-parameter values.
    Handles param values stored as plain strings or as 1-element string lists.

    Reads from record.data: "template" (tmpl_name to match), "param" (param key),
    "values" (declared allowed values).
    """
    tmpl_name = record.data["template"]
    param_name = record.data["param"]
    declared = frozenset(v.translate(_NORM_QUOTES) for v in record.data["values"])
    observed: set[str] = set()
    for tmpl in iter_all_template_objects(ctx.corpus):
        if tmpl["tmpl_name"] != tmpl_name:
            continue
        raw = tmpl.get("tmpl_params", {}).get(param_name)
        if raw is None:
            continue
        if isinstance(raw, str):
            observed.add(raw.translate(_NORM_QUOTES))
        elif isinstance(raw, list) and len(raw) == 1 and isinstance(raw[0], str):
            observed.add(raw[0].translate(_NORM_QUOTES))
        else:
            assert False, f"unexpected {param_name}= value structure: {raw!r}"
    unexpected = observed - declared
    assert (
        not unexpected
    ), f"unexpected {param_name}= values in {tmpl_name}: {sorted(unexpected)}"


def verify_mp_plus_templates_kq_special_subtypes(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every סוג= value observed for מ:כו״ק מיוחד is among the nine declared subtypes."""
    _verify_named_param_values_subset(record, ctx)


def verify_mp_plus_templates_kq_special_subtype_counts(
    record: ClaimRecord, ctx: Context
) -> None:
    """Each kq-special subtype has declared fixed ketiv/qere atom counts."""
    kq_special_counts.verify(record, ctx)


def verify_mp_plus_templates_kq_am2_sug_values(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every observed סוג= value in מ:קו״כ-אם-2 is among the declared values."""
    _verify_named_param_values_subset(record, ctx)


def verify_mp_plus_templates_kq_qere_first_contexts(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every qere-first ketiv/qere follows a maqaf, except at the declared verses,
    where a קו״כ follows a narrow-sense paseq."""
    kq_qere_first_contexts.verify(record, ctx)


# ---------------------------------------------------------------------------
# Global coverage check (B1)
# ---------------------------------------------------------------------------


def verify_mp_plus_templates_all_groups_cover_all_observed(
    record: ClaimRecord, ctx: Context
) -> None:
    """Every template the plus corpus calls is covered by a declared group.

    Collects all declared template names from mp.plus.templates.*.set and
    mp.plus.templates.note claims, then checks the corpus's templates against their union.
    """
    assert (
        ctx.claim_records is not None
    ), "ctx.claim_records was not provided to verifier context"
    declared: set[str] = set()
    for cid, rec in ctx.claim_records.items():
        is_plus = cid.startswith("mp.plus.templates.") and (
            cid.endswith(".set") or cid == "mp.plus.templates.note"
        )
        if not is_plus:
            continue
        if cid == record.id:
            continue
        d = rec.data
        if "templates" in d:
            declared.update(d["templates"])
        if "template" in d:
            declared.add(d["template"])
    uncovered = ctx.template_names - declared
    assert (
        not uncovered
    ), f"observed templates not covered by any declared group: {sorted(uncovered)}"


# ---------------------------------------------------------------------------
# Figures the documentation states in words
# ---------------------------------------------------------------------------


def _template_sites(ctx: Context, template_name: str):
    """Yield ((book24, sub-book, chapter, verse, column index), template) for every call."""
    for book39, ch_key, v_key, verse in iter_verses(ctx.corpus):
        for column_index, column in enumerate(verse):
            for tmpl in iter_template_objects(column):
                if tmpl["tmpl_name"] == template_name:
                    site = (
                        book39["book24_name"],
                        book39["sub_book_name"],
                        ch_key,
                        v_key,
                        column_index,
                    )
                    yield site, tmpl


def _param_text(tmpl: dict, key: str):
    """A parameter's value as text, whether stored as a string or as a one-string list."""
    value = tmpl.get("tmpl_params", {}).get(key)
    if isinstance(value, list) and len(value) == 1 and isinstance(value[0], str):
        return value[0]
    return value


def _assert_sites(observed: Counter, declared, what: str) -> None:
    """Assert that the observed sites are the declared ones, each as often as declared."""
    expected = Counter(tuple(site) for site in declared)
    assert observed == expected, (
        f"{what}: at {sorted(observed.items(), key=repr)},"
        f" declared at {sorted(expected.items(), key=repr)}"
    )


def verify_mp_plus_templates_r1_in_column_c(record: ClaimRecord, ctx: Context) -> None:
    """The template stands in column C once in each declared chapter and nowhere else."""
    data = record.data
    observed = Counter(
        (book24, sub_book, chapter)
        for (book24, sub_book, chapter, _verse, column), _tmpl in _template_sites(
            ctx, data["template"]
        )
        if column == data["column"]
    )
    _assert_sites(observed, data["where"], f"{data['template']} in column C")


def verify_mp_plus_templates_shirah_divider_sections(
    record: ClaimRecord, ctx: Context
) -> None:
    """The song-section divider is in exactly the declared number of chapters.

    A section is counted by its chapter: the divider need not mark every verse of a song,
    so a run of consecutive verses with the divider is not a section.
    """
    data = record.data
    chapters = {
        (book24, sub_book, chapter)
        for (book24, sub_book, chapter, _verse, _column), _tmpl in _template_sites(
            ctx, data["template"]
        )
    }
    assert len(chapters) == data["sections"], (
        f"{data['template']} is in {len(chapters)} chapters, not {data['sections']}:"
        f" {sorted(chapters, key=repr)}"
    )


def verify_mp_plus_templates_new_book_at_each_book_start(
    record: ClaimRecord, ctx: Context
) -> None:
    """The new-book marker opens each book, once, at the first verse of its first book39."""
    data = record.data
    starts = {}
    for book39 in ctx.corpus.book39s:
        chapter = next(iter(book39["chapters"]))
        verse = next(iter(book39["chapters"][chapter]))
        starts.setdefault(
            book39["book24_name"], (book39["sub_book_name"], chapter, verse)
        )
    assert len(starts) == data["books"], f"{len(starts)} books, not {data['books']}"
    observed = Counter(
        (book24, sub_book, chapter, verse)
        for (book24, sub_book, chapter, verse, _column), _tmpl in _template_sites(
            ctx, data["template"]
        )
    )
    _assert_sites(
        observed,
        [(book24, *start) for book24, start in starts.items()],
        data["template"],
    )


def verify_mp_plus_templates_no_par_weekly_where(
    record: ClaimRecord, ctx: Context
) -> None:
    """The template is called exactly at the declared verses, once each."""
    data = record.data
    observed = Counter(
        (book24, sub_book, chapter, verse)
        for (book24, sub_book, chapter, verse, _column), _tmpl in _template_sites(
            ctx, data["template"]
        )
    )
    _assert_sites(observed, data["where"], data["template"])


def verify_mp_plus_template_haarah_2_star_first_where(
    record: ClaimRecord, ctx: Context
) -> None:
    """The declared parameter value is given exactly at the declared verses, once each."""
    data = record.data
    observed = Counter(
        (book24, sub_book, chapter, verse)
        for (book24, sub_book, chapter, verse, _column), tmpl in _template_sites(
            ctx, data["template"]
        )
        if _param_text(tmpl, data["param"]) == data["value"]
    )
    _assert_sites(
        observed,
        data["where"],
        f"{data['template']} with {data['param']}={data['value']}",
    )


def verify_mp_plus_templates_meteg_accent_one_letter_wikisource_cases(
    record: ClaimRecord, ctx: Context
) -> None:
    """The Wikisource download calls the template exactly the declared number of times.

    Counted in in/mam-ws/ rather than in the plus corpus, because the parse resolves the
    template into the marks it stands for.
    """
    del ctx  # This check reads the Wikisource download directly.
    data = record.data
    call = re.compile(re.escape("{{" + data["template"]) + r"\s*[|}]")
    files = sorted((paths.in_dir() / "mam-ws").glob("*.json"))
    assert files, "no Wikisource download under in/mam-ws/"
    count = sum(len(call.findall(path.read_text(encoding="utf-8"))) for path in files)
    assert (
        count == data["cases"]
    ), f"{data['template']}: {count} calls, not {data['cases']}"


REGISTRY: dict[str, VerifierFn] = {
    "mp.plus.template.haarah-2.star-first-where": verify_mp_plus_template_haarah_2_star_first_where,
    "mp.plus.templates.meteg-accent-one-letter.wikisource-cases": verify_mp_plus_templates_meteg_accent_one_letter_wikisource_cases,
    "mp.plus.templates.new-book.at-each-book-start": verify_mp_plus_templates_new_book_at_each_book_start,
    "mp.plus.templates.no-par-weekly.where": verify_mp_plus_templates_no_par_weekly_where,
    "mp.plus.templates.r1.in-column-c": verify_mp_plus_templates_r1_in_column_c,
    "mp.plus.templates.shirah-divider.sections": verify_mp_plus_templates_shirah_divider_sections,
    "mp.plus.file-naming.book24-prefixes": verify_mp_plus_file_naming_book24_prefixes,
    "mp.plus.templates.accents.set": verify_mp_plus_templates_accents_set,
    "mp.plus.templates.all-groups-cover-all-observed": verify_mp_plus_templates_all_groups_cover_all_observed,
    "mp.plus.templates.kq-am2.sug-values": verify_mp_plus_templates_kq_am2_sug_values,
    "mp.plus.templates.kq-special.subtype-counts": verify_mp_plus_templates_kq_special_subtype_counts,
    "mp.plus.templates.kq-special.subtypes": verify_mp_plus_templates_kq_special_subtypes,
    "mp.plus.templates.kq.qere-first-contexts": verify_mp_plus_templates_kq_qere_first_contexts,
    "mp.plus.templates.kq.set": verify_mp_plus_templates_kq_set,
    "mp.plus.templates.modag.only-in-docnote-param2": verify_mp_plus_templates_modag_only_in_docnote_param2,
    "mp.plus.templates.note-link-external.only-in-docnote-param2": verify_mp_plus_templates_note_link_external_only_in_docnote_param2,
    "mp.plus.templates.note-link-internal.only-in-docnote-param2": verify_mp_plus_templates_note_link_internal_only_in_docnote_param2,
    "mp.plus.templates.navigation.set": verify_mp_plus_templates_navigation_set,
    "mp.plus.templates.note": verify_mp_plus_templates_note,
    "mp.plus.templates.note-links.set": verify_mp_plus_templates_note_links_set,
    "mp.plus.templates.other.set": verify_mp_plus_templates_other_set,
    "mp.plus.templates.poetic.set": verify_mp_plus_templates_poetic_set,
    "mp.plus.templates.sampe.pabp-arg-value": verify_mp_plus_templates_sampe_pabp_arg_value,
    "mp.plus.templates.sh.only-in-docnote-param2": verify_mp_plus_templates_sh_only_in_docnote_param2,
    "mp.plus.templates.special-letters.set": verify_mp_plus_templates_special_letters_set,
    "mp.plus.templates.structural.set": verify_mp_plus_templates_structural_set,
}
