# Initially generated by GitHub Copilot.
"""Normalize special ketiv/qere template forms across old and unified names."""

from mb_cmn import template_names as tmpln

UNIFIED_SPECIAL_KQ_TEMPLATE_NAME = 'מ:כו"ק מיוחד'

OLD_SPECIAL_KQ_TEMPLATE_NAMES = (
    tmpln.K1Q1_MCOM,
    tmpln.K1Q2_SR_KQQ,
    tmpln.K1Q2_SR_QQK,
    tmpln.K1Q2_SR_BCOM,
    tmpln.K1Q2_WR_KQQ,
    tmpln.K1Q2_UR_QQK,
    tmpln.K2Q1,
    tmpln.K2Q2,
    tmpln.K3Q3,
)

_SPECIAL_KQ_TYPE_FROM_OLD_NAME = {
    old_name: tmpln.LATIN_SHORTS[old_name] for old_name in OLD_SPECIAL_KQ_TEMPLATE_NAMES
}
_SPECIAL_KQ_OLD_NAME_FROM_SUG = {
    old_name.removeprefix("מ:"): old_name for old_name in OLD_SPECIAL_KQ_TEMPLATE_NAMES
}

SPECIAL_KQ_TYPE_KEYS = tuple(
    _SPECIAL_KQ_TYPE_FROM_OLD_NAME[old_name]
    for old_name in OLD_SPECIAL_KQ_TEMPLATE_NAMES
)


def is_unified_special_kq_template_name(template_name):
    return template_name == UNIFIED_SPECIAL_KQ_TEMPLATE_NAME


def is_old_special_kq_template_name(template_name):
    return template_name in _SPECIAL_KQ_TYPE_FROM_OLD_NAME


def is_special_kq_template_name(template_name):
    return is_old_special_kq_template_name(
        template_name
    ) or is_unified_special_kq_template_name(template_name)


def sug_text_for_old_special_kq_template_name(old_template_name):
    assert is_old_special_kq_template_name(old_template_name), old_template_name
    assert old_template_name.startswith("מ:"), old_template_name
    return old_template_name.removeprefix("מ:")


def _canonical_old_name_for_unified_sug(sug_text):
    assert isinstance(sug_text, str), sug_text
    assert sug_text in _SPECIAL_KQ_OLD_NAME_FROM_SUG, sug_text
    return _SPECIAL_KQ_OLD_NAME_FROM_SUG[sug_text]


def canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text=None):
    """Return the canonical old template name for a special-kq template call.

    For old-form names this returns template_name itself.
    For unified-form calls (מ:כו"ק מיוחד) this resolves from סוג=... .
    """
    assert is_special_kq_template_name(template_name), template_name
    if is_old_special_kq_template_name(template_name):
        if sug_text is not None:
            assert sug_text == sug_text_for_old_special_kq_template_name(
                template_name
            ), (
                template_name,
                sug_text,
            )
        return template_name

    assert is_unified_special_kq_template_name(template_name), template_name
    assert sug_text is not None, template_name
    return _canonical_old_name_for_unified_sug(sug_text)


def canonical_special_kq_type_from_name_and_sug(template_name, sug_text=None):
    """Return canonical k/q subtype key (for example k1q2-sr-kqq)."""
    old_name = canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text)
    return _SPECIAL_KQ_TYPE_FROM_OLD_NAME[old_name]


def maybe_special_kq_type_from_name_and_sug(template_name, sug_text=None):
    """Return canonical subtype for special-kq templates, else None."""
    if not is_special_kq_template_name(template_name):
        return None
    return canonical_special_kq_type_from_name_and_sug(template_name, sug_text)


def maybe_canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text=None):
    """Return canonical old special-kq template name, or None if not special-kq."""
    if not is_special_kq_template_name(template_name):
        return None
    return canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text)
