# Initially generated by GitHub Copilot.
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from repo_util.common import (
    local_date_from_git_iso8601,
    read_json,
    run_cmd,
    today_local_date,
)


@dataclass(frozen=True)
class RepoInfo:
    path: Path
    head_commit: str | None
    head_committer_iso: str | None

    @property
    def name(self) -> str:
        return self.path.name


def _resolve_repo_path(folder_path: str, workspace_dir: Path, repos_root: Path) -> Path:
    candidate = Path(folder_path)
    if candidate.is_absolute():
        return candidate.resolve()

    workspace_relative = (workspace_dir / folder_path).resolve()
    if workspace_relative.exists():
        return workspace_relative

    repos_root_relative = (repos_root / folder_path).resolve()
    if repos_root_relative.exists():
        return repos_root_relative

    return workspace_relative


def load_workspace_repo_dirs(workspace_file: Path, repos_root: Path) -> list[Path]:
    workspace = read_json(workspace_file)
    workspace_dir = workspace_file.parent
    repo_dirs: list[Path] = []

    for folder in workspace["folders"]:
        repo_dir = _resolve_repo_path(folder["path"], workspace_dir, repos_root)
        if not repo_dir.is_dir():
            raise FileNotFoundError(f"Workspace folder not found: {repo_dir}")
        repo_dirs.append(repo_dir)

    return repo_dirs


def _select_explicit_repos(
    repo_dirs: Sequence[Path],
    *,
    repos: Sequence[str] | None,
    workspace_dir: Path,
    repos_root: Path,
) -> list[Path]:
    if not repos:
        return list(repo_dirs)

    selected: list[Path] = []
    for token in repos:
        token_lc = token.casefold()
        token_as_path = Path(token)
        token_abs = token_as_path.resolve()
        token_workspace = (workspace_dir / token).resolve()
        token_root = (repos_root / token).resolve()

        match = None
        for repo_dir in repo_dirs:
            if repo_dir.name.casefold() == token_lc:
                match = repo_dir
                break
            if str(repo_dir).casefold() == str(token_abs).casefold():
                match = repo_dir
                break
            if str(repo_dir).casefold() == str(token_workspace).casefold():
                match = repo_dir
                break
            if str(repo_dir).casefold() == str(token_root).casefold():
                match = repo_dir
                break

        if match is None:
            raise ValueError(
                f"Requested repo was not found in workspace folders: {token}"
            )
        if match not in selected:
            selected.append(match)

    return selected


def _is_git_repo(repo_dir: Path) -> bool:
    result = run_cmd(["git", "-C", str(repo_dir), "rev-parse", "--is-inside-work-tree"])
    return result.returncode == 0 and result.stdout.strip() == "true"


def _get_head_info(repo_dir: Path) -> tuple[str | None, str | None]:
    result = run_cmd(
        ["git", "-C", str(repo_dir), "log", "-1", "--pretty=format:%H|%cI"]
    )
    text = result.stdout.strip()
    if result.returncode != 0 or "|" not in text:
        return None, None
    commit_sha, committer_iso = text.split("|", 1)
    return commit_sha, committer_iso


def select_repo_infos(
    workspace_file: Path,
    *,
    repos_root: Path,
    repos: Sequence[str] | None,
    today_only: bool,
) -> list[RepoInfo]:
    workspace_file = workspace_file.resolve()
    workspace_dir = workspace_file.parent
    repo_dirs = load_workspace_repo_dirs(workspace_file, repos_root)
    repo_dirs = _select_explicit_repos(
        repo_dirs,
        repos=repos,
        workspace_dir=workspace_dir,
        repos_root=repos_root,
    )

    selected: list[RepoInfo] = []
    today = today_local_date()

    for repo_dir in repo_dirs:
        if not _is_git_repo(repo_dir):
            continue

        head_commit, head_committer_iso = _get_head_info(repo_dir)
        if today_only:
            if head_committer_iso is None:
                continue
            if local_date_from_git_iso8601(head_committer_iso) != today:
                continue

        selected.append(
            RepoInfo(
                path=repo_dir,
                head_commit=head_commit,
                head_committer_iso=head_committer_iso,
            )
        )

    return selected
