# Initially generated by GitHub Copilot.
from mb_cmn import template_names as tmpln
from mb_cmn import ws_tmpl2 as wtp
from mb_cmn.my_utils import sl_map
from mb_cmn.my_utils import sum_of_seqs
from mb_misc import hebrew_letter_words as hlw
from py_misc import wt_qere
from py_misc.split import my_re_split


def verse_word_tokens(minirow):
    return wtseq_word_tokens(minirow.EP)


def wtseq_word_tokens(wtseq):
    verse_text = "".join(_flatten_wtseq(wtseq))
    rough_tokens = my_re_split(r"[ ]+", verse_text)
    clean_tokens = tuple(filter(None, (_clean_token(token) for token in rough_tokens)))
    return clean_tokens


def range_label_for_minirow(minirow):
    return range_label_for_wtseq(minirow.EP)


def range_label_for_minirow_span(start_minirow, end_minirow):
    start_tokens = verse_word_tokens(start_minirow)
    end_tokens = verse_word_tokens(end_minirow)
    if start_tokens[0] in {"לא", "ולא"}:
        second_token = start_tokens[1]
        if second_token.endswith(start_tokens[0]) and second_token != start_tokens[0]:
            second_token = second_token[: -len(start_tokens[0])]
        return (
            _display_initial_token(start_tokens[0])
            + " "
            + second_token
            + "…"
            + _display_final_token(end_tokens[-1])
        )
    return (
        _display_initial_token(start_tokens[0])
        + "…"
        + _display_final_token(end_tokens[-1])
    )


def range_label_for_wtseq(wtseq):
    tokens = wtseq_word_tokens(wtseq)
    if len(tokens) == 1:
        return _display_initial_token(_display_final_token(tokens[0]))
    if len(tokens) == 2:
        return (
            _display_initial_token(tokens[0]) + " " + _display_final_token(tokens[-1])
        )
    if tokens[0] in {"לא", "ולא"}:
        second_token = tokens[1]
        if second_token.endswith(tokens[0]) and second_token != tokens[0]:
            second_token = second_token[: -len(tokens[0])]
        return (
            _display_initial_token(tokens[0])
            + " "
            + second_token
            + "…"
            + _display_final_token(tokens[-1])
        )
    return f"{_display_initial_token(tokens[0])}…{_display_final_token(tokens[-1])}"


def first_two_word_label_for_wtseq(wtseq):
    tokens = wtseq_word_tokens(wtseq)
    assert len(tokens) >= 2
    second_token = tokens[1]
    if second_token.endswith(tokens[0]) and second_token != tokens[0]:
        second_token = second_token[: -len(tokens[0])]
    return _display_initial_token(tokens[0]) + " " + second_token


def _clean_token(token):
    return hlw.letters_and_maqafs(token)


def _display_final_token(token):
    if token.startswith("על־"):
        return token.split("־", 1)[1]
    return token


def _display_initial_token(token):
    special = {
        "לא־יהיה־לך": "לא יהיה",
        "לא־תעשה־לך": "לא־תעשה",
    }
    return special.get(token, token)


def _flatten_wtseq(wtseq):
    qere = wt_qere.do_one_wtseq(wt_qere.HANDLERS, wtseq)
    return tuple(sum_of_seqs(_flatten_wtel(wtel) for wtel in qere))


def _flatten_wtel(wtel):
    if isinstance(wtel, str):
        return (wtel,)
    tmpl_name = wtp.template_name(wtel)
    return _STAGE_2_HANDLERS[tmpl_name](wtel)


def _recurse_on_param_vals(tmpl):
    return sum_of_seqs(wtp.map_params(_flatten_wtseq, tmpl))


def _hnd_return_empty(_tmpl):
    return tuple()


def _hnd_slh_word(tmpl):
    quad1 = [wtp.template_param_val(tmpl, key) for key in ("2", "3", "4", "5")]
    quad2 = sl_map(lambda seq: "".join(seq), quad1)
    return ("".join(quad2),)


_STAGE_2_HANDLERS = {
    "מ:דחי": _recurse_on_param_vals,
    "מ:צינור": _recurse_on_param_vals,
    "מ:קמץ": _recurse_on_param_vals,
    "מ:כפול": _recurse_on_param_vals,
    tmpln.SLH_WORD: _hnd_slh_word,
    "מ:פסק": _hnd_return_empty,
}
