# Initially generated by GitHub Copilot.
"""Slide definitions for the 'What is MAM?' deck.

Slides
------
title-card      "What is MAM?" with Hebrew subtitle
closing-card    "What will *you* create with MAM?"
json-snippet    Syntax-colored JSON excerpt
"""

import pathlib

from bidi.algorithm import get_display
from PIL import ImageFont

from py_misc import json_snippet_slide
from slide_generator import slide_render

DECK_NAME = "what-is-mam"
IMAGES_DIR = pathlib.Path("misc/what-is-mam/img")

# Teal gradient shared across all slides in this deck
_TOP_RGB = (13, 94, 87)
_BOT_RGB = (8, 61, 56)


def _gradient():
    return slide_render.make_gradient(_TOP_RGB, _BOT_RGB)


def render_title_card(**kwargs):
    """Render slide-title-card.png."""
    font_bold = ImageFont.truetype(str(slide_render.FONT_DIR / "arialbd.ttf"), size=180)
    font_reg = ImageFont.truetype(str(slide_render.FONT_DIR / "arial.ttf"), size=96)
    lines = [
        ("What is MAM?", font_bold, (255, 255, 255)),
        ("Miqra According to the Masorah", font_reg, (200, 232, 228)),
        # bidi-reordered so Pillow renders RTL correctly
        (
            get_display("מקרא על פי המסורה"),
            font_reg,
            (200, 232, 228),
        ),
    ]
    img = _gradient()
    slide_render.draw_centered_lines(img, lines, gap_after=[80, 40, 0])
    dest = IMAGES_DIR / "slide-title-card.png"
    dest.parent.mkdir(parents=True, exist_ok=True)
    img.save(dest)
    slide_render.write_provenance(dest, DECK_NAME, "title-card")
    print(f"Saved {dest} {img.size}")


def render_closing_card(**kwargs):
    """Render slide-closing-card.png."""
    font_size = 162  # 10% smaller than title card's 180
    font_bold = ImageFont.truetype(
        str(slide_render.FONT_DIR / "arialbd.ttf"), size=font_size
    )
    font_bold_it = ImageFont.truetype(
        str(slide_render.FONT_DIR / "arialbi.ttf"), size=font_size
    )
    # Split so "you" can be rendered in bold italic
    segments = [
        ("What will ", font_bold, (255, 255, 255)),
        ("you", font_bold_it, (255, 255, 255)),
        (" create with MAM?", font_bold, (255, 255, 255)),
    ]
    img = _gradient()
    from PIL import ImageDraw

    draw = ImageDraw.Draw(img)
    bboxes = [draw.textbbox((0, 0), text, font=font) for text, font, _ in segments]
    widths = [bb[2] - bb[0] for bb in bboxes]
    total_width = sum(widths)
    # Vertical center based on ink extents across all segments
    top = min(bb[1] for bb in bboxes)
    bot = max(bb[3] for bb in bboxes)
    y = slide_render.H // 2 - (top + bot) // 2
    x = (slide_render.W - total_width) // 2
    for (text, font, color), bb, w in zip(segments, bboxes, widths):
        draw.text((x - bb[0], y), text, font=font, fill=color)
        x += w
    dest = IMAGES_DIR / "slide-closing-card.png"
    dest.parent.mkdir(parents=True, exist_ok=True)
    img.save(dest)
    slide_render.write_provenance(dest, DECK_NAME, "closing-card")
    print(f"Saved {dest} {img.size}")


def render_json_snippet(**kwargs):
    """Render slide-json-snippet.png with syntax-colored JSON."""
    json_snippet_slide.render_json_snippet(IMAGES_DIR, _gradient, DECK_NAME)


ALL_SLIDES = {
    "title-card": render_title_card,
    "closing-card": render_closing_card,
    "json-snippet": render_json_snippet,
}
