# Initially generated by GitHub Copilot.
from mb_cmn import uni_heb_2 as u2


def revia_label(mid_parts=()):
    return _label("⅃-leg", ("plain", "rev"), _mid("counted", mid_parts))


def non_revia_label(stop, mid_parts=()):
    return _label("⅃-leg", ("non-revia", stop), _mid("counted", mid_parts))


def munpas_pazer_label(mid_parts=(), style="counted"):
    return _label("⅃-pas", ("plain", "paz"), _mid(style, mid_parts))


def explanation_for_path(path_parts):
    if not path_parts:
        return None
    return _EXPLANATIONS_BY_LABEL.get(path_parts[-1])


OVERALL_EXPLANATION = (
    "This page groups pasoleg-related accent patterns, especially munaḥ legarmeih and munaḥ paseq sequences together with their most characteristic stopping accents.",
    "The compact labels summarize the starting pattern, the stopping pattern, and how many accents intervene. Prefixes such as dualcant/upper and dualcant/lower mark the upper and lower cantillation systems in the dual-cantillation passages.",
)


def _label(start, stop, mid):
    stop_text = _stop_short(stop)
    mid_text = _mid_short(mid)
    return f"{start}...{stop_text} with {mid_text} intervening"


def _explanation(start, stop, mid):
    start_text = _TOKEN_LONG_NAMES[start]
    stop_text = _stop_long(stop)
    mid_text = _mid_long(mid)
    return f"{start_text} preceding {stop_text} {mid_text}"


def _mid(style, parts):
    return style, tuple(parts)


def _stop_short(stop):
    kind, token = stop
    token_text = _TOKEN_SHORT_NAMES[token]
    if kind == "non-revia":
        return f"non-revia ({token_text})"
    return token_text


def _stop_long(stop):
    kind, token = stop
    token_text = _TOKEN_LONG_NAMES[token]
    if kind == "non-revia":
        return f"a non-revia pattern ending in {token_text}"
    return token_text


def _mid_short(mid):
    style, parts = mid
    if not parts:
        return "0"
    if style == "bare":
        assert len(parts) == 1, parts
        return _TOKEN_SHORT_NAMES[parts[0]]
    if len(parts) == 1:
        return f"1 {_TOKEN_SHORT_NAMES[parts[0]]}"
    parts_text = ",".join(_TOKEN_SHORT_NAMES[part] for part in parts)
    return f"{len(parts)} ({parts_text})"


def _mid_long(mid):
    style, parts = mid
    if not parts:
        return "with no accents intervening"
    count_name = _COUNT_NAMES[len(parts)]
    plural = "accent" if len(parts) == 1 else "accents"
    accents_text = _join_with_and(_TOKEN_LONG_NAMES[part] for part in parts)
    return f"with {count_name} {plural} intervening: {accents_text}"


def _join_with_and(items):
    items = tuple(items)
    if len(items) == 1:
        return items[0]
    if len(items) == 2:
        return f"{items[0]} and {items[1]}"
    return ", ".join(items[:-1]) + f", and {items[-1]}"


_COUNT_NAMES = {
    1: "one",
    2: "two",
    3: "three",
}


_TOKEN_SHORT_NAMES = {
    "da": "da",
    "ge": "ge",
    "mah": u2.MAH,
    "p": "p",
    "paz": u2.PAZ,
    "qa": "qa",
    "rev": u2.REV,
    "tev": u2.TEV,
    "⅃": "⅃",
    "⅃-leg": "⅃-leg",
    "⅃-pas": "⅃-pas",
}


_TOKEN_LONG_NAMES = {
    "da": "darga",
    "ge": "geresh",
    "mah": "mahapakh",
    "p": "pashta",
    "paz": "pazer",
    "qa": "qadma",
    "rev": "revia",
    "tev": "tevir",
    "⅃": "munaḥ",
    "⅃-leg": "munaḥ legarmeih",
    "⅃-pas": "munaḥ paseq",
}


_EXPLANATIONS_BY_LABEL = {
    revia_label(): _explanation("⅃-leg", ("plain", "rev"), _mid("counted", ())),
    revia_label(("⅃",)): _explanation(
        "⅃-leg", ("plain", "rev"), _mid("counted", ("⅃",))
    ),
    revia_label(("⅃-leg", "⅃")): _explanation(
        "⅃-leg", ("plain", "rev"), _mid("counted", ("⅃-leg", "⅃"))
    ),
    revia_label(("da", "⅃")): _explanation(
        "⅃-leg", ("plain", "rev"), _mid("counted", ("da", "⅃"))
    ),
    non_revia_label("p", ("mah",)): _explanation(
        "⅃-leg", ("non-revia", "p"), _mid("counted", ("mah",))
    ),
    non_revia_label("tev", ("qa", "da")): _explanation(
        "⅃-leg", ("non-revia", "tev"), _mid("counted", ("qa", "da"))
    ),
    non_revia_label("ge", ("qa",)): _explanation(
        "⅃-leg", ("non-revia", "ge"), _mid("counted", ("qa",))
    ),
    non_revia_label("paz"): _explanation(
        "⅃-leg", ("non-revia", "paz"), _mid("counted", ())
    ),
    munpas_pazer_label(("⅃", "⅃")): _explanation(
        "⅃-pas", ("plain", "paz"), _mid("counted", ("⅃", "⅃"))
    ),
    munpas_pazer_label(("⅃", "⅃-pas")): _explanation(
        "⅃-pas", ("plain", "paz"), _mid("counted", ("⅃", "⅃-pas"))
    ),
    munpas_pazer_label(): _explanation("⅃-pas", ("plain", "paz"), _mid("counted", ())),
    munpas_pazer_label(("⅃-pas",), style="bare"): _explanation(
        "⅃-pas", ("plain", "paz"), _mid("bare", ("⅃-pas",))
    ),
    "⅃-pas,(rev)": "munaḥ paseq preceding revia",
    "⅃-pas-⅃": "munaḥ paseq preceding munaḥ legarmeih",
    "shalshelet": "shalshelet legarmeih",
}
