# Initially generated by GitHub Copilot.

_QQ_ACCENT_NAMES = {
    "(dex)": "deḥi",
    "(ger_m)": "geresh muqdam",
    "(mer)": "merkha",
    "(mos)": "meteg or silluq",
    "(mun)": "munaḥ",
    "(ole)": "oleh",
    "(qom)": "qadma or metigah",
    "(tel_g)": "telisha gedolah",
}

_NOTE_QUALIFIER_EXPLANATIONS = {
    "doc-part-n": " ".join(
        (
            "The examples in this subsection occur inside a documentation note rather",
            "than directly in the running text.",
        )
    ),
    "scrdfftar-note": (
        "The examples in this subsection occur inside a scroll-difference note."
    ),
}


def explanation_for_path(path_parts):
    if not path_parts:
        return None
    qualifier = None
    if path_parts[-1] in _NOTE_QUALIFIER_EXPLANATIONS:
        *path_parts, qualifier = path_parts
    base_explanation = _base_explanation_for_path(tuple(path_parts))
    if qualifier is None:
        return base_explanation
    return {
        "label": base_explanation,
        "paras": (_NOTE_QUALIFIER_EXPLANATIONS[qualifier],),
    }


def _base_explanation_for_path(path_parts):
    if path_parts == ("NON_STANDARD_MARK_ORDER",):
        return " ".join(
            (
                "that the word's Hebrew combining marks are not in this project's",
                "standard internal mark order",
            )
        )
    family, *rest = path_parts
    if family == "qq":
        return _qq_explanation(rest)
    if family == "rare":
        return _rare_explanation(rest)
    if family == "varika":
        return _varika_explanation(rest)
    if family == "xatef-on-non-gutt":
        return _xatef_on_non_gutt_explanation(rest)
    assert False, path_parts


def _qq_explanation(path_parts):
    assert len(path_parts) == 1, path_parts
    accent_code = path_parts[0]
    accent_name = _QQ_ACCENT_NAMES[accent_code]
    return " ".join(
        (
            "that the word contains Unicode QAMATS QATAN immediately followed by",
            f"{accent_name}",
        )
    )


def _rare_explanation(path_parts):
    return _RARE_EXPLANATIONS[tuple(path_parts)]


def _varika_explanation(path_parts):
    if not path_parts:
        return "that the word contains Unicode JUDEO-SPANISH VARIKA"
    assert path_parts == ["two-in-a-word"] or tuple(path_parts) == ("two-in-a-word",)
    return "that the word contains Unicode JUDEO-SPANISH VARIKA twice"


def _xatef_on_non_gutt_explanation(path_parts):
    assert len(path_parts) == 1, path_parts
    return _XATEF_ON_NON_GUTT_EXPLANATIONS[path_parts[0]]


_RARE_EXPLANATIONS = {
    ("geresh-telisha-gedolah",): " ".join(
        (
            "that the word contains the rare Unicode sequence geresh plus telisha",
            "gedolah",
        )
    ),
    ("gershayim-telisha-gedolah",): " ".join(
        (
            "that the word contains the rare Unicode sequence gershayim plus telisha",
            "gedolah",
        )
    ),
    ("rafeh", "alef"): ("that the word contains Unicode RAFE on Hebrew letter alef"),
    ("rafeh", "he"): "that the word contains Unicode RAFE on Hebrew letter he",
    ("rafeh", "misc"): (
        "that the word contains Unicode RAFE on a letter other than alef or he"
    ),
    ("rafeh-with-dagesh",): (
        "that the word contains Unicode RAFE together with Unicode DAGESH OR MAPIQ"
    ),
    ("udot",): "that the word contains the extraordinary Unicode upper dot",
    ("udot-with-ldot",): " ".join(
        (
            "that the word contains both the extraordinary Unicode upper dot and the",
            "extraordinary Unicode lower dot",
        )
    ),
}


_XATEF_ON_NON_GUTT_EXPLANATIONS = {
    "patax": "that the word contains one ḥataf pataḥ on a non-guttural letter",
    "patax×2": "that the word contains two ḥataf pataḥ marks on non-guttural letters",
    "qamats": "that the word contains ḥataf qamats on a non-guttural letter",
    "segol": "that the word contains ḥataf segol on a non-guttural letter",
}


OVERALL_EXPLANATION = (
    " ".join(
        (
            "This page collects assorted Unicode-oriented categories in the MAM",
            "corpus. Some highlight unusual but intentional characters or character",
            "combinations, such as varika, rafeh, or the extraordinary upper and",
            "lower dots. Others collect patterns that are most naturally described",
            "in Unicode terms, such as qamats qatan followed immediately by another",
            "non-letter mark or ḥataf vowels on non-guttural letters. One",
            "category, NON_STANDARD_MARK_ORDER, is an internal check for this",
            "project's standard combining-mark order.",
        )
    ),
    " ".join(
        (
            "The qq labels mean qamats qatan followed immediately by another",
            "non-letter mark. The parenthesized code names that following mark:",
            "dex = deḥi, ger_m = geresh muqdam, mer = merkha, mos = meteg or",
            "silluq, mun = munaḥ, ole = oleh, qom = qadma or metigah, and tel_g =",
            "telisha gedolah. The xatef-on-non-gutt labels mean that a ḥataf vowel",
            "appears on a non-guttural consonant; patax×2 means the same word has",
            "two such ḥataf patah cases. The rafeh sublabels separate cases on",
            "alef, on he, and on other letters.",
        )
    ),
    " ".join(
        (
            "The suffixes doc-part-n and scrdfftar-note are context qualifiers",
            "rather than new Unicode phenomena. They indicate that the example",
            "occurs inside a documentation note or inside a scroll-difference note,",
            "respectively.",
        )
    ),
)
