# Initially generated by GitHub Copilot.
OVERALL_EXPLANATION_ALEF_VAV = (
    " ".join(
        (
            "This page groups words having the alef-vav dual-mater pattern.",
            "Most groups collect cases where alef-vav corresponds to a ḥolam vowel,",
            "while other groups collect cases where alef-vav corresponds to other vowels",
            "such as shuruq and ḥiriq.",
        )
    ),
    " ".join(
        (
            "The short labels are bucket names within this FOI search, not separate",
            "grammatical categories. In particular, a-misc is the residual bucket after",
            "the more specific named patterns are excluded.",
        )
    ),
)


EXPLANATIONS_ALEF_VAV = {
    ("a-misc",): " ".join(
        (
            "that the word contains alef-vav-ḥolam and does not fall under any of b-ot,",
            "c-m.lot, c-smol, or c-xatot",
        )
    ),
    ("d-alef-rafeh-shuruq",): {
        "label": "that the word contains a quiescent alef followed immediately by shuruq",
        "paras": ("Rows labeled no rafeh are the cases where the alef lacks rafeh.",),
    },
    ("e-alef-yod",): " ".join(
        (
            "that the word contains ḥiriq followed immediately by a bare alef and a",
            "bare yod",
        )
    ),
}


OVERALL_EXPLANATION_VAV_ALEF = (
    " ".join(
        (
            "This page groups words containing a vav-ḥolam-alef sequence, with the labels",
            "dividing the examples into a few recurring subpatterns and a miscellaneous",
            "remainder.",
        )
    ),
    " ".join(
        (
            "The short labels are bucket names within this FOI search, not separate",
            "grammatical categories. In particular, a-misc is the residual bucket after",
            "the more specific named patterns are excluded.",
        )
    ),
)


EXPLANATIONS_VAV_ALEF = {
    ("a-misc",): " ".join(
        (
            "that the word contains vav-ḥolam-alef and does not fall under a-misc/2 or",
            "b-not-final",
        )
    ),
    ("c-shuruq-alef",): {
        "label": "that the word contains shuruq followed immediately by a quiescent alef",
        "paras": (
            " ".join(
                (
                    "The explicit lexical exclusions are atoms whose consonant letters",
                    "reduce to הוא, including prefixed forms, and atoms whose consonant",
                    "letters end in יהוא.",
                )
            ),
        ),
    },
}
