# Initially generated by GitHub Copilot.
EXPLANATIONS_ALEF_VAV = {
    (
        "d-alef-no-rafe-shuruq",
    ): "that the word contains a quiescent alef followed immediately by shuruq, with no rafeh on the alef",
    (
        "d-alef-rafeh-shuruq",
    ): "that the word contains a quiescent alef followed immediately by shuruq, with rafeh on the alef",
}


EXPLANATIONS_VAV_ALEF = {
    ("c-shuruq-alef",): {
        "label": "that the word contains shuruq followed immediately by a quiescent alef",
        "paras": (
            "The explicit lexical exclusions are atoms whose consonant letters reduce to הוא, including prefixed forms, and atoms whose consonant letters end in יהוא.",
        ),
    },
}
