# Initially generated by GitHub Copilot.
OVERALL_EXPLANATION_ALEF_VAV = (
    "This page groups words containing an alef-vav-holam sequence, with the labels dividing the examples into a few recurring subpatterns and a miscellaneous remainder.",
    "The short labels are bucket names within this FOI search, not separate grammatical categories. In particular, a-misc is the residual bucket after the more specific named patterns are excluded.",
)


EXPLANATIONS_ALEF_VAV = {
    (
        "a-misc",
    ): "that the word contains alef-vav-ḥolam and does not fall under any of b-ot, c-m.lot, c-smol, or c-xatot",
    (
        "d-alef-no-rafe-shuruq",
    ): "that the word contains a quiescent alef followed immediately by shuruq, with no rafeh on the alef",
    (
        "d-alef-rafeh-shuruq",
    ): "that the word contains a quiescent alef followed immediately by shuruq, with rafeh on the alef",
}


OVERALL_EXPLANATION_VAV_ALEF = (
    "This page groups words containing a vav-holam-alef sequence, with the labels dividing the examples into a few recurring subpatterns and a miscellaneous remainder.",
    "The short labels are bucket names within this FOI search, not separate grammatical categories. In particular, a-misc is the residual bucket after the more specific named patterns are excluded.",
)


EXPLANATIONS_VAV_ALEF = {
    (
        "a-misc",
    ): "that the word contains vav-ḥolam-alef and does not fall under a-misc/2 or b-not-final",
    ("c-shuruq-alef",): {
        "label": "that the word contains shuruq followed immediately by a quiescent alef",
        "paras": (
            "The explicit lexical exclusions are atoms whose consonant letters reduce to הוא, including prefixed forms, and atoms whose consonant letters end in יהוא.",
        ),
    },
}
