# Initially generated by GitHub Copilot.
"""Compare two git revisions of MAM-parsed-plus/ JSON and generate an HTML
diff report with category filtering.

Usage:
    .venv/Scripts/python.exe py/main_diff.py mpp
    .venv/Scripts/python.exe py/main_diff.py mpp --old <rev> --new <rev>
    .venv/Scripts/python.exe py/main_diff.py mpp --all

The revisions are git refs in the ../MAM-parsed repo (commits, tags, branches).
Output goes to ../MAM-with-doc/gh-pages/change-log/ by default. If the hash range
matches an entry in releases.json, the release name is used as the filename;
otherwise the sanitised hash range is used.

The --all flag generates reports for every named release in releases.json
and regenerates index.html, including unpinned-latest when unreleased diffs exist.

When run with no arguments, the script compares the latest named release
(the release boundary closest to HEAD) against HEAD. If commits exist beyond
that release and produce diffs, it writes
../MAM-with-doc/gh-pages/change-log/unpinned-latest.html.
When unreleased diffs are absent, unpinned-latest artifacts are rewritten as
empty reports so stale content is not left behind.
"""

import argparse
import json
import os
import subprocess

from mb_cmn import paths
from mb_diff_mpu import (
    mpplus_classify,
    mpplus_extract,
    mpplus_html,
    mpplus_index,
    mpplus_json,
)

MAM_PARSED_DIR = str(paths.sibling_repo("MAM-parsed"))
CHANGE_LOG_DIR = str(paths.sibling_repo("MAM-with-doc") / "gh-pages" / "change-log")
RELEASES_JSON = f"{CHANGE_LOG_DIR}/releases.json"
UNPINNED_LATEST_HTML = f"{CHANGE_LOG_DIR}/unpinned-latest.html"
UNPINNED_LATEST_JSON = UNPINNED_LATEST_HTML.removesuffix(".html") + ".json"
PRESERVED_CHANGE_LOG_ARTIFACTS = (
    UNPINNED_LATEST_HTML,
    UNPINNED_LATEST_JSON,
)


def _commit_date(rev):
    """Return the commit date (YYYY-MM-DD) for a revision in MAM-parsed.

    Checked, because the date lands in the report's own heading: an unresolvable
    revision used to return "" here and the report was written with a blank date rather
    than not written at all.  Same 2026-08-31 finding as mpplus_extract._list_plus_files,
    where the shallow-clone case is set out.
    """
    result = subprocess.run(
        ["git", "-C", MAM_PARSED_DIR, "log", "-1", "--format=%cs", rev],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    return result.stdout.strip()


def _sanitize_rev(rev):
    """Make a revision string safe for use in a filename."""
    return (
        rev.replace("/", "_")
        .replace("\\", "_")
        .replace("..", "_")
        .replace("^", "-")[:20]
    )


def _lookup_release_name(old_rev, new_rev):
    """Return the release name if this hash range is in releases.json, else None."""
    if not os.path.isfile(RELEASES_JSON):
        return None
    with open(RELEASES_JSON, "r", encoding="utf-8") as in_fp:
        releases = json.load(in_fp)
    for entry in releases["releases"]:
        if entry["old"] == old_rev and entry["new"] == new_rev:
            return entry["name"]
    return None


def _latest_release_entry():
    """Return the release entry whose `new` boundary is closest to HEAD."""
    with open(RELEASES_JSON, "r", encoding="utf-8") as in_fp:
        data = json.load(in_fp)
    best_entry = None
    best_distance = None
    for entry in data["releases"]:
        distance = _count_newer_commits(entry["new"])
        if best_distance is None or distance < best_distance:
            best_distance = distance
            best_entry = entry
    return best_entry


def _count_newer_commits(base_rev):
    """Return how many commits exist in MAM-parsed between base_rev and HEAD."""
    result = subprocess.run(
        ["git", "-C", MAM_PARSED_DIR, "rev-list", "--count", f"{base_rev}..HEAD"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    return int(result.stdout.strip())


def default_output_path(old_rev, new_rev):
    """Build the default output path inside the change-log directory."""
    name = _lookup_release_name(old_rev, new_rev)
    if name is not None:
        slug = name
    else:
        slug = f"{_sanitize_rev(old_rev)}_{_sanitize_rev(new_rev)}"
    return f"{CHANGE_LOG_DIR}/{slug}.html"


def generate_report(old_rev, new_rev, output, *, write_when_empty=True):
    """Generate one diff report. Returns the expanded diff count."""
    print(f"Comparing {old_rev} -> {new_rev} ...")
    diffs = mpplus_extract.diff_all_books(old_rev, new_rev)
    print(f"  {len(diffs)} raw changes found")
    if not diffs and not write_when_empty:
        print("  No diffs found; not writing report")
        return 0, _commit_date(old_rev)
    mpplus_classify.classify_diffs(diffs)
    from mb_diff_mpu import mpplus_verify

    verification_errors = mpplus_verify.verify_all(diffs)
    if verification_errors:
        raise mpplus_verify.VerificationError(
            f"{len(verification_errors)} diff(s) failed roundtrip verification; "
            "no JSON or HTML report was written"
        )
    old_date = _commit_date(old_rev)
    new_date = _commit_date(new_rev)
    os.makedirs(os.path.dirname(output), exist_ok=True)
    json_path = output.removesuffix(".html") + ".json"
    mpplus_json.write_json(diffs, old_rev, new_rev, json_path)
    print(f"  JSON written to {json_path}")
    total = mpplus_html.write_report(
        diffs, old_rev, new_rev, output, old_date, new_date
    )
    print(f"  Report written to {output}")
    return total, old_date


def run_all():
    """Generate reports for named releases plus unpinned-latest, then write index."""
    with open(RELEASES_JSON, "r", encoding="utf-8") as in_fp:
        data = json.load(in_fp)
    release_info = []
    for entry in data["releases"]:
        output = f"{CHANGE_LOG_DIR}/{entry['name']}.html"
        count, old_date = generate_report(entry["old"], entry["new"], output)
        release_info.append(
            {"name": entry["name"], "count": count, "old_date": old_date}
        )
    unpinned_info = run_unpinned_latest()
    if unpinned_info is not None:
        release_info.append(unpinned_info)
    mpplus_index.write_index(release_info, CHANGE_LOG_DIR)


def run_unpinned_latest():
    """Generate unpinned-latest report and return its index entry, else None."""
    latest_release = _latest_release_entry()
    if latest_release is None:
        raise RuntimeError("releases.json has no release entries")
    old_rev = latest_release["new"]
    commit_count = _count_newer_commits(old_rev)
    if commit_count == 0:
        generate_report(
            old_rev,
            "HEAD",
            UNPINNED_LATEST_HTML,
            write_when_empty=True,
        )
        print(
            f"No commits after latest named release ({old_rev}); "
            "wrote empty unpinned-latest artifacts: "
            f"{', '.join(PRESERVED_CHANGE_LOG_ARTIFACTS)}"
        )
        return None
    count, old_date = generate_report(
        old_rev,
        "HEAD",
        UNPINNED_LATEST_HTML,
        write_when_empty=True,
    )
    if count == 0:
        print(
            "No diffs in unreleased commit range; wrote empty "
            "unpinned-latest artifacts"
        )
        return None
    return {"name": "unpinned-latest", "count": count, "old_date": old_date}


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--all",
        action="store_true",
        help="Generate all named releases from releases.json and regenerate index.html",
    )
    parser.add_argument("--old", help="Old git revision (in ../MAM-parsed repo)")
    parser.add_argument("--new", help="New git revision (in ../MAM-parsed repo)")
    parser.add_argument(
        "--output",
        default=None,
        help="Output HTML path (default: auto from releases.json or hash range)",
    )


def run_from_args(args: argparse.Namespace) -> None:
    if args.all:
        if args.old or args.new or args.output:
            raise SystemExit("--all cannot be combined with --old, --new, or --output")
        run_all()
        return
    if args.old or args.new:
        if not args.old or not args.new:
            raise SystemExit("--old and --new must be provided together")
        output = args.output or default_output_path(args.old, args.new)
        generate_report(args.old, args.new, output)
        return
    if args.output:
        raise SystemExit("--output requires --old and --new")
    run_unpinned_latest()
