# Initially generated by GitHub Copilot.
"""Download MAM data from Sefaria and write it to CSV files.

Usage:
    .venv/Scripts/python.exe py/main_download.py fr-sefaria
    .venv/Scripts/python.exe py/main_download.py fr-sefaria --book39 1Kings
"""

from mb_cmn import file_io
from mb_cmn import polite_download
from mb_misc import my_utils_for_mainish as my_utils_fm
from mb_sefaria import sef_cmn


def _download_book(sebn, downloader):
    # sebn: Sefaria English Book Name
    base = "https://www.sefaria.org/download/version"
    lang = "he"
    version = "Miqra%20according%20to%20the%20Masorah"
    csv_url = f"{base}/{sebn}%20-%20{lang}%20-%20{version}.csv"
    out_path = f"in/mam-from-sefaria/{sebn}.csv"
    my_utils_fm.show_progress_g(__file__, out_path)
    text = downloader.get_text(csv_url)
    # repls = (
    #     (sd.NBSP, '&nbsp;'),
    #     (sd.THSP, '&thinsp;'),
    #     (WIKISOURCE_URL_HE, WIKISOURCE_URL_ENG)
    # )
    # for repl in repls:
    #     text = text.replace(*repl)
    file_io.with_tmp_openw(out_path, {"newline": ""}, _write_callback, text)


def _write_callback(text, out_fp):
    out_fp.write(text)


def run(bkids):
    """Download MAM books from Sefaria."""
    with polite_download.PoliteDownloader(_SEFARIA_DOWNLOAD_CONFIG) as downloader:
        for bkid in bkids:
            _download_book(sef_cmn.SEF_BKNA[bkid], downloader)


_SEFARIA_DOWNLOAD_CONFIG = polite_download.PoliteDownloadConfig(
    user_agent="Denckla-Dowload-MAM-Bot/1.1 (https://www.sefaria.org)",
    default_timeout_s=30.0,
    accept_language="he,en;q=0.5",
    throttle=polite_download.ThrottleConfig(min_delay_s=1.5, mean_delay_s=3.0),
    retry=polite_download.RetryConfig(max_attempts=4),
    cache=polite_download.CacheConfig(dir_path=".novc/http-cache/sefaria"),
    obey_robots_txt=True,
)
