# Initially generated by GitHub Copilot.
"""Edit Hebrew Wikisource pages using a pywikibot-based automation bot.

Usage (run from repo root):
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:path/to/.pywikibot
    $env:PYWIKIBOT_DIR="$env:USERPROFILE/.pywikibot"; .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:... --book39 Deuter
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:... --section6 SifEm
"""

import os
import json
from urllib import parse
from urllib import request

import pywikibot

from mb_cmn import bib_locales as tbn
from mb_cmn import file_io
from mb_cmn import mam_bknas_and_std_bknas as mbkn_a_sbkn
from mb_misc import my_utils_for_mainish as my_utils_fm
from py_misc import get_wikisource_plan as wsplan
from ws import ws_bot_edit as wbe


def run(edits_path, book_plans, pywikibot_args):
    """Use a bot to process chapters of Hebrew Wikisource."""
    _assert_pywikibot_dir_configured(pywikibot_args)
    edits_ctx = wbe.load_edits(edits_path)
    summary = edits_ctx["summary"]
    assert summary
    site = pywikibot.Site("he", "wikisource", "BDencklaBot")
    botctx = {
        "botctx-site": site,
        "botctx-summary": summary,
        "botctx-edits-ctx": edits_ctx,
        "botctx-modified-pages": [],
    }
    for book_plan in book_plans:
        _run_bot_on_book(botctx, book_plan)
    wbe.write_warnings(edits_ctx, _OUT_PATH_WARNINGS)
    wbe.write_modified_chapters(edits_ctx, _OUT_PATH_MODIFIED_CHAPTERS)
    _write_modified_chapter_diffs_md(
        botctx["botctx-modified-pages"],
        _OUT_PATH_MODIFIED_CHAPTER_DIFFS_MD,
    )


def _run_bot_on_chapter(botctx, bkid, out_book_contents, chapter_plan):
    he_chnu, title = chapter_plan
    summary = botctx["botctx-summary"]
    edits_ctx = botctx["botctx-edits-ctx"]
    modified_pages = botctx["botctx-modified-pages"]
    site = botctx["botctx-site"]
    page = pywikibot.Page(site, title)
    orig_text = page.text
    page.text = wbe.edit_page_text(edits_ctx, bkid, he_chnu, page.text)
    if page.text != orig_text:
        edits_ctx["modified-chapters"].append((bkid, he_chnu))
        page.save(summary)
        newrevid, oldrevid = _latest_two_revids(title)
        modified_pages.append(
            {
                "title": title,
                "newrevid": newrevid,
                "oldrevid": oldrevid,
            }
        )
    out_book_contents[he_chnu] = page.text.splitlines()


def _latest_two_revids(title):
    api_url = "https://he.wikisource.org/w/api.php?" + parse.urlencode(
        {
            "action": "query",
            "format": "json",
            "prop": "revisions",
            "rvlimit": 2,
            "rvprop": "ids",
            "titles": title,
        }
    )
    with request.urlopen(api_url) as response:
        data = json.loads(response.read().decode("utf-8"))
    page_obj = next(iter(data["query"]["pages"].values()))
    revisions = page_obj["revisions"]
    assert len(revisions) >= 2, (title, data)
    return revisions[0]["revid"], revisions[1]["revid"]


def _diff_url(title, newrevid, oldrevid):
    title_enc = parse.quote(title, safe="")
    return (
        "https://he.wikisource.org/w/index.php?"
        f"title={title_enc}&diff={newrevid}&oldid={oldrevid}"
    )


def _modified_chapter_diffs_markdown(modified_pages):
    if not modified_pages:
        return "_No modified chapters in this run._\n"
    lines = [
        f"- [{entry['title']}]({_diff_url(entry['title'], entry['newrevid'], entry['oldrevid'])})"
        for entry in modified_pages
    ]
    return "\n".join(lines) + "\n"


def _write_modified_chapter_diffs_md(modified_pages, out_path):
    markdown = _modified_chapter_diffs_markdown(modified_pages)
    file_io.with_tmp_openw(out_path, {}, _write_text, markdown)


def _write_text(text, outfp):
    outfp.write(text)


def _write_book(book_contents, he_bn_sbn):
    # he_bn_sbn: Hebrew book name and sub-book name (a pair) (aka mam_he_book_name_pair)
    bkid = mbkn_a_sbkn.MAM_HBNP_TO_BK39ID[he_bn_sbn]
    osdf = tbn.ordered_short_dash_full_39(bkid)
    out_path = f"{_OUT_PATH_BOOKS}/{osdf}.json"
    my_utils_fm.show_progress_g(__file__, out_path)
    file_io.json_dump_to_file_path(book_contents, out_path)


def _run_bot_on_book(botctx, book_plan):
    he_bn_sbn, _he_chnus = book_plan
    bkid = mbkn_a_sbkn.MAM_HBNP_TO_BK39ID[he_bn_sbn]
    book_contents = {}
    for chapter_plan in wsplan.get_chapter_plans(book_plan):
        _run_bot_on_chapter(botctx, bkid, book_contents, chapter_plan)
    _write_book(book_contents, he_bn_sbn)


def _assert_pywikibot_dir_configured(pywikibot_args):
    pywikibot_dir = _resolve_pywikibot_dir(pywikibot_args)
    if not pywikibot_dir:
        raise SystemExit(
            "Missing pywikibot config directory. Pass -dir:<path-to-.pywikibot> "
            "or set PYWIKIBOT_DIR. See py/ws/pywikibot-setup.md"
        )
    _assert_pywikibot_auth_files_present(pywikibot_dir)


def _resolve_pywikibot_dir(pywikibot_args):
    dir_arg = _dir_from_pywikibot_args(pywikibot_args)
    if dir_arg:
        return _normalize_path(dir_arg)
    env_dir = os.environ.get("PYWIKIBOT_DIR")
    if env_dir:
        return _normalize_path(env_dir)
    env_dir_pwb = os.environ.get("PYWIKIBOT_DIR_PWB")
    if env_dir_pwb:
        return _normalize_path(env_dir_pwb)
    return None


def _dir_from_pywikibot_args(pywikibot_args):
    for idx, arg in enumerate(pywikibot_args):
        if arg.startswith("-dir:"):
            return arg.split(":", 1)[1]
        if arg == "-dir" and idx + 1 < len(pywikibot_args):
            return pywikibot_args[idx + 1]
    return None


def _normalize_path(path):
    return os.path.abspath(os.path.expanduser(os.path.expandvars(path)))


def _assert_pywikibot_auth_files_present(pywikibot_dir):
    user_config_path = os.path.join(pywikibot_dir, "user-config.py")
    password_path = os.path.join(pywikibot_dir, "password.py")
    if not os.path.isfile(user_config_path):
        raise SystemExit(f"Missing {user_config_path}. See py/ws/pywikibot-setup.md")
    if not os.path.isfile(password_path):
        raise SystemExit(f"Missing {password_path}. See py/ws/pywikibot-setup.md")


_OUT_PATH_BOOKS = "out/mam-ws-bot/real"
_OUT_PATH_MISC = "out/mam-ws-bot/real-misc"
_OUT_PATH_WARNINGS = f"{_OUT_PATH_MISC}/warnings.json"
_OUT_PATH_MODIFIED_CHAPTERS = f"{_OUT_PATH_MISC}/modified-chapters.json"
_OUT_PATH_MODIFIED_CHAPTER_DIFFS_MD = f"{_OUT_PATH_MISC}/modified-chapter-diffs.md"
