# Initially generated by GitHub Copilot.
"""Edit Hebrew Wikisource pages using a pywikibot-based automation bot.

Usage (run from repo root):
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:path/to/.pywikibot
    $env:PYWIKIBOT_DIR="$env:USERPROFILE/.pywikibot"; .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:... --book39 Deuter
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:... --section6 SifEm
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:... --no-post-download
    .venv/Scripts/python.exe py/main_ws_bot.py real --edits path.json -dir:... --identity-run
"""

import argparse
import os
import json
from datetime import datetime
from urllib import parse
from urllib import request

import pywikibot

from mb_cmn import bib_locales as tbn
from mb_cmn import file_io
from mb_cmn import hebrew_verse_numerals as hvn
from mb_cmn import mam_bknas_and_std_bknas as mbkn_a_sbkn
from mb_misc import my_utils_for_mainish as my_utils_fm
from py_misc import get_wikisource_plan as wsplan
from subcommands import download_wikisource
from ws import ws_bot_edit as wbe
from ws import ws_download_selector as wsds


def run(
    edits_path,
    book_plans,
    pywikibot_args,
    post_download=True,
    identity_run=False,
):
    """Use a bot to process chapters of Hebrew Wikisource."""
    _assert_pywikibot_dir_configured(pywikibot_args)
    run_paths = _build_run_paths()
    my_utils_fm.show_progress_g(__file__, "run-artifacts", run_paths["run-root"])
    if identity_run and post_download:
        my_utils_fm.show_progress_g(
            __file__,
            "identity-run",
            "post-download disabled during identity-run",
        )
    edits_ctx = wbe.load_edits(edits_path)
    wbe.assert_book_plans_within_target_set(edits_ctx, book_plans)
    summary = edits_ctx["summary"]
    assert summary
    site = pywikibot.Site("he", "wikisource", "BDencklaBot")
    botctx = {
        "botctx-site": site,
        "botctx-summary": summary,
        "botctx-edits-ctx": edits_ctx,
        "botctx-modified-pages": [],
        "botctx-run-paths": run_paths,
        "botctx-identity-run": identity_run,
        "botctx-identity-mismatches": [],
    }
    for book_plan in book_plans:
        _run_bot_on_book(botctx, book_plan)
    wbe.write_warnings(edits_ctx, run_paths["warnings"])
    wbe.write_modified_chapters(edits_ctx, run_paths["modified-chapters"])
    _write_modified_chapter_diffs_md(
        botctx["botctx-modified-pages"],
        run_paths["modified-chapter-diffs-md"],
    )
    _raise_if_identity_mismatches(botctx["botctx-identity-mismatches"])
    if post_download and not identity_run:
        _download_modified_chapters(run_paths["modified-chapters"])


def _run_bot_on_chapter(botctx, bkid, chapter_plan):
    he_chnu, title = chapter_plan
    summary = botctx["botctx-summary"]
    edits_ctx = botctx["botctx-edits-ctx"]
    modified_pages = botctx["botctx-modified-pages"]
    run_paths = botctx["botctx-run-paths"]
    identity_run = botctx["botctx-identity-run"]
    identity_mismatches = botctx["botctx-identity-mismatches"]
    site = botctx["botctx-site"]
    page = pywikibot.Page(site, title)
    orig_text = page.text
    page.text = wbe.edit_page_text(edits_ctx, bkid, he_chnu, page.text)
    if page.text != orig_text:
        edits_ctx["modified-chapters"].append((bkid, he_chnu))
        if identity_run:
            identity_mismatches.append(
                {
                    "bkid": bkid,
                    "he_chnu": he_chnu,
                    "title": title,
                }
            )
        else:
            page.save(summary)
            newrevid, oldrevid = _latest_two_revids(title)
            modified_pages.append(
                {
                    "title": title,
                    "newrevid": newrevid,
                    "oldrevid": oldrevid,
                }
            )
    _write_chapter(run_paths["chapters-dir"], bkid, he_chnu, page.text.splitlines())


def _raise_if_identity_mismatches(identity_mismatches):
    if not identity_mismatches:
        return
    mismatch_lines = [
        f"- {entry['bkid']} chapter {hvn.STR_TO_INT_DIC[entry['he_chnu']]} ({entry['title']})"
        for entry in identity_mismatches
    ]
    raise SystemExit(
        "identity-run failed: the following chapters would change:\n"
        + "\n".join(mismatch_lines)
    )


def _build_run_paths():
    run_root = os.path.join(_REAL_RUNS_ROOT, _run_timestamp())
    chapters_dir = os.path.join(run_root, "chapters")
    misc_dir = os.path.join(run_root, "misc")
    return {
        "run-root": run_root,
        "chapters-dir": chapters_dir,
        "warnings": os.path.join(misc_dir, "warnings.json"),
        "modified-chapters": os.path.join(misc_dir, "modified-chapters.json"),
        "modified-chapter-diffs-md": os.path.join(
            misc_dir, "modified-chapter-diffs.md"
        ),
    }


def _run_timestamp():
    return datetime.now().strftime("%Y%m%d-%H%M%S-%f")


def _latest_two_revids(title):
    api_url = "https://he.wikisource.org/w/api.php?" + parse.urlencode(
        {
            "action": "query",
            "format": "json",
            "prop": "revisions",
            "rvlimit": 2,
            "rvprop": "ids",
            "titles": title,
        }
    )
    with request.urlopen(api_url) as response:
        data = json.loads(response.read().decode("utf-8"))
    page_obj = next(iter(data["query"]["pages"].values()))
    revisions = page_obj["revisions"]
    assert len(revisions) >= 2, (title, data)
    return revisions[0]["revid"], revisions[1]["revid"]


def _diff_url(title, newrevid, oldrevid):
    title_enc = parse.quote(title, safe="")
    return (
        "https://he.wikisource.org/w/index.php?"
        f"title={title_enc}&diff={newrevid}&oldid={oldrevid}"
    )


def _modified_chapter_diffs_markdown(modified_pages):
    if not modified_pages:
        return "_No modified chapters in this run._\n"
    lines = [
        f"- [{entry['title']}]({_diff_url(entry['title'], entry['newrevid'], entry['oldrevid'])})"
        for entry in modified_pages
    ]
    return "\n".join(lines) + "\n"


def _write_modified_chapter_diffs_md(modified_pages, out_path):
    markdown = _modified_chapter_diffs_markdown(modified_pages)
    file_io.with_tmp_openw(out_path, {}, _write_text, markdown)


def _write_text(text, outfp):
    outfp.write(text)


def _chapter_out_filename(bkid, he_chnu):
    osdf = tbn.ordered_short_dash_full_39(bkid)
    chapter = hvn.STR_TO_INT_DIC[he_chnu]
    return f"{osdf}-{chapter:0{_chapter_pad_width(bkid)}d}.json"


def _chapter_pad_width(bkid):
    if bkid == tbn.BK_PSALMS:
        return 3
    return 2


def _write_chapter(chapters_dir, bkid, he_chnu, chapter_lines):
    out_path = os.path.join(chapters_dir, _chapter_out_filename(bkid, he_chnu))
    my_utils_fm.show_progress_g(__file__, out_path)
    file_io.json_dump_to_file_path(chapter_lines, out_path)


def _run_bot_on_book(botctx, book_plan):
    he_bn_sbn, _he_chnus = book_plan
    bkid = mbkn_a_sbkn.MAM_HBNP_TO_BK39ID[he_bn_sbn]
    for chapter_plan in wsplan.get_chapter_plans(book_plan):
        _run_bot_on_chapter(botctx, bkid, chapter_plan)


def _assert_pywikibot_dir_configured(pywikibot_args):
    pywikibot_dir = _resolve_pywikibot_dir(pywikibot_args)
    if not pywikibot_dir:
        raise SystemExit(
            "Missing pywikibot config directory. Pass -dir:<path-to-.pywikibot> "
            "or set PYWIKIBOT_DIR. See py/ws/pywikibot-setup.md"
        )
    _assert_pywikibot_auth_files_present(pywikibot_dir)


def _resolve_pywikibot_dir(pywikibot_args):
    dir_arg = _dir_from_pywikibot_args(pywikibot_args)
    if dir_arg:
        return _normalize_path(dir_arg)
    env_dir = os.environ.get("PYWIKIBOT_DIR")
    if env_dir:
        return _normalize_path(env_dir)
    env_dir_pwb = os.environ.get("PYWIKIBOT_DIR_PWB")
    if env_dir_pwb:
        return _normalize_path(env_dir_pwb)
    return None


def _dir_from_pywikibot_args(pywikibot_args):
    for idx, arg in enumerate(pywikibot_args):
        if arg.startswith("-dir:"):
            return arg.split(":", 1)[1]
        if arg == "-dir" and idx + 1 < len(pywikibot_args):
            return pywikibot_args[idx + 1]
    return None


def _normalize_path(path):
    return os.path.abspath(os.path.expanduser(os.path.expandvars(path)))


def _assert_pywikibot_auth_files_present(pywikibot_dir):
    user_config_path = os.path.join(pywikibot_dir, "user-config.py")
    password_path = os.path.join(pywikibot_dir, "password.py")
    if not os.path.isfile(user_config_path):
        raise SystemExit(f"Missing {user_config_path}. See py/ws/pywikibot-setup.md")
    if not os.path.isfile(password_path):
        raise SystemExit(f"Missing {password_path}. See py/ws/pywikibot-setup.md")


def _download_modified_chapters(modified_chapters_path):
    selector_args = argparse.Namespace(
        book39=None,
        chapter=None,
        book_chapters_json=modified_chapters_path,
        section6=None,
    )
    modified_book_plans = wsds.selected_book_plans(selector_args)
    if not modified_book_plans:
        my_utils_fm.show_progress_g(__file__, "post-download", "no modified chapters")
        return
    my_utils_fm.show_progress_g(
        __file__,
        "post-download",
        modified_chapters_path,
    )
    download_wikisource.run(modified_book_plans)


_REAL_RUNS_ROOT = ".novc/mam-ws-bot-real-runs"
